### ISSUE TITLE
multi-device whatsapp socket exit after i scan the qr

### ISSUE THREAD

**Issue by zhengshengjie666** [adiwajshing/Baileys#1017]
this is my code url：
https://github.com/adiwajshing/Baileys/tree/multi-device

this is the error info:

saving auth state
connection update { isNewLogin: true, qr: undefined }
{"level":30,"time":1639548755543,"pid":10960,"hostname":"LAPTOP-1VQLDJ2U","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"},"headers":{}}},"msg":"connection closed"}

connection closed
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Stream Errored
        at WebSocket.<anonymous> (D:\works\whatsapp-workspace\Baileys\src\Socket\socket.ts:527:13)
        at WebSocket.emit (node:events:394:28)
        at WebSocket.emit (node:domain:475:12)
        at D:\works\whatsapp-workspace\Baileys\src\Socket\socket.ts:261:35
        at Object.decodeFrame (D:\works\whatsapp-workspace\Baileys\src\Utils\noise-handler.ts:162:5)
        at WebSocket.onMessageRecieved (D:\works\whatsapp-workspace\Baileys\src\Socket\socket.ts:237:15)
        at WebSocket.emit (node:events:394:28)
        at WebSocket.emit (node:domain:475:12)
        at Receiver.receiverOnMessage (D:\works\whatsapp-workspace\Baileys\node_modules\ws\lib\websocket.js:1093:20)
        at Receiver.emit (node:events:394:28) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2021-12-15T04:01:11.963Z
  }
}

**To Reproduce**
1. yarn example
2. scan the qr 
3. the socket return the ‘connect close ’；and tips 'Restart Required'

**Expected behavior**
the socket is normal

**Comment by mateuscdor** [comment]
Please put in the language (English)

**Comment by zhengshengjie666** [comment]
我重启下了下vs code就好了，感谢各位的支持

**Comment by zhengshengjie666** [comment]
this error is continue

**Comment by mateuscdor** [comment]
Here is the example of Baileys-Md (mult-device)
is working normally.

The problem is definitely in your code.
If you are running in javascript
compile and run the example and see if the error occurs.
https://github.com/adiwajshing/Baileys/blob/multi-device/Example/example.ts

**Comment by itacirgabral** [comment]
> multi-device whatsapp socket exit after i scan the qr

It is supposed to happen. You sould connect soon using the new credentials to complete de signup. So the connection does not close anymore.
