### ISSUE TITLE
[BUG] groupMetadata Error

### ISSUE THREAD

**Issue by KingAndrewYT** [adiwajshing/Baileys#1019]
BaileysError: Unexpected status in 'query': Internal Server Error(500)
    at WAConnection.query (/root/kaytbot-b/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:237:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WAConnection.fetchGroupMetadataFromWA (/root/kaytbot-b/node_modules/@adiwajshing/baileys/lib/WAConnection/8.Groups.js:19:30)
    at async WAConnection.groupMetadata (/root/kaytbot-b/node_modules/@adiwajshing/baileys/lib/WAConnection/8.Groups.js:167:28)
    at async /root/kaytbot-b/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:32
    at async KAYTmsg (file:///root/kaytbot-b/KAYTmsg.js:133:41)
    at async WAConnection.<anonymous> (file:///root/kaytbot-b/index.js:114:13) {
  status: 500,
  context: {
    query: [ 'query', 'GroupMetadata', '120363023236413273@g.us' ],
    message: 'Internal Server Error',
    status: 500
  }
}

**Comment by Ramlan404** [comment]
this.version = [2, 2140, 12] to this.version = [2, 2140, 14]

**Comment by zatu22** [comment]
> 

not working for me

**Comment by zadik-hacker** [comment]
this.version = [2, 2140, 14] , it works but it keeps dropping and giving a query and you have to keep reconnecting

**Comment by SheIITear** [comment]
Use this [2, 2146, 9]

**Comment by itsMySky** [comment]
change groupMetadata

const groupMetadata = isGroup ? await conn.groupMetadata(from) : 'query'.toString
