### ISSUE TITLE
[BUG][MD] axios error on message upsert

### ISSUE THREAD

**Issue by bigbdigital** [adiwajshing/Baileys#1050]
In new update with axios, i got erro

TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Range"
    at ClientRequest.setHeader (node:_http_outgoing:579:3)
    at new ClientRequest (node:_http_client:256:14)
    at Object.request (node:https:353:10)
    at RedirectableRequest._performRequest (/var/www/bll/node_modules/follow-redirects/index.js:279:24)
    at new RedirectableRequest (/var/www/bll/node_modules/follow-redirects/index.js:61:8)
    at Object.request (/var/www/bll/node_modules/follow-redirects/index.js:482:14)
    at dispatchHttpRequest (/var/www/bll/node_modules/axios/lib/adapters/http.js:226:25)
    at new Promise (<anonymous>)
    at httpAdapter (/var/www/bll/node_modules/axios/lib/adapters/http.js:48:10)
    at dispatchRequest (/var/www/bll/node_modules/axios/lib/core/dispatchRequest.js:58:10) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}

**Comment by bigbdigital** [comment]
more erro detail with a pino log

{
	"level": 50,
	"time": 1639932696143,
	"pid": 3441939,
	"hostname": "sd-bigbangshop-3",
	"trace": "TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value \"undefined\" for header \"Range\"\n    at ClientRequest.setHeader (node:_http_outgoing:579:3)\n    at new ClientRequest (node:_http_client:256:14)\n    at Object.request (node:https:353:10)\n    at RedirectableRequest._performRequest (/var/www/bll/node_modules/follow-redirects/index.js:279:24)\n    at new RedirectableRequest (/var/www/bll/node_modules/follow-redirects/index.js:61:8)\n    at Object.request (/var/www/bll/node_modules/follow-redirects/index.js:482:14)\n    at dispatchHttpRequest (/var/www/bll/node_modules/axios/lib/adapters/http.js:226:25)\n    at new Promise (<anonymous>)\n    at httpAdapter (/var/www/bll/node_modules/axios/lib/adapters/http.js:48:10)\n    at dispatchRequest (/var/www/bll/node_modules/axios/lib/core/dispatchRequest.js:58:10)",
	"node": {
		"tag": "notification",
		"attrs": {
			"from": "@s.whatsapp.net",
			"type": "server_sync",
			"id": "4233597710",
			"t": "1639932575"
		},
		"content": [{
			"tag": "collection",
			"attrs": {
				"name": "critical_unblock_low",
				"version": "47"
			},
			"content": null
		}]
	},
	"msg": "failed to sync state"
}

**Comment by adiwajshing** [comment]
Thanks for pointing it out, fixed in latest commit
