### ISSUE TITLE
[MD] ChatModify not cleaning all messages from group

### ISSUE THREAD

**Issue by guiireal** [adiwajshing/Baileys#1083]
I try to clear a chat group, but it gives the following error:

![image](https://user-images.githubusercontent.com/13739343/147392408-0734d2f2-69f4-403d-8f4d-805543b4dea4.png)
`(node:23280) UnhandledPromiseRejectionWarning: Error: not supported
    at Object.chatModificationToAppPatch (/home/guiireal/projects/spider/bot/node_modules/@adiwajshing/baileys-md/lib/Utils/chat-utils.js:395:19)
    at Object.chatModify (/home/guiireal/projects/spider/bot/node_modules/@adiwajshing/baileys-md/lib/Socket/chats.js:481:31)
    at /home/guiireal/projects/spider/bot/src/support/baileys-md/commands/clearall.ts:29:16
    at step (/home/guiireal/projects/spider/bot/src/support/baileys-md/commands/clearall.ts:33:23)
    at Object.next (/home/guiireal/projects/spider/bot/src/support/baileys-md/commands/clearall.ts:14:53)
    at fulfilled (/home/guiireal/projects/spider/bot/src/support/baileys-md/commands/clearall.ts:5:58)
(Use `node --trace-warnings ...` to show where the warning was created)`

My Code:

![image](https://user-images.githubusercontent.com/13739343/147392382-00c80708-64e5-4a3d-86b3-ce1b7d4e23b7.png)
> The `remoteJid` variable returns the jid from a group with format: number-code@g.us

Any idea to solve this?

**Comment by guiireal** [comment]
Note:

I found the line where the error is being triggered, is this possible in the new version of the multi device?

![image](https://user-images.githubusercontent.com/13739343/147392828-56ed9f07-7b62-4f3e-8f72-f456d6b368b4.png)
> In `@adiwajshing/baileys-md/lib/Utils/chat-utils.js`, line `395`

**Comment by BochilGaming** [comment]
clear all not support

**Comment by guiireal** [comment]
> Clear all does not support, instead use clear

Do you know if this is a limitation of whatsapp multidevice?
