### ISSUE TITLE
[solved] error on call base64EncodedAuthInfo()

### ISSUE THREAD

**Issue by jchiavellibr** [adiwajshing/Baileys#1087]
**Error:**
```
TypeError: Cannot read properties of undefined (reading 'toString')
    at WAConnection.base64EncodedAuthInfo (C:\Users\x\Documents\Embarcadero\Studio\Projects\SisLoja2020\wtz\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:127:42)
    at WAConnection.<anonymous> (C:\Users\x\Documents\Embarcadero\Studio\Projects\SisLoja2020\wtz\App\appo.js:1:4309)
    at WAConnection.emit (node:events:402:35)
    at WAConnection.emit (node:domain:475:12)
    at WAConnection.emit (C:\Users\x\Documents\Embarcadero\Studio\Projects\SisLoja2020\wtz\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41)
    at WAConnection.connect (C:\Users\x\Documents\Embarcadero\Studio\Projects\SisLoja2020\wtz\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at run (C:\Users\x\Documents\Embarcadero\Studio\Projects\SisLoja2020\wtz\App\appo.js:1:4711)
```

**Code:**
```
import {
    Browsers,
    MessageType,
    ReconnectMode,
    WAConnection,
} from '@adiwajshing/baileys';

import * as fs from 'fs';
...
async function run() {
    conn = new WAConnection();
    conn.browserDescription = Browsers.appropriate('Chrome');
    conn.autoReconnect = ReconnectMode.onConnectionLost ;
    conn.connectOptions.maxRetries = 10;
    conn.connectOptions.connectCooldownMs = 8000;
    conn.logger.level = 'error';

    if (fs.existsSync('./auth_info.json')) {
        conn.loadAuthInfo ('./auth_info.json');
    } else {
        console.log('\n\n' + colors.bold.bgRed.yellow('  LEIA O CÓDIGO COM O  WHATSAPP DO CELULAR   '));
    }

    conn.on ('open', () => {
        try {
            const authInfo = conn.base64EncodedAuthInfo();    **//  <= error**
            fs.writeFileSync('./auth_info.json', JSON.stringify(authInfo, null, '\t')) ;
        }catch (e){
            console.log(e);
        }
    })

    conn.on('close', ({reason, isReconnecting}) => {
        console.log(colors.bold.bgYellow.red(' *** desconectado de web.whatsapp.com ***'));
    })

    try {
        await conn.connect()
    } catch (err) {
        console.log( colors.bold.bgRed.yellow( 'Ocorreu um erro ao conectar com o servidor do Whatsapp: ' + err));
        fs.existsSync('./auth_info.json') && fs.unlinkSync('./auth_info.json');
        setTimeout(run, 2000);
        return;
    }
...
}
```

**in 0.Base.js:121  only "authInfo.clientID" is filled**
```
base64EncodedAuthInfo() {
        console.log(this.authInfo);   // result:   { clientID: 'xxxxxf+e2ls0/VqqP5L8NQ==' }
        return {
            clientID: this.authInfo.clientID,
            serverToken: this.authInfo.serverToken,
            clientToken: this.authInfo.clientToken,
            encKey: this.authInfo.encKey.toString('base64'),
            macKey: this.authInfo.macKey.toString('base64'),
        };
    }
```

**Config:**
NodeJS v16.13.1
npm 7.14.0
Windows 11

**package.json:**
...
"dependencies": {
    "@adiwajshing/baileys": "^3.5.2",
    "@adiwajshing/keyed-db": "^0.2.2",
    "colors": "^1.4.0",
    "curve25519-js": "^0.0.4",
    "futoin-hkdf": "^1.3.2",
    "got": "^11.8.1",
    "https-proxy-agent": "^5.0.0",
    "javascript-obfuscator": "^2.12.0",
    "jimp": "^0.16.1",
    "music-metadata": "^7.4.1",
    "npm": "^7.24.2",
    "pino": "^6.7.0",
    "pino-pretty": "^4.3.0",
    "protobufjs": "^6.10.1",
    "qrcode-terminal": "^0.12.0",
    "ws": "^7.3.1"
  },
  "devDependencies": {
    "@types/got": "^9.6.11",
    "@types/mocha": "^7.0.2",
    "@types/node": "^14.6.2",
    "@types/pino": "^6.3.2",
    "@types/ws": "^7.2.6",
    "dotenv": "^8.2.0",
    "mocha": "^8.1.3",
    "ts-node": "^9.1.1",
    "typedoc": "^0.20.0-beta.27",
    "typescript": "^4.0.0"
  }
...

**Comment by jchiavellibr** [comment]
not a bug. The "Whatsapp Beta" subscription causes the problem.

**Comment by jchiavellibr** [comment]
make sure your Whatsapp account is not subscribed to the Beta Version. This
is my problem.

Em seg., 7 de fev. de 2022 às 06:32, Manish ***@***.***>
escreveu:
