### ISSUE TITLE
[BUG] - MD - One connection lost breaks all connections running on same server

### ISSUE THREAD

**Issue by canove** [adiwajshing/Baileys#1098]
**Describe the bug**
I'm running around 10 connections, time to time I got a "Connection Closed" error from one of these connections, and right after that all my connections closes.

Why a connection lost affect all connections running on the same server? Maybe they are sharing the same websocket instance?

**Environment (please complete the following information):**
 - Is this on a server?: Yes
 - What do your `connectOptions` look like?: Like default.
 - Do you have multiple clients on the same IP?: Yes, but I'm using proxies. 
 - Are you using a proxy?: Yes, one for each connection.

**Additional context**
```
2021-12-29T06:19:21-03:00 INFO: XXXXXXXXXXX OPEN
2021-12-29T06:19:21-03:00 INFO: XXXXXXXXXXX OPEN
2021-12-29T06:19:21-03:00 INFO: XXXXXXXXXXX OPEN
2021-12-29T06:19:21-03:00 INFO: XXXXXXXXXXX OPEN
2021-12-29T06:19:21-03:00 INFO: XXXXXXXXXXX OPEN
2021-12-29T06:19:21-03:00 INFO: XXXXXXXXXXX OPEN
2021-12-29T06:19:22-03:00 INFO: XXXXXXXXXXX OPEN
2021-12-29T07:23:31-03:00 This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2021-12-29T07:23:31-03:00 Error: Connection Closed
2021-12-29T07:23:31-03:00     at sendRawMessage (/wpp-md-microservice/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:82:19)
2021-12-29T07:23:31-03:00     at sendNode (/wpp-md-microservice/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:90:16)
2021-12-29T07:23:31-03:00     at sendReceipt (/wpp-md-microservice/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-send.js:115:15)
2021-12-29T07:23:31-03:00     at sendDeliveryReceipt (/wpp-md-microservice/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-send.js:118:16)
2021-12-29T07:23:31-03:00     at WebSocket.<anonymous> (/wpp-md-microservice/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-recv.js:364:19)
2021-12-29T07:23:31-03:00 INFO: XXXXXXXXXXX CLOSE: Connection was lost
2021-12-29T07:23:31-03:00 INFO: XXXXXXXXXXX CLOSE: Connection was lost
2021-12-29T07:23:31-03:00 INFO: XXXXXXXXXXX CLOSE: Connection was lost
2021-12-29T07:23:31-03:00 INFO: XXXXXXXXXXX CLOSE: Connection was lost
2021-12-29T07:23:31-03:00 INFO: XXXXXXXXXXX CLOSE: Connection was lost
2021-12-29T07:23:31-03:00 INFO: XXXXXXXXXXX CLOSE: Connection was lost
2021-12-29T07:23:31-03:00 INFO: XXXXXXXXXXX CLOSE: Connection was lost
2021-12-29T07:23:34-03:00 INFO: RESTARTING
2021-12-29T07:23:34-03:00 INFO: RESTARTING
2021-12-29T07:23:34-03:00 INFO: RESTARTING
2021-12-29T07:23:34-03:00 INFO: RESTARTING
2021-12-29T07:23:34-03:00 INFO: RESTARTING
2021-12-29T07:23:34-03:00 INFO: RESTARTING
2021-12-29T07:23:34-03:00 INFO: RESTARTING

```

**Comment by mateuscdor** [comment]
> 

You have opened an issue that is not a bug.
the problem is not in your script and not in the library.

**Comment by canove** [comment]
Hi @mateuscdor. Thanks for replying. I'm not sure about that. 

The `Connection was lost` message comes from the `startKeepAliveRequest` function on `socket.js`. For some unknown reason, all sessions looses the connection at the same time, and there's nothing on my code that could cause this (as far as I know).

I opened this issue because maybe someone who also maintains multiple connections on the same server might be experiencing the same.

**Comment by HUGEIT** [comment]
to eliminate errors in your session management, you should try to have another session running in a second terminal instance on the same server and OS instance. if it still breaks, it's either a connectivity issue or something WA does.

after that you could try the same with a proxy on the second terminal instance. if that does not result in a close, you know it's WA doing something to all connections for a given IP

**Comment by canove** [comment]
Hi @HUGEIT , thanks for the tip, but I don't have many session and either a way to reproduce it on my development environment. It just occurs in "production". 

I have 2 servers running about 10 sessions, they have same configuration and use same outgoing IP. These sessions are distributed on the available servers after they come up, and each sessions uses a own proxy. Once started, one of the server (never both) starts getting this "Connection was lost" error.

Maybe there is some WS error that closes all existing connections or something.

I'm going to enable tracing to get more info.

**Comment by HUGEIT** [comment]
that does sound like an issue with your setup then. but the `connection was lost` only triggers on timeout so there must be something else going on where it messes it up on your server. is pino set to trace?

**Comment by mateuscdor** [comment]
Utilizo em média 50 a 75 conexões simultâneas 
Múltiplas sessões sendo separadas por classes.

Se uma sessão desconectar ou quebrar não interfere em nenhuma outra sessão.

O problema não é na lib, tem que ser testado direito em seu script para evitar socket.close.
