### ISSUE TITLE
[BUG] - MD - failure in decrypting "status@broadcast" messages results in memory leak

### ISSUE THREAD

**Issue by canove** [adiwajshing/Baileys#1119]
**Describe the bug**
One of my sessions get broken a few hours after reading QR code. When trying to restart it, I see a lot of "saving auth state" logs on console and memory blows up.

This session auth file has 110k lines (around 4MB). 

This is related to https://github.com/adiwajshing/Baileys/issues/985 and https://github.com/adiwajshing/Baileys/issues/1098. Both issues does only occur when this broken sessions is running on the same server.

**Environment (please complete the following information):**
I've tested it with the example.ts and only changed the "saving auth state" from pino to console.log.

**Additional context**

https://user-images.githubusercontent.com/24817866/147935354-705d77f2-fd5d-4a21-9000-a513261ab612.mp4

**Comment by canove** [comment]
Seems like it has something to do with retry receipt for "status@broadcast" messages. 

Right after connection, I got a lot of these: 
```
[1641402756252] ERROR: failure in decrypting message
    msgId: "3AAAB4D4C79B1E663252"
    trace: "Error: Received message with old counter: 3, 0\n    at GroupCipher.getSenderKey (/home/cassio/code_learn/whaticket-closed/wpp-md-microservice/node_modules/@adiwajshing/baileys-md/WASignalGroup/group_cipher.js:65:13)\n    at GroupCipher.decrypt (/home/cassio/code_learn/whaticket-closed/wpp-md-microservice/node_modules/@adiwajshing/baileys-md/WASignalGroup/group_cipher.js:45:28)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at Object.decodeMessageStanza (/home/cassio/code_learn/whaticket-closed/wpp-md-microservice/node_modules/@adiwajshing/baileys-md/lib/Utils/decode-wa-message.js:70:37)\n    at WebSocket.<anonymous> (/home/cassio/code_learn/whaticket-closed/wpp-md-microservice/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-recv.js:317:21)"
    data: "APgSCwb6CgkEJlKWCPsKOqq01MebHmYyUgX6/wZXMRV2kncDEqQd/wUWQTV3Vw38C0RpYW5hIFJhc2No+AL4BhY2MwRg/QABFDMSIQW1d3gyoelcJ6GORBVyKKXs6+/gEI9LULOFc7Qz2DrxChohBdhrMzdnqsgQ2Y+MYKFP7LuhR+Zq3Q3AJYBxJo9PuepwIsMBMwohBRooydDo83V3/mU9RaOgdYfQx/oi50OOzxiLd+MHufMOEAEYACKQAT+zZuxhlrCQhZH5P0ZgIS86mH3BcPsVt26Io+3LVQ0fTKrVGSMlds/5mypszJE/9+sDYDOfp8QvWkznMwTpp11TPiWoe0bNlzl6Y4AiyN+Y2vs+Z7C+Vtvr9Fkb3rt5G0WTNa9w1uoiihuEw2jCkfaZZduVZb11rxGFY1KCPI0NIf+HznXKEXnl/1JdjBBw5AMyhkNfrzmHKL+h5gcwAfgGFjYzBBf8izMI6Oz5yQIQABpA/SGd1R37DkdKvZiRN9DoTyJ1G3mD4j6W3N3lkdDdVmBb2QhB9HsIZlInj/jDBVcM3RvcQuNngHmUmUy0zX57n01Ts2XKGc65qjrsSvrtgVyiyQeRowsw6aXH6CAFuHpmXcqc++YM2hwLRay/5i8X6Yk2jPmApLNfiWbnF4Xsnws="
[1641402760073] INFO: sent retry receipt
    msgAttrs: {
      "from": "status@broadcast",
      "type": "text",
      "edit": "7",
      "id": "3AAAB4D4C79B1E663252",
      "participant": "XXXXXXX@s.whatsapp.net",
      "offline": "3",
      "t": "1641357757",
      "notify": "XXXXXX"
    }
    retryCount: 2
^C
```

I've added one line on `messages-recv.js` to ignore retries on status@broadcast messages and memory leak stopped.

```
 const sendRetryRequest = async (node) => {
        if (node.attrs.from === "status@broadcast") return;
```

**Comment by HUGEIT** [comment]
bumping this since I'm not sure if I had something similar going on but it's possible that I saw the same

**Comment by canove** [comment]
It seems to be related to the size of auth file. The one that causes this grows from 14k lines to 399k lines in a few days.

200k lines are related to "status@broadcast" keys. 

Is there a way to ignore status broadcast, since I don't really use it on my use case? If yes, ignoring it could cause some other problem?

**Comment by lu4t** [comment]
I am having same issue, or at the very least same symtomps, i.e. auth_multi.json going over 21MB (growing at a 1MB/hr rate).

**Comment by MacKey-255** [comment]
Same issue. Error:
```
Failed to decrypt message with any known session...
Session error:MessageCounterError: Key used already or never filled MessageCounterError: Key used already or never filled
    at SessionCipher.doDecryptWhisperMessage (/whatsapp/node_modules/libsignal/src/session_cipher.js:234:19)
    at SessionCipher.decryptWithSessions (/whatsapp/node_modules/libsignal/src/session_cipher.js:145:40)
    at Object.5355209409.0 [as awaitable] (/whatsapp/node_modules/libsignal/src/session_cipher.js:169:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _asyncQueueExecutor (/whatsapp/node_modules/libsignal/src/queue_job.js:20:29)
Session error:Error: Bad MAC Error: Bad MAC
    at Object.verifyMAC (/whatsapp/node_modules/libsignal/src/crypto.js:87:15)
    at SessionCipher.doDecryptWhisperMessage (/whatsapp/node_modules/libsignal/src/session_cipher.js:248:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SessionCipher.decryptWithSessions (/whatsapp/node_modules/libsignal/src/session_cipher.js:145:29)
    at async Object.5355209409.0 [as awaitable] (/whatsapp/node_modules/libsignal/src/session_cipher.js:169:28)
    at async _asyncQueueExecutor (/whatsapp/node_modules/libsignal/src/queue_job.js:20:29)
Session error:Error: Bad MAC Error: Bad MAC
    at Object.verifyMAC (/whatsapp/node_modules/libsignal/src/crypto.js:87:15)
    at SessionCipher.doDecryptWhisperMessage (/whatsapp/node_modules/libsignal/src/session_cipher.js:248:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SessionCipher.decryptWithSessions (/whatsapp/node_modules/libsignal/src/session_cipher.js:145:29)
    at async Object.5355209409.0 [as awaitable] (/whatsapp/node_modules/libsignal/src/session_cipher.js:169:28)
    at async _asyncQueueExecutor (/whatsapp/node_modules/libsignal/src/queue_job.js:20:29)
```
SAlu2s
