### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by doghi22** [adiwajshing/Baileys#1150]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**
Hello, im working for a solution to send mass messages throw whatsapp.
Sending to 1-30 ppl work fine.

When i have more than 50 numbers in my sent list, i get connection reset and sending stops, sometimes reset and start from scratch and resend to the same 50 numbers.

I have this in my stderr.log

(node:2751986) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 531)
(node:2751986) UnhandledPromiseRejectionWarning: Error: timed out
at WAConnection.rejectAllOnWSClose (/home/bentitec/nodevenv/mywebsiteurlhere/12/lib/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:79:62)
at WAConnection.emit (events.js:326:22)
at WAConnection.emit (/home/bentitec/nodevenv/mywebsiteurlhere/12/lib/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41)
at WAConnection.endConnection (/home/bentitec/nodevenv/mywebsiteurlhere/12/lib/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:417:14)
at Timeout.<anonymous> (/home/bentitec/nodevenv/mywebsiteurlhere/12/lib/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:79:113)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)

**Comment by Flam3rboy** [comment]
WhatsApp probably rate limits you and closes your connection. If you want to mass message many people you should probably use the WhatsApp Buisness api.
