### ISSUE TITLE
Can't Send files

### ISSUE THREAD

**Issue by rexdevin8** [adiwajshing/Baileys#1178]
conn.sendMessage(
                    id, 
                    { 
                        video: "./Doc/song.mp4", 
                        caption: "hello!",
                        gifPlayback: true
                    }

when use this I get this

throw new Constants_1.BaileysError(`Unexpected status in '${json[0] || 'query'}': ${http_1.STATUS_CODES[response.status]}(${response.status})`, { query: json, message, status: response.status });
                          ^

BaileysError: Unexpected status in 'action': Bad Request(400)
    at WAConnection.query (d:\Projects\rar-test\Wa\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:237:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WAConnection.relayWAMessage (d:\Projects\rar-test\Wa\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:316:13)
    at async WAConnection.sendMessage (d:\Projects\rar-test\Wa\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:25:9) {
  status: 400,
  context: {
    query: [
      'action',
      { epoch: '13', type: 'relay' },
      [
        [
          'message',
          null,
          WebMessageInfo {
            messageStubParameters: [],
            labels: [],
            key: [MessageKey],
            message: Message {},
            messageTimestamp: [Long],
            status: 1
          }
        ]
      ]
    ],
    message: 'Bad Request',
    status: 400
  }
}

**Comment by DiyRex** [comment]
same problem
