### ISSUE TITLE
Question regarding error handling

### ISSUE THREAD

**Issue by LinkTree3** [adiwajshing/Baileys#1192]
I keep getting these errors in my log informing me that the Baileys websocket disconnected.
Is there a way to suppress this error?

connection closed due to  Error: Stream Errored
    at WebSocket.<anonymous> (..\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:437:13)
    at WebSocket.emit (node:events:390:28)
    at ..\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:229:35
    at Object.decodeFrame (..\node_modules\@adiwajshing\baileys\lib\Utils\noise-handler.js:143:17)
    at WebSocket.onMessageRecieved (..\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:207:15)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (..\node_modules\ws\lib\websocket.js:1098:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (..\node_modules\@adiwajshing\baileys\node_modules\ws\lib\receiver.js:513:14)
    at Receiver.getData (..\node_modules\@adiwajshing\baileys\node_modules\ws\lib\receiver.js:446:17)
{
  data: { tag: 'stream:error', attrs: { code: '503' }, content: null },
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 503,
    payload: {
      statusCode: 503,
      error: 'Service Unavailable',
      message: 'Stream Errored'
    },
    headers: {}
  }
} , reconnecting  true

**Comment by LinkTree3** [comment]
Seems to error out on `End`

![image](https://user-images.githubusercontent.com/2587457/151467237-fb5f0912-f011-4523-8bce-cba86af2186a.png)

**Comment by LinkTree3** [comment]
Still looking for a solution for this. :(

**Comment by abhishek-eit** [comment]
I too have same issue

**Comment by maleeqB** [comment]
> I too have same issue. It works fine sometimes but most of the time this error occurs error: Error: Stream Errored at WebSocket. (/home/t9l_rishi/Desktop/Abhishek/projects/krishicress/17Jan2022/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:437:13) Any help would be appreciated

were you able to fix this?

**Comment by growupmarketingdigital** [comment]
same here... ANYONE, COULD YOU PLEASE SOLVE THIS??!!

**Comment by MuhammadRestu999** [comment]
Uh
no one knows
