### ISSUE TITLE
[BUG] BaileysError: Unexpected status in 'action': Payload Too Large(413)

### ISSUE THREAD

**Issue by Temuxuser2021** [adiwajshing/Baileys#1199]
/data/data/com.termux/files/home/janibot/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:230
            throw new Constants_1.BaileysError(`Unexpected status in '${json[0] || 'generic query'}': ${http_1.STATUS_CODES[response.status]}(${response.status})`, { query: json, message, status: response.status });
                  ^

BaileysError: Unexpected status in 'action': Payload Too Large(413)
    at WAConnection.query (/data/data/com.termux/files/home/janibot/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:230:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WAConnection.relayWAMessage (/data/data/com.termux/files/home/janibot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:260:13)
    at async WAConnection.sendMessage (/data/data/com.termux/files/home/janibot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:25:9) {
  status: 413,
  context: {
    query: [
      'action',
      { epoch: '463', type: 'relay' },
      [
        [
          'message',
          null,
          WebMessageInfo {
            messageStubParameters: [],
            labels: [],
            key: [MessageKey],
            message: [Message],
            messageTimestamp: [Long],
            status: 1,
            participant: '...............@s.whatsapp.net'
          }
        ]
      ]
    ],
    message: 'Payload Too Large',
    status: 413
  }

**Comment by Barqah-Xiex** [comment]
saya juga seperti itu, saya memakai UBUNTU
