### ISSUE TITLE
[BUG] TypeError: Cannot read property 'toString' of undefined - c.conversationTimestamp

### ISSUE THREAD

**Issue by sah-anshu** [adiwajshing/Baileys#1209]
**Describe the bug**
TypeError: Cannot read property 'toString' of undefined

**To Reproduce**
After First Run, It create problem and demands re-setup. 

anshu@ThinkPad:~/NewProjects/Baileys$ yarn example
yarn run v1.22.4
$ node --inspect -r ts-node/register Example/example.ts
Debugger listening on ws://127.0.0.1:9229/3a6e4fe4-c119-4c24-b97a-87eedf14c4ae
For help, see: https://nodejs.org/en/docs/inspector
/home/anshu/NewProjects/Baileys/src/Store/make-in-memory-store.ts:17
	key: (c: Chat) => (pin ? (c.pin ? '1' : '0') : '') + (c.archive ? '0' : '1') + c.conversationTimestamp.toString(16).padStart(8, '0') + c.id,
                                                                                                        ^
TypeError: Cannot read property 'toString' of undefined
    at Object.key (/home/anshu/NewProjects/Baileys/src/Store/make-in-memory-store.ts:17:105)
    at KeyedDB.firstIndex (/home/anshu/NewProjects/Baileys/node_modules/@adiwajshing/keyed-db/lib/KeyedDB.js:242:35)
    at KeyedDB._insertSingle (/home/anshu/NewProjects/Baileys/node_modules/@adiwajshing/keyed-db/lib/KeyedDB.js:197:32)
    at /home/anshu/NewProjects/Baileys/node_modules/@adiwajshing/keyed-db/lib/KeyedDB.js:52:18
    at Array.forEach (<anonymous>)
    at KeyedDB.upsert (/home/anshu/NewProjects/Baileys/node_modules/@adiwajshing/keyed-db/lib/KeyedDB.js:48:16)
    at fromJSON (/home/anshu/NewProjects/Baileys/src/Store/make-in-memory-store.ts:241:9)
    at Object.readFromFile (/home/anshu/NewProjects/Baileys/src/Store/make-in-memory-store.ts:371:5)
    at Object.<anonymous> (/home/anshu/NewProjects/Baileys/Example/example.ts:8:7)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
error Command failed with exit code 1.

**Comment by zennn08** [comment]
i found the same error

**Comment by zennn08** [comment]
this error occurs because c.conversationTimestamp is undefined

I added "?" on c.conversationTimestamp?.toString
and this error has been fixed

maybe it can help :\

**Comment by jackcokk** [comment]
> this error occurs because c.conversationTimestamp is undefined
> 
> I added "?" on c.conversationTimestamp?.toString and this error has been fixed
> 
> maybe it can help :\

You can also check this PR https://github.com/adiwajshing/Baileys/pull/1210 or make your own, it has not been merged yet
