### ISSUE TITLE
[Questions] Can't sendMessage, connection close

### ISSUE THREAD

**Issue by ade566** [adiwajshing/Baileys#1218]
Can't sendMessage, i following the docs [sendMessage](https://adiwajshing.github.io/Baileys/#non-media-messages), but the script running got error Connection Closed. How do i send a message?

**Console**
```python
Error: Connection Closed
    at sendRawMessage (D:\project\eksperimen\wa-baileys\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:63:19)
    at sendNode (D:\project\eksperimen\wa-baileys\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:71:16)
    at Object.presenceSubscribe (D:\project\eksperimen\wa-baileys\node_modules\@adiwajshing\baileys\lib\Socket\chats.js:352:43)
    at D:\project\eksperimen\wa-baileys\index.ts:35:14
    at step (D:\project\eksperimen\wa-baileys\index.ts:33:23)
    at Object.next (D:\project\eksperimen\wa-baileys\index.ts:14:53)
    at D:\project\eksperimen\wa-baileys\index.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\project\eksperimen\wa-baileys\index.ts:4:12)
    at sendMessageWTyping (D:\project\eksperimen\wa-baileys\index.ts:34:70) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}
```

**Script**
 ```python
import { Boom } from '@hapi/boom'
import P from 'pino'
import makeWASocket, { AnyMessageContent, delay, DisconnectReason, useSingleFileAuthState } from '@adiwajshing/baileys'

const startSock = async (id) => {
	console.log(`ObjectID: ${id}`);
	
	const { state, saveState } = useSingleFileAuthState(`./sessions/session-${id}.json`)
	const sock = makeWASocket({
		logger: P({ level: 'trace' }),
		printQRInTerminal: true,
		auth: state
	})

	sock.ev.on('connection.update', (update) => {
		const { connection, lastDisconnect } = update
		if(connection === 'close') {
      console.log(DisconnectReason.loggedOut);
      console.log(lastDisconnect);
      
			// reconnect if not logged out
			if((lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut) {
				startSock(id)
			} else {
				console.log('connection closed')
			}
		}
        
		console.log('connection update', update)
	})

	sock.ev.on('creds.update', saveState)

	const sentMsg  = await sock.sendMessage('[MY ID]@s.whatsapp.net', { text: 'kiddo' })
	return sock;
}
var idClient = ["wacs3"]
idClient.forEach(e => {
	startSock(e)
});
```

**Comment by HUGEIT** [comment]
you're sending a message before the connection is established

**Comment by cp-yago** [comment]
I have the same error, how do we know the connection is stable or not?
