### ISSUE TITLE
[BUG] Error after scanning qr the bot does not connect

### ISSUE THREAD

**Issue by Millena543** [adiwajshing/Baileys#1221]
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/storage/emulated/0/download/millady2/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/storage/emulated/0/download/millady2/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/storage/emulated/0/download/millady2/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:86:18)
    at WAConnection.emit (node:events:402:35)
    at WAConnection.emit (/storage/emulated/0/download/millady2/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v17.0.1

**Comment by AkirahX** [comment]
Code?

**Comment by Millena543** [comment]
> Código?

?

**Comment by zakirkun** [comment]
same error

**Comment by zakinshk** [comment]
@Millena543 @MaurilhoB @MaurilhoB @AZMCode

Criaram um grupo no whatsapp do Baileys Brazil
https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL

**Comment by AZMCode** [comment]
@zakinshk 
Cool cool, but I'm not really involved in the project anymore. 

Can't even speak Portuguese even...
Y'all got a group for Spanish speakers?

**Comment by AZMCode** [comment]
Also, that comment might be off-topic, might wanna contact the maintainer directly for that sorta stuff.

**Comment by Nanatturnip** [comment]
Leave from Multi-Device beta program on WhatsApp

**Comment by jasmanX** [comment]
i got same error also. please fix it. thanks

**Comment by andicc07** [comment]
ME TOO

**Comment by Hiiroshii** [comment]
Esse grupo ainda está funcionado??? @zakirkun
