### ISSUE TITLE
[ERROR] service-unavaible

### ISSUE THREAD

**Issue by Dakauann** [adiwajshing/Baileys#1231]
**Describe the bug**
thiss bug occurs when i made a request to send any message

**To Reproduce**
1. Created a new connection
2. try sending a message
3. get the error

**Environment (please complete the following information):**
 - Is this on a server? on a vps
 - What do your `connectOptions` look like? nothing changed
 - Do you have multiple clients on the same IP? theres some other connection in the same vps
 - Are you using a proxy? no

**Additional context**

complete log error: Error: service-unavailable
    at Object.assertNodeErrorFree (C:\Users\trash\Documents\trash-md\node_modules\@adiwajshing\baileys\lib\WABinary\index.js:290:15)
    at query (C:\Users\trash\Documents\trash-md\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:134:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getUSyncDevices (C:\Users\trash\Documents\trash-md\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:156:24)
    at async C:\Users\trash\Documents\trash-md\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:261:47
    at async Object.transaction (C:\Users\trash\Documents\trash-md\node_modules\@adiwajshing\baileys\lib\Utils\auth-utils.js:78:21)
    at async relayMessage (C:\Users\trash\Documents\trash-md\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:243:9)
    at async Object.sendMessage (C:\Users\trash\Documents\trash-md\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:395:17) {
  data: 503,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

**Comment by MarvynSTAR** [comment]
Same problem here!

**Comment by Botros-Fawzy** [comment]
Same problem here!

**Comment by Dakauann** [comment]
> Same problem here!

looks like whatsapp servers are partially down

**Comment by MarvynSTAR** [comment]
> > Same problem here!
> 
> looks like whatsapp servers are partially down

For me it’s all working now

**Comment by mateuscdor** [comment]
this is not a bug!

**Comment by Dakauann** [comment]
WhatsApp servers have already normalized!
