### ISSUE TITLE
[BUG] Apa Yang terjadi

### ISSUE THREAD

**Issue by Bintangp02** [adiwajshing/Baileys#1265]
/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290
throw new boom_1.Boom(errNode.attrs.text || 'Unknown error', { data: +errNode.attrs.code });
^
Error: bad-request
at Object.assertNodeErrorFree (/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290:15)
at query (/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:134:24)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async groupMetadata (/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:20:24)
at async /node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:250:41
at async Promise.all (index 0)
at async /node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:246:51
at async Object.transaction (/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:78:21)
at async relayMessage (/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:243:9) {
data: 400,
isBoom: true,
isServer: true,
output: {
statusCode: 500,
payload: {
statusCode: 500,
error: 'Internal Server Error',
message: 'An internal server error occurred'
},
headers: {}
}
}

**Comment by zakirkun** [comment]
Coba nanya pakai bahasa inggris bro,
