### ISSUE TITLE
Message "Restart Required" using MD

### ISSUE THREAD

**Issue by phenriquec** [adiwajshing/Baileys#1286]
Hello,

I'm starting using MD version, but after read the qrcode receive this message!!

Any solutions?

connection closed { isNewLogin: true, qr: undefined }
{"level":30,"time":1645785786967,"pid":1520,"hostname":"mynb","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"},"headers":{}}},"msg":"connection closed"}
+ connection closed {
  connection: 'close',
  lastDisconnect: {
    error: Error: Restart Required
        at WebSocket.<anonymous> (C:\vb\wabase-md\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:411:17) {
      data: null,
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2022-02-25T10:43:06.968Z
  }
}

my code to start MD instance

    const { version, isLatest } = await fetchLatestBaileysVersion()
    const sock = makeWASocket({ version, printQRInTerminal: true, auth: state })

**Comment by Bintangp02** [comment]
> Hello,
> 
> I'm starting using MD version, but after read the qrcode receive this message!!
> 
> Any solutions?
> 
> connection closed { isNewLogin: true, qr: undefined } {"level":30,"time":1645785786967,"pid":1520,"hostname":"mynb","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"},"headers":{}}},"msg":"connection closed"}
> 
> * connection closed {
>   connection: 'close',
>   lastDisconnect: {
>   error: Error: Restart Required
>   at WebSocket. (C:\vb\wabase-md\node_modules@adiwajshing\baileys\lib\Socket\socket.js:411:17) {
>   data: null,
>   isBoom: true,
>   isServer: false,
>   output: [Object]
>   },
>   date: 2022-02-25T10:43:06.968Z
>   }
>   }
> 
> my code to start MD instance
> 
> ```
> const { version, isLatest } = await fetchLatestBaileysVersion()
> const sock = makeWASocket({ version, printQRInTerminal: true, auth: state })
> ```

I also experienced the same thing :)
Saya juga mengalami hal serupa :)

**Comment by pedroayres** [comment]
Same here

**Comment by banyu-wigara** [comment]
> Hello,
> 
> I'm starting using MD version, but after read the qrcode receive this message!!
> 
> Any solutions?
> 
> connection closed { isNewLogin: true, qr: undefined } {"level":30,"time":1645785786967,"pid":1520,"hostname":"mynb","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"},"headers":{}}},"msg":"connection closed"}
> 
> * connection closed {
>   connection: 'close',
>   lastDisconnect: {
>   error: Error: Restart Required
>   at WebSocket. (C:\vb\wabase-md\node_modules@adiwajshing\baileys\lib\Socket\socket.js:411:17) {
>   data: null,
>   isBoom: true,
>   isServer: false,
>   output: [Object]
>   },
>   date: 2022-02-25T10:43:06.968Z
>   }
>   }
> 
> my code to start MD instance
> 
> ```
> const { version, isLatest } = await fetchLatestBaileysVersion()
> const sock = makeWASocket({ version, printQRInTerminal: true, auth: state })
> ```

It is nomal, you have to restart the socket with newly obtained credentials, like two step login.

**Comment by phenriquec** [comment]
@banyu-wigara  how to restart socket?

**Comment by banyu-wigara** [comment]
> @banyu-wigara how to restart socket?

Discard currently running socket, then create new instance, you can see that in readme's "Connecting" section

See this part

```
sock.ev.on('connection.update', (update) => {
    const { connection, lastDisconnect } = update
    if(connection === 'close') {
        const shouldReconnect = (lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
        console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
        // reconnect if not logged out
        if(shouldReconnect) {
            connectToWhatsApp()
        }
    } else if(connection === 'open') {
        console.log('opened connection')
    }
})
```

**Comment by pedroayres** [comment]
> > @banyu-wigara how to restart socket?
> 
> Discard currently running socket, then create new instance, you can see that in readme's "Connecting" section
> 
> See this part
> 
> ```
> sock.ev.on('connection.update', (update) => {
>     const { connection, lastDisconnect } = update
>     if(connection === 'close') {
>         const shouldReconnect = (lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
>         console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
>         // reconnect if not logged out
>         if(shouldReconnect) {
>             connectToWhatsApp()
>         }
>     } else if(connection === 'open') {
>         console.log('opened connection')
>     }
> })
> ```

Even with this code didn't work, I recommend trying to start a new session and scanning the Qrcode to see the problem.
WhatsApp made an update today =(

**Comment by banyu-wigara** [comment]
> > > @banyu-wigara how to restart socket?
> > 
> > 
> > Discard currently running socket, then create new instance, you can see that in readme's "Connecting" section
> > See this part
> > ```
> > sock.ev.on('connection.update', (update) => {
> >     const { connection, lastDisconnect } = update
> >     if(connection === 'close') {
> >         const shouldReconnect = (lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
> >         console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
> >         // reconnect if not logged out
> >         if(shouldReconnect) {
> >             connectToWhatsApp()
> >         }
> >     } else if(connection === 'open') {
> >         console.log('opened connection')
> >     }
> > })
> > ```
> 
> Even with this code didn't work, I recommend trying to start a new session and scanning the Qrcode to see the problem. WhatsApp made an update today =(

Yes, it's probably because the update.
I've just tried it a few minutes a go and its working fine, no update on my region as for now ....

**Comment by phenriquec** [comment]
> > > > @banyu-wigara how to restart socket?
> > > 
> > > 
> > > Discard currently running socket, then create new instance, you can see that in readme's "Connecting" section
> > > See this part
> > > ```
> > > sock.ev.on('connection.update', (update) => {
> > >     const { connection, lastDisconnect } = update
> > >     if(connection === 'close') {
> > >         const shouldReconnect = (lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
> > >         console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
> > >         // reconnect if not logged out
> > >         if(shouldReconnect) {
> > >             connectToWhatsApp()
> > >         }
> > >     } else if(connection === 'open') {
> > >         console.log('opened connection')
> > >     }
> > > })
> > > ```
> > 
> > 
> > Even with this code didn't work, I recommend trying to start a new session and scanning the Qrcode to see the problem. WhatsApp made an update today =(
> 
> Yes, it's probably because the update. I've just tried it a few minutes a go and its working fine, no update on my region as for now ....

Hi, don't function for me !!!

After scan qrcode the app show "Logging in..." for some seconds and after show me a error 

![image](https://user-images.githubusercontent.com/7809203/155774238-d329fe00-df54-42b0-81de-84e39a90ba31.png)

![image](https://user-images.githubusercontent.com/7809203/155774268-b731936f-b91c-46df-bd70-863c2da1518d.png)

**Comment by rubensmk** [comment]
@phenriquec Hi, can u share your solution? same problem here

**Comment by luizlago** [comment]
same problem here too

**Comment by diezeldev** [comment]
Hi @rubensmk @luizlago make sure to do the reconnect: https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts#:~:text=reconnect

**Comment by zakinshk** [comment]
@luizlago @rubensmk @phenriquec @pedroayres @pokearaujo 
fizeram um grupo do Baileys brazil
https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL

**Comment by waldemirflj** [comment]
> @luizlago @rubensmk @phenriquec @pedroayres @pokearaujo
> fizeram um grupo do Baileys brazil
> https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL

@luizlago consegue compartilhar novamente o link do grupo?

**Comment by lucasantoniooficial** [comment]
> > tente usar example.ts sem modificação
> 
> resolvi o problema!!
> 
> Eu estava configurando o socket null, antes de reconectá-los.
> 
> kkk galera!!

how did you solve? Can you share with the community?

**Comment by andreixhz** [comment]
you can share the solution? 
i have the same problem.

**Comment by jgalindosl** [comment]
I got it to work adding the following:  basically, passing the auth: state to the socket creation.

```
import makeWASocket, { DisconnectReason, BufferJSON, useSingleFileAuthState } from '@adiwajshing/baileys'

const { state, saveState } = await useSingleFileAuthState('auth_info_baileys')
const sock = makeWASocket({
        auth: state,
        printQRInTerminal: true
})
sock.ev.on ('creds.update', saveState)
 sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = (lastDisconnect?.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect?.error, ', reconnecting ', shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                connectToWhatsApp()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    })
```
