### ISSUE TITLE
 [BUG] error not known

### ISSUE THREAD

**Issue by Bintangp02** [adiwajshing/Baileys#1289]
[Session error:Error: Bad MAC Error: Bad MAC
at Object.verifyMAC (/node_modules/libsignal/src/crypto.js:87:15)
at SessionCipher.doDecryptWhisperMessage (/node_modules/libsignal/src/session_cipher.js:248:16)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async SessionCipher.decryptWithSessions (/node_modules/libsignal/src/session_cipher.js:145:29)
at async Object.6285171127920.0 [as awaitable] (/node_modules/libsignal/src/session_cipher.js:169:28)
at async _asyncQueueExecutor (/node_modules/libsignal/src/queue_job.js:20:29)
](https://github.com/adiwajshing)
```
**Ind
Bantu saya untuk mmenyelesaikan nya saya tidak tahu eror yang terjdi,trimakasih!!**


**Inglish
Help me to solve it I don't know the error that occurred, thank you!!**
```

**Comment by yoitscarolinee** [comment]
+1

**Comment by Hiarley** [comment]
+1

**Comment by jrCleber** [comment]
+1

**Comment by shinainaru** [comment]
+1

**Comment by Hiarley** [comment]
+1

**Comment by makanSukros** [comment]
+1

**Comment by NixSey** [comment]
+1

**Comment by makanSukros** [comment]
Problem still exist until now

Session error:Error: Bad MAC Error: Bad MAC
at Object.verifyMAC (/home/baileysmdbot/node_modules/libsignal/src/crypto.js:87:15)
at SessionCipher.doDecryptWhisperMessage (/home/baileysmdbot/node_modules/libsignal/src/session_cipher.js:250:16)
 at runMicrotasks (<anonymous>)
 at processTicksAndRejections (node:internal/process/task_queues:96:5)
 at async SessionCipher.decryptWithSessions (/home/baileysmdbot/node_modules/libsignal/src/session_cipher.js:147:29)
 at async Object.6285770812429:6.0 [as awaitable] (/home/baileysmdbot/node_modules/libsignal/src/session_cipher.js:171:28)
  at async _asyncQueueExecutor (/home/baileysmdbot/node_modules/libsignal/src/queue_job.js:20:29)
