### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by hasanbasri1993** [adiwajshing/Baileys#13]
i got error like this **SyntaxError: Unexpected token =**

Step:
1. npm install github:adiwajshing/Baileys
2. cope example 
3. run node example.js

/Users/hasanbasri1/Downloads/looptest/node_modules/Baileys/WhatsAppWeb.js:5
        static version = [0,4,1296] // the version of WhatsApp Web we're telling the servers we are
                       ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/hasanbasri1/Downloads/looptest/example.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by adiwajshing** [comment]
Can you check what version of node you're running, using ``` node --version ```?

**Comment by hasanbasri1993** [comment]
node -v
v10.16.3

**Comment by adiwajshing** [comment]
Ah, could you please update your node to the latest version? It’ll solve this issue

**Comment by hasanbasri1993** [comment]
thanks.. its work with the lastest but there problem again. getting error


hasans-imac:looptest hasanbasri1$ node example.js 
type exit to disconnect
connected to WhatsApp Web
resolving challenge
connected successfully
/Users/hasanbasri1/Downloads/looptest/node_modules/Baileys/WhatsAppWeb.Recv.js:261
        return Object.keys(message)[0]
                      ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at WhatsAppWeb.getMessageType (/Users/hasanbasri1/Downloads/looptest/node_modules/Baileys/WhatsAppWeb.Recv.js:261:23)
    at Object.client.handlers.onUnreadMessage (/Users/hasanbasri1/Downloads/looptest/example.js:34:32)
    at WhatsAppWeb.clearUnreadMessages (/Users/hasanbasri1/Downloads/looptest/node_modules/Baileys/WhatsAppWeb.Recv.js:233:31)
    at WhatsAppWeb.onMessageRecieved (/Users/hasanbasri1/Downloads/looptest/node_modules/Baileys/WhatsAppWeb.Recv.js:145:30)
    at WebSocket.<anonymous> (/Users/hasanbasri1/Downloads/looptest/node_modules/Baileys/WhatsAppWeb.Session.js:23:39)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (/Users/hasanbasri1/Downloads/looptest/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:310:20)
    at Receiver.dataMessage (/Users/hasanbasri1/Downloads/looptest/node_modules/ws/lib/receiver.js:427:14)
hasans-imac:looptest hasanbasri1$

**Comment by adiwajshing** [comment]
That's a bug. Will be fixed by EOD. You can work around it by adding the following snippet to the ``` client.onUnreadMessage ``` callback.

``` javascript
client.onUnreadMessage = (m) => {
    if (!m.message) {
        return
    }
    // rest of the function...
}
```

**Comment by adiwajshing** [comment]
These issues should be fixed in the latest beta release, please shift to that version!

**Comment by hasanbasri1993** [comment]
getting error again 



SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/hasanbasri1/Downloads/looptest/example.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
Hasans-iMac:looptest hasanbasri1$ node example.js 
/Users/hasanbasri1/Downloads/looptest/node_modules/Baileys/WhatsAppWeb.js:108
                type: ackTypes[json.ack-1] ?? "unknown (" + json.ack + ")"
                                            ^

**Comment by adiwajshing** [comment]
I think you have an older version of Node, it doesn't have the nullifying operator (```??```). However, I've updated the library to be compatible with older versions. Check it out.

**Comment by adiwajshing** [comment]
Seems okay now. Closing.

**Comment by gabrielayer** [comment]
delete baileys_store.json
