### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by moskoweb** [adiwajshing/Baileys#1306]
**Describe the bug**
The function of defining the group with the temp message setting does not terminate and break with timeout.

**To Reproduce**
```
await sock.groupToggleEphemeral(group_id, 7 * 24 * 60 * 60);
```
**Return**
```
Catch: Error: Timed Out
	at /my_folder/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:178:32 {
  data: {
	stack: 'Error\n' +
	  '    at Object.promiseTimeout (/my_folder/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:173:19)\n' +
	  '    at waitForMessage (/my_folder/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:107:42)\n' +
	  '    at query (/my_folder/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:130:22)\n' +
	  '    at groupQuery (/my_folder/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:10:55)\n' +
	  '    at Object.groupToggleEphemeral (/my_folder/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:107:19)\n' +
	  '    at groupSettingTemporary (/my_folder/src/controllers/groupsController.js:310:21)\n' +
	  '    at Layer.handle [as handle_request] (/my_folder/node_modules/express/lib/router/layer.js:95:5)\n' +
	  '    at next (/my_folder/node_modules/express/lib/router/route.js:137:13)\n' +
	  '    at verifyApiKey (/my_folder/src/middlewares.js:51:5)\n' +
	  '    at Layer.handle [as handle_request] (/my_folder/node_modules/express/lib/router/layer.js:95:5)'
  },
  isBoom: true,
  isServer: false,
  output: {
	statusCode: 408,
	payload: {
	  statusCode: 408,
	  error: 'Request Time-out',
	  message: 'Timed Out'
	},
	headers: {}
  }
}
```

**Comment by sudomaaz** [comment]
I am having exactly same issue @adiwajshing please check
