### ISSUE TITLE
[BUG] [MD] TypeError: Cannot read properties of undefined (reading 'me')

### ISSUE THREAD

**Issue by pushpa-raj-thazhathillada** [adiwajshing/Baileys#1313]
**Deployed on heroku and returned an error:**

------

/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:465
2022-03-03T14:35:58.862987+00:00 app[web.1]:             **return authState.creds.me;**
2022-03-03T14:35:58.862988+00:00 app[web.1]:     **^**
2022-03-03T14:35:58.862988+00:00 app[web.1]: 
2022-03-03T14:35:58.862988+00:00 app[web.1]: **TypeError: Cannot read properties of undefined (reading 'me')**
2022-03-03T14:35:58.862989+00:00 app[web.1]:     at Object.get user [as user] **(/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:465:36)**
2022-03-03T14:35:58.862990+00:00 app[web.1]:     at Object.makeGroupsSocket (/app/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:23:5)
2022-03-03T14:35:58.862990+00:00 app[web.1]:     at Object.makeMessagesSocket (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:15:27)
2022-03-03T14:35:58.862990+00:00 app[web.1]:     at Object.makeChatsSocket (/app/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:13:34)
2022-03-03T14:35:58.862991+00:00 app[web.1]:     at Object.makeMessagesRecvSocket (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:26:26)
2022-03-03T14:35:58.862997+00:00 app[web.1]:     at makeWASocket (/app/node_modules/@adiwajshing/baileys/lib/Socket/index.js:6:51)
2022-03-03T14:35:58.862997+00:00 app[web.1]:     at connect (/app/index.js:31:14)
2022-03-03T14:35:58.862998+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-03T14:35:58.999244+00:00

------

**I AM USING THE LATEST VERSION ( ^4.0.0 )**

**THE LINE WHICH GOT ERROR IS [`THIS`](https://github.com/adiwajshing/Baileys/blob/de7d1002a915475d7c5d9591ea232b6abea531b3/src/Socket/socket.ts#L547)**

**Comment by Error-Unknown-git** [comment]
@adiwajshing @barkerpedro @galiazzi @edgardmessias @Diden05

**Comment by pushpa-raj-thazhathillada** [comment]
No response -_-

**Comment by PurpShell** [comment]
I am having this issue too of lately

**Comment by PurpShell** [comment]
re-open

**Comment by rhutikcodes** [comment]
+1

**Comment by moskoweb** [comment]
+1

**Comment by SarkonTampan** [comment]
how to fix it?
