### ISSUE TITLE
cant scan qr while using md [BUG]

### ISSUE THREAD

**Issue by devil-slayer141** [adiwajshing/Baileys#1369]
(node:11312) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:86:18)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41)
    at WAConnection.connect (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 55)
(node:11312) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:87:18)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41)
    at WAConnection.connect (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 56)
(node:11312) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:88:18)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41)
    at WAConnection.connect (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 57)
(node:11312) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:89:18)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41)
    at WAConnection.connect (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 58)
(node:11312) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:90:18)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41)
    at WAConnection.connect (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 59)
(node:11312) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:91:18)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41)
    at WAConnection.connect (F:\DTS-EDDIE\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 60)

**Comment by FaizBastomi** [comment]
you are using baileys v3 while that version does not support Multi Device, please update your baileys to version 4.0.1 and don't forget to read the README for reference on how to migrate from v3 to v4.
please close this issue immediately

**Comment by devil-slayer141** [comment]
> you are using baileys v3 while that version does not support Multi Device, please update your baileys to version 4.0.1 and don't forget to read the README for reference on how to migrate from v3 to v4. please close this issue immediately

It is v4.0.1 but still cant scan qr..

**Comment by FaizBastomi** [comment]
> It is v4.0.1 but still cant scan qr..

are you sure it's version 4.0.1?  From the baileys lib file structure listed in the log like version 3.5.3, try checking the version again by going to the lib folder and looking at the contents in package.json

**Comment by SheIITear** [comment]
It doesn't work because you aren't even using the md version of baileys. 

If you'd actually do what the issue template says. Instead of just slapping the whole terminal output into an issue without any code or anything, you'd find many, _many_, issues about the same thing.
