### ISSUE TITLE
duplicate key error in conn.groupCreate

### ISSUE THREAD

**Issue by anupamsinghal** [adiwajshing/Baileys#138]
Happens a lot of the time, but not every single time:

```
(node:49384) UnhandledPromiseRejectionWarning: Error: duplicate key: -15866, of inserting: 17195-159996@g.us, present: 17195-159996@g.us
    at KeyedDB.insert (/Users/Baileys/node_modules/@adiwajshing/keyed-db/lib/KeyedDB.js:28:23)
    at WAConnection.chatAdd (/Users/Baileys/src/WAConnection/4.Events.ts:172:20)
    at WAConnection.groupCreate (/Users/Baileys/src/WAConnection/8.Groups.ts:51:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:49384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:49384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by adiwajshing** [comment]
Could you try updating to the latest version, 3.0.0 and see if the issue persists?

**Comment by anupamsinghal** [comment]
@adiwajshing I have the latest code from today already.

**Comment by adiwajshing** [comment]
@anupamsinghal I've made a new commit -- could you please check that its working correctly & solves your problem?

**Comment by anupamsinghal** [comment]
Seems to be working so far. Thanks for the quick response, @adiwajshing!

**Comment by adiwajshing** [comment]
Happy to help
