### ISSUE TITLE
Connection Closed!

### ISSUE THREAD

**Issue by sreza78** [adiwajshing/Baileys#1386]
**When i try to login into new session or load a session with token, sometimes the baileys not connecting to whatsapp**
i try more and more and at last it connects

```
POST /add 200 210.045 ms - 77
{"level":30,"time":1647784237257,"pid":7645,"hostname":"host","class":"baileys","error":{},"msg":"connection closed"}
{"level":30,"time":1647784237258,"pid":7645,"hostname":"host","class":"baileys","error":{},"msg":"closed connection to WhatsApp"}
POST /add 200 133.938 ms - 77
{"level":30,"time":1647784244646,"pid":7645,"hostname":"host","class":"baileys","error":{},"msg":"connection closed"}
{"level":30,"time":1647784244646,"pid":7645,"hostname":"host","class":"baileys","error":{},"msg":"closed connection to WhatsApp"}
POST /add 200 121.266 ms - 77
{"level":30,"time":1647784255386,"pid":7645,"hostname":"host","class":"baileys","error":{},"msg":"connection closed"}
{"level":30,"time":1647784255386,"pid":7645,"hostname":"host","class":"baileys","error":{},"msg":"closed connection to WhatsApp"}
POST /add 200 160.282 ms - 77
{"level":30,"time":1647784260060,"pid":7645,"hostname":"host","class":"baileys","msg":"Opened WS connection to WhatsApp Web"}
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀▄ ▀  ▀  ▄██ ▄▀▄▄▄   ▄ ▀▀▀█▀▄█ ▄▄▄▄▄ █
█ █   █ █▄▄▀▄▄▄█  ▄█ ▀▀ ▄██ █▄▄▄████ ▀█ █   █ █
█ █▄▄▄█ █   ▀▀▄ ▄▀██▀ ▄▄▄  ▄██▄▄ ▄ ▄▄▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ █ ▀▄█ ▀▄█▄█ █▄█ ▀ █ ▀▄█ ▀ ▀ █▄▄▄▄▄▄▄█
█▄ ▀ ▀▀▄▄▀▀ ██▄██▄▄ ▀  ▄▄ █▄▄ █▄▄███▄█▀▄  █ ▄▀█
█ ▄  █▀▄▄██▄█▄█▄█ ▀▀█ ▄▄█▄▀█▄█ ▄▄ ▄▄█ ▀▀▄█▄▄▄ █
██  ▀█ ▄▄▄▀▄▄▀▄ ▀▀  █ ▄▄█ ▄█▄▄▄█  ▄  ██▄▄  █▀▀█
██▄█   ▄▀▄ █ ▄▄█▀▄▄ █▄█▄▄▄ ▄█   ▄ █▄▀ █▄▀▄█▄█▀█
█▀█ ▀ ▄▄▄ ▀▀▄▀▀▄█▄  █▀▀█▀▀  ▄█▀▄▀ ▄█▀█▄▀ ▀  ▀ █
█▀▀ █▄█▄ ▀▄▀▄▄    ▄▄▀▄▄ █  █▄▄ ▀▄█▄█▀ █▀█▄ ▄▄▄█
█▀█▄▄ ▄▄▄ ▄▄▀▀█▀▄▄▀ ▄ ▄▄▄  ▄▄▄█▄▄██▄█ ▄▄▄  █▀▀█
█▀█▀  █▄█   ▀ █▄▀█▀██ █▄█ ▀▀█ ▀█▀▄▀██ █▄█  ▄▀▄█
█▄ ██▄▄▄▄ █▀ ▄▄▄█▀ ▄▀   ▄▄▀▄  ██ ▄▄▀    ▄ ▄ ▄▄█
█ ▄▀▀▀▀▄█▀█▄▀▄ ███▀▄▀▀▀ ▄█▀▄▄   ▀   ██ █▄█▄▄▄██
█▀ ▄▀▄▄▄▄██▄▄█▀  ▄ ▄▄ ▄▀▀▄▄▀ ▀▀█▀ ██▀▄▀█▄██▄▄▄█
█ ▀▄ ▀▄▄▀█ █▀ ▀▄ ▄█▀▀█▄▄█▄ █▄█  █▀ █▀ ▄ ▄█▄█▄ █
██▄█ ██▄▄▄█ ▄ █▀ ██▄▀ ▄ █▀▄▄▀ ▄▄ █ ▄▄▀██▄█ ▀▄▀█
██▀▀▀ █▄    ▀▀ ▀ ▄▀▄ ▀▄▀ ▄  ▀█▀█▄  ▄▀ ▄▄▄█▀▄  █
█▄██▄▄█▄▄▀ ▄▄█▄ ▄▀▄▄▀ ▄▄▄  ▄ ▄▄▄▄ █▀█ ▄▄▄  ████
█ ▄▄▄▄▄ █▄ ▄▀ ▄▄ ▄ █▄ █▄█ ▀▀█ ▄ ▄▀▄██ █▄█ █▄▄██
█ █   █ █▀ ▄█▄▄▄█▄ ▄ ▄▄▄▄ █▀ ▀▀█ ▄█▄  ▄▄  █▄█ █
█ █▄▄▄█ █▀  ▄  █▀▀▄  ▄▀ ▀ ▀ ▀▄▄█     ▄ █ ▄█████
█▄▄▄▄▄▄▄█▄▄▄█▄▄██▄█▄▄██▄▄▄█▄▄▄▄███▄▄▄▄██▄█▄▄▄██
```
## My Code
```js
const client = makeWALegacySocket({
    connectTimeoutMs: 60000,
    keepAliveIntervalMs: 20000
});
client.ev.on("connection.update", x =>{
    if(x.connection == "close") return reject();
    if(x.qr){
        qrcode.toDataURL(x.qr, { scale: 8 }).then(raw =>{
            raw.replace(/^data:image\/png;base64,/, "")
            console.log(raw);
        })
    }
})
client.ev.on('creds.update', (auth) =>{
    client.ws.close();
    return resolve(auth)
})
```

**Comment by mrjoebudi** [comment]
same here, after 5 seconds QRCode Scan, Apear message UNAuthorize .......scan again....and so on, any solutions?

**Comment by MacKey-255** [comment]
Try it:
```
// Get session file
const session_file = path.join(this.SESSIONS_DIR, this.bot_name + '.json');
const { state, saveState } = useSingleFileAuthState(session_file);
const { version, isLatest } = await fetchLatestBaileysVersion();

// Create Client
this.client = await makeWASocket({
    version,
    printQRInTerminal: false,
    auth: state,
    connectTimeoutMs: this.CONNECTION_TIMEOUT,
    defaultQueryTimeoutMs: this.CONNECTION_TIMEOUT,
    keepAliveIntervalMs: this.CONNECTION_TIMEOUT,
});

// Event Connection State
this.client.ev.on('connection.update', async update => {
    const { connection, lastDisconnect, qr } = update;
    if (qr) {
        // Send QR Code to Server
        await this._qr_code(qr);
    } else if (connection === 'close') {
        // reconnect if not logged out
        const statusCode = lastDisconnect.error ? lastDisconnect.error?.output?.statusCode : 0;
        if (statusCode === DisconnectReason.badSession) {
            this.log(`Bad session file, delete and run again`);
            this.remove_session();  // Delete session file
        } else if (statusCode === DisconnectReason.connectionClosed) {
            this.log('Connection closed, reconnecting....');
        } else if (statusCode === DisconnectReason.connectionLost) {
            this.log('Connection lost, reconnecting....');
        } else if (statusCode === DisconnectReason.connectionReplaced) {
            this.log('Connection Replaced, Another New Session Opened, Please Close Current Session First');
        } else if (statusCode === DisconnectReason.loggedOut) {
            this.log(`Device Logged Out, Deleting Session.`);
            this.remove_session();  // Delete session file
        } else if (statusCode === DisconnectReason.restartRequired) {
            this.log('Restart required, restarting...');
        } else if (statusCode === DisconnectReason.timedOut) {
            this.log('Connection timedOut, reconnecting...');
        } else {
            this.log(lastDisconnect.error);
        }
        // Restart bot (You can call the start bot function)
        this.destroy(false);
    } else if (connection === 'open') {
        // Wait 5 seg for linked qr process to whatsapp
        await delay(this.SLEEP_TIME);
        // Bot is Ready (I execute my code when bot is ready)
        await this._ready();
        this.log(`Started using WA v${version.join('.')}, isLatest: ${isLatest}`);
    }
});

// listen for when the auth credentials is updated
this.client.ev.on('creds.update', saveState);
```
SAlu2s

**Comment by sreza78** [comment]
> @sreza78 Try it:

**It gives me this error**

```
var statusCode = con.lastDisconnect.error ? (_con$lastDisconnect$e = con.lastDisconnect.error) === null || _con$lastDisconnect$e === void 0 ? void 0 : (_con$lastDisconnect$e2 = _con$lastDisconnect$e.output) === null || _con$lastDisconnect$e2 === void 0 ? void 0 : _con$lastDisconnect$e2.statusCode : 0;
                                          ^

TypeError: Cannot read property 'error' of undefined
```

**Comment by MaznAbdullah** [comment]
> > @sreza78 Try it:
> 
> **It gives me this error**
> 
> ```
> var statusCode = con.lastDisconnect.error ? (_con$lastDisconnect$e = con.lastDisconnect.error) === null || _con$lastDisconnect$e === void 0 ? void 0 : (_con$lastDisconnect$e2 = _con$lastDisconnect$e.output) === null || _con$lastDisconnect$e2 === void 0 ? void 0 : _con$lastDisconnect$e2.statusCode : 0;
>                                           ^
> 
> TypeError: Cannot read property 'error' of undefined
> ```

const statusCode = (lastDisconnect.error as Boom)?.output?.statusCode;

**Comment by sahilhilki** [comment]
> When i log **lastDisconectReason** gives me
> 
> ```
> {
>   error: Error: Unexpected server response: 400
>       at ClientRequest.<anonymous> (/~/node_modules/ws/lib/websocket.js:852:7)
>       at ClientRequest.emit (events.js:400:28)
>       at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
>       at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
>       at TLSSocket.socketOnData (_http_client.js:515:22)
>       at TLSSocket.emit (events.js:400:28)
>       at addChunk (internal/streams/readable.js:290:12)
>       at readableAddChunk (internal/streams/readable.js:265:9)
>       at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
>       at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23),
>   date: 2022-03-21T12:05:13.285Z
> }
> ```

Facing same issue when try connecting using stored session (legacy API)

**Comment by sreza78** [comment]
> const statusCode = (lastDisconnect.error as Boom)?.output?.statusCode;

sorry but i use js not ts

**Comment by sreza78** [comment]
I fix my problem by call the function again as [sample](https://github.com/adiwajshing/Baileys/blob/master/Example/example-legacy.ts#L66)

but problem already exists, it's not connecting sometimes and connecting sometimes

**Comment by pedropalhari** [comment]
For me the behavior is pretty consistent. If I scan the QRCode immediately (within 5 to 10 seconds of it being generated) it always fails.

If I wait for a little bit and then scan it, it goes without an issue.

**Comment by sreza78** [comment]
any updates?

**Comment by shingie3500** [comment]
//This solved it for me --> type: any
 const { connection, lastDisconnect, qr }: any = update;
