### ISSUE TITLE
[BUG] error on qrcode scan

### ISSUE THREAD

**Issue by jazz7381** [adiwajshing/Baileys#1402]
**Describe the bug**
when i start fresh install of baileys from and npm and using example: 
https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts
it keep show me error, and qrcode re appear.

**To Reproduce**
1. run baileys
2. scan qrcode

**Expected behavior**
Qrcode scan completed and authenticated.

**Environment (please complete the following information):**
 - Is this on a server? no
 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? no

**Additional context**
this the error log:
```
{"level":10,"time":1648015239596,"pid":10166,"hostname":"MSI","fromMe":false,"frame":{"tag":"ib","attrs":{"from":"@s.whatsapp.net"},"content":[{"tag":"downgrade_webclient","attrs":{},"content":null}]},"msg":"communication"}
{"level":30,"time":1648015239596,"pid":10166,"hostname":"MSI","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":411,"payload":{"statusCode":411,"error":"Length Required","message":"Multi-device beta not joined"},"headers":{}}},"msg":"connection closed"}
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Multi-device beta not joined
        at WebSocket.<anonymous> (/mnt/c/laragon/www/apg/wa-bot/wabot2/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:454:13)
        at WebSocket.emit (node:events:526:28)
        at /mnt/c/laragon/www/apg/wa-bot/wabot2/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:236:35
        at Object.decodeFrame (/mnt/c/laragon/www/apg/wa-bot/wabot2/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:143:17)
        at WebSocket.onMessageRecieved (/mnt/c/laragon/www/apg/wa-bot/wabot2/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:215:15)
        at WebSocket.emit (node:events:526:28)
        at Receiver.receiverOnMessage (/mnt/c/laragon/www/apg/wa-bot/wabot2/node_modules/ws/lib/websocket.js:1137:20)
        at Receiver.emit (node:events:526:28)
        at Receiver.dataMessage (/mnt/c/laragon/www/apg/wa-bot/wabot2/node_modules/ws/lib/receiver.js:513:14)
        at Receiver.getData (/mnt/c/laragon/www/apg/wa-bot/wabot2/node_modules/ws/lib/receiver.js:446:17) {
      data: null,
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2022-03-23T06:00:39.597Z
  }
}
using WA v2.2208.14, isLatest: true
connection update {
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
}
{"level":30,"time":1648015241110,"pid":10166,"hostname":"MSI","browser":["Baileys","Chrome","4.0.0"],"msg":"connected to WA Web"}
{"level":20,"time":1648015241530,"pid":10166,"hostname":"MSI","msg":"handshake recv from WA Web"}
{"level":30,"time":1648015241533,"pid":10166,"hostname":"MSI","msg":"handshake complete"}
{"level":30,"time":1648015241533,"pid":10166,"hostname":"MSI","msg":"not logged in, attempting registration..."}
```

**Comment by BochilGaming** [comment]
"Error: Multi-device beta not joined", join multi-device first!

**Comment by jazz7381** [comment]
[BochilGaming](https://github.com/BochilGaming) why i need to use multidevice? i use master branch, did join to multidevice beta is a must?

**Comment by FaizBastomi** [comment]
@jazz7381 you must join the multi-device beta to use the master branch
