### ISSUE TITLE
Not upload files

### ISSUE THREAD

**Issue by paulocorcino** [adiwajshing/Baileys#1405]
I'm trying upload image, but during process return a error.

```
// this is a  sample the of code
await WA_CLIENT.CONNECTION.sendMessage('557XXXXXXX@s.whatsapp.net', {
  "image": {
    "url": "/Users/paulocorcino/somoschat/wapi/baileys/tmp/6049bc47db10_master8992unnamed.jpg"
  },
  "mimetype": "image/jpeg"
}, {
  mimetype: 'image/jpeg',
  caption: '',
  filename: '6049bc47db10_master8992unnamed.jpg'
});

//return error
{"level":20,"time":1648030164875,"pid":29015,"hostname":"Paulos-MacBook-Pro.local","msg":"uploading to \"media.fssa21-1.fna.whatsapp.net\""}
{"level":40,"time":1648030164876,"pid":29015,"hostname":"Paulos-MacBook-Pro.local","trace":"TypeError [ERR_INVALID_ARG_TYPE]: The \"options.agent\" property must be one of Agent-like Object, undefined, or false. Received type string ('Mozilla/5.0 (Macintosh; ...)\n    at new NodeError (node:internal/errors:371:5)\n    at new ClientRequest (node:_http_client:140:11)\n    at Object.request (node:https:353:10)\n    at RedirectableRequest._performRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/follow-redirects/index.js:279:24)\n    at new RedirectableRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/follow-redirects/index.js:61:8)\n    at Object.request (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/follow-redirects/index.js:487:14)\n    at dispatchHttpRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/axios/lib/adapters/http.js:226:25)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/axios/lib/adapters/http.js:48:10)\n    at dispatchRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/axios/lib/core/dispatchRequest.js:58:10)","msg":"Error in uploading to media.fssa21-1.fna.whatsapp.net , retrying..."}
{"level":20,"time":1648030164878,"pid":29015,"hostname":"Paulos-MacBook-Pro.local","msg":"uploading to \"media-for1-1.cdn.whatsapp.net\""}
{"level":40,"time":1648030164879,"pid":29015,"hostname":"Paulos-MacBook-Pro.local","trace":"TypeError [ERR_INVALID_ARG_TYPE]: The \"options.agent\" property must be one of Agent-like Object, undefined, or false. Received type string ('Mozilla/5.0 (Macintosh; ...)\n    at new NodeError (node:internal/errors:371:5)\n    at new ClientRequest (node:_http_client:140:11)\n    at Object.request (node:https:353:10)\n    at RedirectableRequest._performRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/follow-redirects/index.js:279:24)\n    at new RedirectableRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/follow-redirects/index.js:61:8)\n    at Object.request (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/follow-redirects/index.js:487:14)\n    at dispatchHttpRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/axios/lib/adapters/http.js:226:25)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/axios/lib/adapters/http.js:48:10)\n    at dispatchRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/axios/lib/core/dispatchRequest.js:58:10)","msg":"Error in uploading to media-for1-1.cdn.whatsapp.net , retrying..."}
{"level":20,"time":1648030164880,"pid":29015,"hostname":"Paulos-MacBook-Pro.local","msg":"uploading to \"media.fssa21-1.fna.whatsapp.net\""}
{"level":40,"time":1648030164882,"pid":29015,"hostname":"Paulos-MacBook-Pro.local","trace":"TypeError [ERR_INVALID_ARG_TYPE]: The \"options.agent\" property must be one of Agent-like Object, undefined, or false. Received type string ('Mozilla/5.0 (Macintosh; ...)\n    at new NodeError (node:internal/errors:371:5)\n    at new ClientRequest (node:_http_client:140:11)\n    at Object.request (node:https:353:10)\n    at RedirectableRequest._performRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/follow-redirects/index.js:279:24)\n    at new RedirectableRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/follow-redirects/index.js:61:8)\n    at Object.request (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/follow-redirects/index.js:487:14)\n    at dispatchHttpRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/axios/lib/adapters/http.js:226:25)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/axios/lib/adapters/http.js:48:10)\n    at dispatchRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/axios/lib/core/dispatchRequest.js:58:10)","msg":"Error in uploading to media.fssa21-1.fna.whatsapp.net , retrying..."}
{"level":20,"time":1648030164886,"pid":29015,"hostname":"Paulos-MacBook-Pro.local","msg":"uploading to \"mmg.whatsapp.net\""}
{"level":40,"time":1648030164887,"pid":29015,"hostname":"Paulos-MacBook-Pro.local","trace":"TypeError [ERR_INVALID_ARG_TYPE]: The \"options.agent\" property must be one of Agent-like Object, undefined, or false. Received type string ('Mozilla/5.0 (Macintosh; ...)\n    at new NodeError (node:internal/errors:371:5)\n    at new ClientRequest (node:_http_client:140:11)\n    at Object.request (node:https:353:10)\n    at RedirectableRequest._performRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/follow-redirects/index.js:279:24)\n    at new RedirectableRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/follow-redirects/index.js:61:8)\n    at Object.request (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/follow-redirects/index.js:487:14)\n    at dispatchHttpRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/axios/lib/adapters/http.js:226:25)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/axios/lib/adapters/http.js:48:10)\n    at dispatchRequest (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/axios/lib/core/dispatchRequest.js:58:10)","msg":"Error in uploading to mmg.whatsapp.net "}
Error: Media upload failed on all hosts
    at Object.upload (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:504:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/paulocorcino/somoschat/wapi/baileys/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:78:28
    at async Promise.all (index 0)
    at async Object.prepareWAMessageMedia (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:76:40)
    at async Object.generateWAMessageContent (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:223:13)
    at async Object.generateWAMessage (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:345:54)
    at async Object.sendMessage (/Users/paulocorcino/somoschat/wapi/baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:380:33)
    at async getId (/Users/paulocorcino/somoschat/wapi/baileys/controllers/api.js:738:18) {
  data: null,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}
```

**Comment by Kikii-XyZ** [comment]
> 

maybe you can use this:
```
conn.sendMessage(jid, { image: image, caption: caption, mimetype: 'image/jpeg', thumbail: null }, { quoted: m})
```

**Comment by paulocorcino** [comment]
Thank you @Kikii-XyZ! I did it upload file, so the problems is on config attribute 'fetchAgent', when set a browser agent info the Axios not accept this information, it waits a 'Agent-like Object' not one string. Why? I don't know. I will open a bug post.
