### ISSUE TITLE
Unexpected status in 'admin'

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#142]
This strange error has appear in some connections of mine
```BaileysError: Unexpected status in 'admin': Unauthorized(401)
   at WAConnection.query (WAConnection/0.Base.js:240:19)
   at processTicksAndRejections (internal/process/task_queues.js:97:5)
   at async WAConnection/1.Validation.js:64:32
   at async Promise.all (index 1)
   at async WAConnection.authenticate (WAConnection/1.Validation.js:73:33)
   at async Promise.all (index 0)
   at async WAConnection.connectInternal (WAConnection/3.Connect.js:122:27)
   at async WAConnection.connect (WAConnection/3.Connect.js:49:27)
   at async Object.load (sulla.js:43:3) {
 status: 401,
 context: {
   query: [
     'admin',
     'login',
     'OMMITED',
     'OMMITED',
     'OMMITED',
     'takeover'
   ],
   message: 'Unauthorized',
   status: 401
 }```

**Comment by adiwajshing** [comment]
Yes, that's when you've logged out from your phone -- not an unexpected error.

**Comment by algoz098** [comment]
This is happening even without logging out of the phone, seems to be outside of it, like whatsapp server unauthentincating the aplication

**Comment by adiwajshing** [comment]
Are you calling logout() somewhere in your code?

**Comment by algoz098** [comment]
Yes, i have to clear the connection to reconnect. Would that remove the auth ? In that case we have something to reload the connection without creating a new object?

**Comment by adiwajshing** [comment]
You have to call `conn.close()` -- that terminates the connection. `conn.logout()` will unpair your phone.

**Comment by algoz098** [comment]
Ok, i have made the change.
