### ISSUE TITLE
chat.messages is not iterable

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#143]
here another strange error
```TypeError: chat.messages is not iterable
   at WAConnection.chatUpdatedMessage (/WAConnection/4.Events.js:284:30)
   at WAConnection.forwardStatusUpdate (/WAConnection/4.Events.js:188:14)
   at func (/WAConnection/4.Events.js:161:18)
   at WAConnection.onMessageRecieved (/WAConnection/3.Connect.js:289:21)
   at WebSocket.<anonymous> (/WAConnection/3.Connect.js:91:70)
   at WebSocket.emit (events.js:315:20)
   at Receiver.receiverOnMessage (/node_modules/ws/lib/websocket.js:801:20)
   at Receiver.emit (events.js:315:20)
   at Receiver.dataMessage (/node_modules/ws/lib/receiver.js:436:14)
   at Receiver.getData (/node_modules/ws/lib/receiver.js:366:17)```

**Comment by adiwajshing** [comment]
I can't see the error, can you please attach it?

**Comment by algoz098** [comment]
```TypeError: chat.messages is not iterable
    at WAConnection.chatUpdatedMessage (/var/sulla-slave/conn/WAConnection/4.Events.js:290:30)
    at WAConnection.forwardStatusUpdate (/var/sulla-slave/conn/WAConnection/4.Events.js:177:14)
    at func (/var/sulla-slave/conn/WAConnection/4.Events.js:161:18)
    at WAConnection.onMessageRecieved (/var/sulla-slave/conn/WAConnection/3.Connect.js:322:21)
    at WebSocket.<anonymous> (/var/sulla-slave/conn/WAConnection/3.Connect.js:95:54)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/var/sulla-slave/node_modules/ws/lib/websocket.js:801:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/var/sulla-slave/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/var/sulla-slave/node_modules/ws/lib/receiver.js:366:17)```
