### ISSUE TITLE
[BUG] Error: Stream Errored

### ISSUE THREAD

**Issue by nyzfunbotz** [adiwajshing/Baileys#1435]
connection closed due to  Error: Stream Errored
    at WebSocket.<anonymous> (/data/data/com.termux/files/home/BOT/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:437:13)
    at WebSocket.emit (node:events:527:28)
    at /data/data/com.termux/files/home/BOT/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:229:35
    at Object.decodeFrame (/data/data/com.termux/files/home/BOT/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:143:17)
    at WebSocket.onMessageRecieved (/data/data/com.termux/files/home/BOT/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:207:15)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/data/data/com.termux/files/home/BOT/node_modules/ws/lib/websocket.js:1137:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (/data/data/com.termux/files/home/BOT/node_modules/ws/lib/receiver.js:513:14)
    at Receiver.getData (/data/data/com.termux/files/home/BOT/node_modules/ws/lib/receiver.js:446:17) {
  data: {
    tag: 'stream:error',
    attrs: { code: '401' },
    content: [ [Object] ]
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 401,
    payload: {
      statusCode: 401,
      error: 'Unauthorized',
      message: 'Stream Errored'
    },
    headers: {}
  }
} , reconnecting  500

**Comment by alexdsgmoura** [comment]
+1
