### ISSUE TITLE
[BUG] Stream Error

### ISSUE THREAD

**Issue by Zarinia** [adiwajshing/Baileys#1441]
when connect mobile whatsapp with qr code generated in terminal
first connection successes but after 2 sec connection failed with error code
Connection closed. You are logged out.
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Stream Errored
        at WebSocket.<anonymous> (/Volumes/Data/Projects/Negin/whatsapp/src/Socket/socket.ts:552:7)
        at WebSocket.emit (node:events:527:28)
        at WebSocket.emit (node:domain:475:12)
        at /Volumes/Data/Projects/Negin/whatsapp/src/Socket/socket.ts:300:23
        at Object.decodeFrame (/Volumes/Data/Projects/Negin/whatsapp/src/Utils/noise-handler.ts:173:5)
        at WebSocket.onMessageRecieved (/Volumes/Data/Projects/Negin/whatsapp/src/Socket/socket.ts:273:9)
        at WebSocket.emit (node:events:527:28)
        at WebSocket.emit (node:domain:475:12)
        at Receiver.receiverOnMessage (/Volumes/Data/Projects/Negin/whatsapp/node_modules/ws/lib/websocket.js:1093:20)
        at Receiver.emit (node:events:527:28) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2022-03-31T20:20:20.862Z
  }
}
whats the problem !?

**Comment by muhamad-fadla** [comment]
same issue

**Comment by mogupta** [comment]
Same issue. I can confirm that this issue is only occurring on node version 16 , not on v14

**Comment by sreza78** [comment]
i have same issue in node v14 as well

**Comment by rodps** [comment]
same

**Comment by jccalbuquerque** [comment]
+1

**Comment by souravkl11** [comment]
I'm also facing this issue!

**Comment by AditdevID** [comment]
same issue

**Comment by codevjs** [comment]
same issue

**Comment by JuniorRibas** [comment]
same issue

**Comment by code-by** [comment]
+1, node v.16

**Comment by abdurahmanshiine** [comment]
Same issue here
