### ISSUE TITLE
Problem with start example.ts

### ISSUE THREAD

**Issue by Zarinia** [adiwajshing/Baileys#1446]
```
/Users/ar/.nvm/versions/node/v16.14.2/bin/npm run example

> @adiwajshing/baileys@4.0.2 example
> node --inspect -r ts-node/register Example/example.ts

Debugger listening on ws://127.0.0.1:9229/22ca4ac6-131c-4edd-9f56-732cb6122ff8
For help, see: https://nodejs.org/en/docs/inspector
using WA v2.2210.9, isLatest: true
connection update {
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
}
{"level":30,"time":"2022-04-02T12:40:01.808Z","pid":26026,"hostname":"Amir.local","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":{"type":"Buffer","data":[168,230,255,207,98,77,110,53,148,93,27,219,39,117,205,175,137,75,44,41,204,166,126,13,190,2,133,129,162,190,8,89]}}},"msg":"connected to WA Web"}
{"level":30,"time":"2022-04-02T12:40:02.257Z","pid":26026,"hostname":"Amir.local","msg":"handshake complete"}
{"level":30,"time":"2022-04-02T12:40:02.257Z","pid":26026,"hostname":"Amir.local","node":{"passive":true,"connectType":1,"connectReason":1,"userAgent":{"appVersion":{"primary":2,"secondary":2210,"tertiary":9},"platform":14,"releaseChannel":0,"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":0},"username":234560957924,"device":4},"msg":"logging in..."}
{"level":30,"time":"2022-04-02T12:40:05.187Z","pid":26026,"hostname":"Amir.local","error":{"data":{"reason":"401","location":"cln"},"isBoom":true,"isServer":false,"output":{"statusCode":401,"payload":{"statusCode":401,"error":"Unauthorized","message":"Connection Failure"},"headers":{}}},"msg":"connection closed"}
Connection closed. You are logged out.
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Connection Failure
        at WebSocket.<anonymous> (/Volumes/ar/whatsapp/src/Socket/socket.ts:574:7)
        at WebSocket.emit (node:events:526:28)
        at WebSocket.emit (node:domain:475:12)
        at /Volumes/ar/whatsapp/src/Socket/socket.ts:316:23
        at Object.decodeFrame (/Volumes/ar/whatsapp/src/Utils/noise-handler.ts:173:5)
        at WebSocket.onMessageRecieved (/Volumes/ar/whatsapp/src/Socket/socket.ts:289:9)
        at WebSocket.emit (node:events:526:28)
        at WebSocket.emit (node:domain:475:12)
        at Receiver.receiverOnMessage (/Volumes/ar/whatsapp/node_modules/ws/lib/websocket.js:1093:20)
        at Receiver.emit (node:events:526:28) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2022-04-02T12:40:05.188Z
  }
}
```

Hi
what is my problem?
Can anyone send me a complete code that uses this repo
thanks

**Comment by diegodorgam** [comment]
+1

**Comment by HanzCEO** [comment]
It seems like you're new to this library. But don't worry, i have made a simplified Baileys library wrapper called `fabuya`.

I'm trying to simplify the library so that beginner could get to know the circle.
Here's the GitHub repo: [HanzHaxors/fabuya](https://github.com/HanzHaxors/fabuya)

Happy hacking and developing
> Hanz
