### ISSUE TITLE
chatRead throws Unexpected status in action

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#145]
This error occurs with methods `chatRead`

``` BaileysError: Unexpected status in 'action': Bad Request(400)
     at WAConnection.query (/WAConnection/0.Base.js:240:19)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
     at async WAConnection.setQuery (/WAConnection/0.Base.js:212:24)
     at async WAConnection.sendReadReceipt (/WAConnection/7.MessagesExtra.js:88:22)
     at async WAConnection.chatRead (/WAConnection/7.MessagesExtra.js:69:13)
     at async /conn/WAConnection/Mutex.js:20:32
     at async sendRead (/lib/sendRead.js:9:3) {
   status: 400,
   context: {
     query: [ 'action', [Object], [Array] ],
     message: 'Bad Request',
     status: 400
   }
 }```

**Comment by adiwajshing** [comment]
1. Were you trying to read or unread the chat?
2. Was the last message yours or somebody else's?
3. Is this a group or individual chat?
4. Can you reproduce this issue?

**Comment by algoz098** [comment]
1. this happens when there's multiple messages mixed, read and not read, 
2. mine
3. individual
4. Send several messages yours without marking them as read, then try to mark the chat as read

**Comment by adiwajshing** [comment]
Could you try the latest version of Baileys, should work correctly 100% of the time now
