### ISSUE TITLE
[BUG] Error and always stop 

### ISSUE THREAD

**Issue by RidOne673** [adiwajshing/Baileys#1454]
why this?

Error: rate-overlimit
    at Object.assertNodeErrorFree (/app/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290:15)
    at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:134:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.groupMetadata (/app/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:20:24)
    at async client (/app/octave.js:1621:16) {
  data: 429,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

is there any solution?

**Comment by makanSukros** [comment]
How much message sending per minutes?

**Comment by Cyberkingcr7** [comment]
> How much message sending per minutes?

no messages
