### ISSUE TITLE
How to update profile name?

### ISSUE THREAD

**Issue by sandro-salles** [adiwajshing/Baileys#1461]
Can someone point me on how to update my profile name? I saw that changing the profile picture is possible (and it's working) using **updateProfilePicture**, but i can't find **how to update the profile name**.

Thanks in advance

**Comment by sandro-salles** [comment]
Anyone?

**Comment by victorkelvin** [comment]
You can use `groupUpdateSubject` method!

**Comment by frmdeveloper** [comment]
> @victorkelvin
> You can use `groupUpdateSubject` method!

```js
Error: Timed Out
    at /home/container/waauto/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157:32 {
  data: {
    stack: 'Error: \n' +
      '    at promiseTimeout (/home/container/waauto/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:152:19)\n' +
      '    at waitForMessage (/home/container/waauto/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:100:61)\n' +
      '    at query (/home/container/waauto/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:22)\n' +
      '    at groupQuery (/home/container/waauto/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:12:55)\n' +
      '    at Object.groupUpdateSubject (/home/container/waauto/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:57:19)\n' +
      '    at eval (eval at cmd.>.cmd..v (/home/container/waauto/feature.js:264:25), <anonymous>:1:29)\n' +
      '    at eval (eval at cmd.>.cmd..v (/home/container/waauto/feature.js:264:25), <anonymous>:1:84)\n' +
      '    at Object.cmd.>.cmd..v (/home/container/waauto/feature.js:264:25)\n' +
      '    at Object.exports.call (/home/container/waauto/feature.js:1079:40)\n' +
      '    at messagesUpsert (/home/container/waauto/bot.js:224:24)\n' +
      '    at /home/container/waauto/bot.js:238:28'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}
```
