### ISSUE TITLE
[BUG] 'Connection Closed'

### ISSUE THREAD

**Issue by Crzlyy** [adiwajshing/Baileys#1472]
}
Device Logged Out, Please Scan Again And Run.
Connected... {
  connection: 'close',
  lastDisconnect: {
    error: Error: Connection Failure
        at WebSocket.<anonymous> (c:\botdev\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:466:13)
        at WebSocket.emit (node:events:526:28)
        at c:\botdev\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:246:35
        at Object.decodeFrame (c:\botdev\node_modules\@adiwajshing\baileys\lib\Utils\noise-handler.js:143:17)
        at WebSocket.onMessageRecieved (c:\botdev\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:222:15)
        at WebSocket.emit (node:events:526:28)
        at Receiver.receiverOnMessage (c:\botdev\node_modules\ws\lib\websocket.js:1137:20)
        at Receiver.emit (node:events:526:28)
        at Receiver.dataMessage (c:\botdev\node_modules\ws\lib\receiver.js:513:14)
        at Receiver.getData (c:\botdev\node_modules\ws\lib\receiver.js:446:17) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2022-04-10T08:58:29.087Z
  }
}
c:\botdev\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:66
            throw new boom_1.Boom('Connection Closed', { statusCode: Types_1.DisconnectReason.connectionClosed });
                  ^

Error: Connection Closed
    at sendRawMessage (c:\botdev\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:66:19)
    at sendNode (c:\botdev\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:74:16)
    at Object.logout (c:\botdev\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:353:19)
    at EventEmitter.<anonymous> (c:\botdev\index.js:223:132)
    at EventEmitter.emit (node:events:538:35)
    at end (c:\botdev\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:268:12)
    at WebSocket.<anonymous> (c:\botdev\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:466:9)
    at WebSocket.emit (node:events:526:28)
    at c:\botdev\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:246:35
    at Object.decodeFrame (c:\botdev\node_modules\@adiwajshing\baileys\lib\Utils\noise-handler.js:143:17) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}

**Comment by tyagolp** [comment]
+1

**Comment by masbilal** [comment]
same problem

**Comment by WevertonCouto** [comment]
update to 4.1.0 problem solve

**Comment by ngadimin51** [comment]
> update to 4.1.0 problem solve

I'm using 4.1.0 still have same problem

**Comment by LightningNeko** [comment]
+1

**Comment by khoirulamri** [comment]
+1

**Comment by Davidiasdesousa** [comment]
> 

Can you explain a little bit more?

My code not working...

import Ws from "App/Services/Ws";
const {
  WAConnection,
  MessageType,
  MessageOptions,
  Mimetype,
} = require("@adiwajshing/baileys");
const qrcode = require("qrcode");
var store = require("store");
Ws.boot();
let conn;
if (!store.get("tokenAuth")) {
  conn = new WAConnection();
}
connectToWhatsApp().catch((err) => console.log("unexpected error: " + err)); // catch any errors

/**
 * Listen for incoming socket connections
 */
async function connectToWhatsApp() {
  Ws.io.on("connection", async (socket) => {


    if (conn.state === "close") {
      console.log("...........close");
      socket.emit("close", "");
      await conn.connect();
    }else if (conn.state === 'open'){
      socket.emit("ready", "Whatsapp Conectado!");
    }



...

**Comment by Davidiasdesousa** [comment]
> I found why my code is closed. It cause mu function is multi user. So i used array instead.
> 
> Example : let sock = [] async function connect(session) { sock[session] = makeWa .. .. .. .. // When conn is close reconect is connect() like example, it wrong, cause i use an array user. So i change to when conn is close connect(session). Voila my script works again }

Can you explain a little bit more?

My code not working...

import Ws from "App/Services/Ws";
const {
WAConnection,
MessageType,
MessageOptions,
Mimetype,
} = require("@adiwajshing/baileys");
const qrcode = require("qrcode");
var store = require("store");
Ws.boot();
let conn;
if (!store.get("tokenAuth")) {
conn = new WAConnection();
}
connectToWhatsApp().catch((err) => console.log("unexpected error: " + err)); // catch any errors

/**

Listen for incoming socket connections
*/
async function connectToWhatsApp() {
Ws.io.on("connection", async (socket) => {

if (conn.state === "close") {
console.log("...........close");
socket.emit("close", "");
await conn.connect();
}else if (conn.state === 'open'){
socket.emit("ready", "Whatsapp Conectado!");
}

...

**Comment by sah-anshu** [comment]
this problem still exists in 4.1.0
```
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Stream Errored
        at WebSocket.<anonymous> (/home/anshu/NewProjects/Baileys-4.1.0/src/Socket/socket.ts:553:7)
        at WebSocket.emit (events.js:315:20)
        at WebSocket.EventEmitter.emit (domain.js:486:12)
        at /home/anshu/NewProjects/Baileys-4.1.0/src/Socket/socket.ts:301:23
        at Object.decodeFrame (/home/anshu/NewProjects/Baileys-4.1.0/src/Utils/noise-handler.ts:173:5)
        at WebSocket.onMessageRecieved (/home/anshu/NewProjects/Baileys-4.1.0/src/Socket/socket.ts:274:9)
        at WebSocket.emit (events.js:315:20)
        at WebSocket.EventEmitter.emit (domain.js:486:12)
        at Receiver.receiverOnMessage (/home/anshu/NewProjects/Baileys-4.1.0/node_modules/ws/lib/websocket.js:1093:20)
        at Receiver.emit (events.js:315:20) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2022-04-13T08:45:08.281Z
  }
}

```

**Comment by rhutikcodes** [comment]
+1

**Comment by sreza78** [comment]
For stream error, change your internet ISP

**Comment by KingMaxine** [comment]
@sreza78 i don't understand your reply can you elaborate

**Comment by sreza78** [comment]
> @sreza78 i don't understand your reply can you elaborate

When i try to authenticate MD account, sometimes i get `streamed error`, for me when i change my network connection to another ISP it works well and no error occurred.

**Comment by KingMaxine** [comment]
@sreza78 doesn't work for me

**Comment by shubhamrathi97** [comment]
@sreza78 It is working on web.whatsapp.com with the same ISP. It should be the implementation and library issues that We need to resolve.

**Comment by guiguicdd** [comment]
Same here

**Comment by moanemanuel** [comment]
+1

**Comment by JustPandaEver** [comment]
root/botv3/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:48
            throw new boom_1.Boom('Connection Closed', { statusCode: Types_1.DisconnectReason.connectionClosed });
                  ^

Error: Connection Closed
    at sendRawMessage (/root/botv3/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:48:19)
    at sendNode (/root/botv3/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:59:16)
    at Object.logout (/root/botv3/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:325:19)
    at EventEmitter.<anonymous> (/root/botv3/index.js:223:137)
    at EventEmitter.emit (node:events:539:35)
    at end (/root/botv3/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:240:12)
    at WebSocket.<anonymous> (/root/botv3/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:419:9)
    at WebSocket.emit (node:events:527:28)
    at /root/botv3/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:219:35
    at Object.decodeFrame (/root/botv3/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}

**Comment by bharat0to** [comment]
Precondition Required.
It is resolved in mine by waiting for connection open

const sock = makeWASocket({...})
await sock.waitForConnectionUpdate(({ connection }) => connection === "open" )
...

**Comment by zhinea** [comment]
> ({ connection }) => connection === "open" )

Thank you :)

**Comment by sarveshbhinge** [comment]
Error: Unexpected server response: 404
    at ClientRequest.<anonymous> (E:\wampp\htdocs\bb\node_modules\ws\lib\websocket.js:783:7)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

kindly help me to resolve

**Comment by ikbalardiansah** [comment]
Any solution??

**Comment by satriowicaksn** [comment]
+1
