### ISSUE TITLE
[BUG]This error started appearing out of nowhere... The "key" argument must be of type string or an instance of Buffer

### ISSUE THREAD

**Issue by Davidiasdesousa** [adiwajshing/Baileys#1485]
This error started appearing out of nowhere... I don't know what it could be.

`opened connection to WhatsApp Web
    class: "Baileys"
(node:14964) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (C:\Users\EuSousa\Documents\PROJETOS\PASSON\WApp\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (C:\Users\EuSousa\Documents\PROJETOS\PASSON\WApp\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (C:\Users\EuSousa\Documents\PROJETOS\PASSON\WApp\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:86:18)
    at WAConnection.emit (events.js:400:28)
    at WAConnection.emit (C:\Users\EuSousa\Documents\PROJETOS\PASSON\WApp\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41)
    at WAConnection.connect (C:\Users\EuSousa\Documents\PROJETOS\PASSON\WApp\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14) 
(node:14964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
INFO [2022-04-13 05:47:05.822 +0000] (14964): closed connection, reason close, reconnecting in a few seconds...
    class: "Baileys"
Client was logged out close close
Disconnected because close, reconnecting: true`

**Comment by rezendefelipe** [comment]
I have the same problem, anyone?

**Comment by GabrielBels** [comment]
Same problem here

**Comment by ashish1500616** [comment]
Try to update the node to the latest version and see if helps.

**Comment by caiosales35** [comment]
same here :(

**Comment by cp-yago** [comment]
same problem here :/

**Comment by drickchote** [comment]
Anyone? Same problem here.

**Comment by madkey77** [comment]
Same here... Just stoped working

**Comment by GabrielBels** [comment]
Hey guys. Recently the WhatsApp implemented the Multi-Device function permanently and obrigatory in their new version. With that update, the version not MD of Baileys stopped to work. To solve, I migrate all my code to new version of baileys and inactivate the old code. I recommend for you try do this.

**Comment by ashish1500616** [comment]
Try this out and see if it works for you.

https://github.com/adiwajshing/Baileys/issues/1489#issuecomment-1101767940

**Comment by Xrazik1** [comment]
You should pass `reviver` while parsing credentials from a JSON before passing them to the socket.

Like this: 
`import reviver from "@stdlib/buffer-reviver";`
`JSON.parse(await this.get("credentials") as unknown as string, revive)`
