### ISSUE TITLE
Error on send photo with buffer

### ISSUE THREAD

**Issue by sreza78** [adiwajshing/Baileys#1486]
**When i trying to send photo message with buffer gives me following error**

## Code
```js
client.sendMessage("***********", { image : File.buffer, fileName: File.name, caption: "" })
```

## Error
```
TypeError: Cannot read property 'toString' of undefined
    at Object.getStream (~/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196:18)
    at Object.encryptedStream (~/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:232:44)
    at Object.prepareWAMessageMedia (~/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:70:132)
    at Object.generateWAMessageContent (~/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:227:27)
    at Object.generateWAMessage (~/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:349:68)
    at Object.sendMessage (~/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:397:47)
    at _callee$ (~/src/services/baileys/index.js:84:24)
    at tryCatch (~/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (~/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (~/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (~/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (~/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

**Comment by vishwajit76** [comment]
same problem
