### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#149]
Another strange error
```
TypeError: Cannot read property 'length' of undefined
    at WAConnection.chatAddMessage (/var/sulla-slave/conn/WAConnection/4.Events.js:228:32)
    at WAConnection.chatAddMessageAppropriate (/var/sulla-slave/conn/WAConnection/4.Events.js:201:14)
    at WAConnection.relayWAMessage (/var/sulla-slave/conn/WAConnection/6.MessagesSend.js:173:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WAConnection.sendMessage (/var/sulla-slave/conn/WAConnection/6.MessagesSend.js:25:9)
    at async routes.postSend (/var/sulla-slave/routes/index.js:67:15)
```

**Comment by adiwajshing** [comment]
Have you altered the chat `messages` property in some way?

**Comment by algoz098** [comment]
I did not

**Comment by adiwajshing** [comment]
What do you mean by`memory pointer`?
