### ISSUE TITLE
ReferenceError: WhatsAppWeb is not defined

### ISSUE THREAD

**Issue by brunon80** [adiwajshing/Baileys#15]
Hi, thanks for this awesome project!

This error happens when I receive a media message, for example a image

`
/home/aorus/Documentos/projetos/testes/new_zap/node_modules/baileys/WhatsAppWeb.Recv.js:214
        if (type === WhatsAppWeb.MessageType.extendedText || type === WhatsAppWeb.MessageType.text) {
                     ^

ReferenceError: WhatsAppWeb is not defined
    at WhatsAppWeb.decodeMediaMessage (/home/aorus/Documentos/projetos/testes/new_zap/node_modules/baileys/WhatsAppWeb.Recv.js:214:22)
    at /home/aorus/Documentos/projetos/testes/new_zap/src/server.ts:53:16
    at /home/aorus/Documentos/projetos/testes/new_zap/node_modules/baileys/WhatsAppWeb.js:123:17
    at WhatsAppWeb.onMessageRecieved (/home/aorus/Documentos/projetos/testes/new_zap/node_modules/baileys/WhatsAppWeb.Recv.js:96:21)
    at WebSocket.<anonymous> (/home/aorus/Documentos/projetos/testes/new_zap/node_modules/baileys/WhatsAppWeb.Session.js:30:41)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/aorus/Documentos/projetos/testes/new_zap/node_modules/baileys/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/home/aorus/Documentos/projetos/testes/new_zap/node_modules/baileys/node_modules/ws/lib/receiver.js:427:14)
    at Receiver.getData (/home/aorus/Documentos/projetos/testes/new_zap/node_modules/baileys/node_modules/ws/lib/receiver.js:366:17)
[nodemon] app crashed - waiting for file changes before starting...
`

**Comment by adiwajshing** [comment]
Fixed in the latest commit, test it out and lemme know?

**Comment by brunon80** [comment]
Fixed! thanks! can you add this version on npm?

**Comment by adiwajshing** [comment]
I'll accumulate a few more fixes & changes, and then upload on npm in a few days. Till then probably just use the master branch.

**Comment by brunon80** [comment]
thanks, by the way, there is a way to get base64 qrcode on `connect` function or in other way?

**Comment by adiwajshing** [comment]
No problem. Presently, printing the private keys as a QR code is the only way you can access those keys. However, making that extensible so that you get access to those keys should be fairly easy. What exactly do you have in mind?

**Comment by brunon80** [comment]
I would like to call the `connect` function, then the string that is used to generate the qr code stay in the client instance, for example:

`client.strConnection // here is the string => ref + "," + publicKeyStr + "," + this.authInfo.clientID`

So I can otherwise generate the qr code

**Comment by adiwajshing** [comment]
I see. I'll add this functionality. I'm closing this issue, please open another one for this.
