### ISSUE TITLE
Not able to start sample file[BUG]

### ISSUE THREAD

**Issue by ankit131996** [adiwajshing/Baileys#1504]
Environment Details:
1. OS - Ubuntu
2. npm version - v12.16.2 / v12.10.2

Steps which I am following:
1. Clone update project
2. Run "npm i".
3. Start example file "npm run example".
When we run the example file it give me an error:

Debugger listening on ws://127.0.0.1:9229/d856d9e5-2fb3-4c0c-9761-f7bac4b1fff6
For help, see: https://nodejs.org/en/docs/inspector
Error: Cannot find module 'fs/promises'
Require stack:
- /home/user/Baileys/src/Utils/baileys-event-stream.ts
- /home/user/Baileys/src/Utils/index.ts
- /home/user/Baileys/src/Defaults/index.ts
- /home/user/Baileys/src/LegacySocket/index.ts
- /home/user/Baileys/src/index.ts
- /home/user/Baileys/Example/example.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/user/Baileys/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/user/Baileys/src/Utils/baileys-event-stream.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module.m._compile (/home/user/Baileys/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.require.extensions.<computed> [as .ts] (/home/user/Baileys/node_modules/ts-node/src/index.ts:1458:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/Baileys/src/Utils/baileys-event-stream.ts',
    '/home/user/Baileys/src/Utils/index.ts',
    '/home/user/Baileys/src/Defaults/index.ts',
    '/home/user/Baileys/src/LegacySocket/index.ts',
    '/home/user/Baileys/src/index.ts',
    '/home/user/Baileys/Example/example.ts'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @adiwajshing/baileys@4.1.0 example: `node --inspect -r ts-node/register Example/example.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @adiwajshing/baileys@4.1.0 example script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-04-18T13_09_15_379Z-debug.log

**Comment by ashish1500616** [comment]
Hi @ankit131996 ,

Try this out
```
1. Clone .
2. yarn install
3. yarn example
```

**Comment by ankit131996** [comment]
Hi  @ashish1500616,

Thank you for your reply.

After executing the above commands it gives me the below error:

yarn run v1.22.18
$ node --inspect -r ts-node/register Example/example.ts
Debugger listening on ws://127.0.0.1:9229/4330d31d-6ea0-4502-a850-a34766e042be
For help see https://nodejs.org/en/docs/inspector
/home/user/Baileys/node_modules/ts-node/dist/resolver-functions.js:97
                catch { } // gracefully do nothing when @types/node is not installed for any reason
                      ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/Baileys/node_modules/ts-node/dist/index.js:13:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Alhar6i** [comment]
try to install types
`yarn add types`

**Comment by gmlemus** [comment]
This error is related to your nodeJs version, you should have at least nodejs 14 in order to avoid this issue (i just googled it and the tested and work fine)
