### ISSUE TITLE
[BUG] Cannot find module 'link-preview-js'

### ISSUE THREAD

**Issue by textarea** [adiwajshing/Baileys#1515]
Sending a text message with a link in the content send correctly but in console log there is the following error message.
`const sentMsg = await sock.sendMessage(
        to,
        { text: message },
        { detectLinks: true },
      );`

"Error: Cannot find module 'link-preview-js'
Require stack:
- /var/www/node_modules/@adiwajshing/baileys/lib/Utils/link-preview.js
- /var/www/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js
- /var/www/node_modules/@adiwajshing/baileys/lib/Socket/chats.js
- /var/www/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js
- /var/www/node_modules/@adiwajshing/baileys/lib/Socket/business.js
- /var/www/node_modules/@adiwajshing/baileys/lib/Socket/index.js
- /var/www/node_modules/@adiwajshing/baileys/lib/index.js
- /var/www/dist/app.service.js
- /var/www/dist/app.controller.js
- /var/www/dist/app.module.js
- /var/www/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Module.Hook._require.Module.require (/var/www/.nvm/versions/node/v16.13.1/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /var/www/node_modules/@adiwajshing/baileys/lib/Utils/link-preview.js:39:84
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.getUrlInfo (/var/www/node_modules/@adiwajshing/baileys/lib/Utils/link-preview.js:39:36)
    at Object.generateWAMessageContent (/var/www/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:179:30)
    at Object.generateWAMessage (/var/www/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:349:54)
    at Object.sendMessage (/var/www/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:398:33)","msg":"url generation failed"}

**Comment by sreza78** [comment]
according to [this](https://github.com/adiwajshing/Baileys/commit/872536fa5bad590846866ddf8dd2855b66360ee8) install `link-preview-js` module will fix the problem

**Comment by textarea** [comment]
Thank you @sreza78 👍
