### ISSUE TITLE
cannot connect when state=connecting

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#152]
This is expected?
There's a way to grab this error?
```
Error: cannot connect when state=connecting
 at WAConnection.connect (/WAConnection/3.Connect.js:37:19)
 at WAConnection.unexpectedDisconnect (/WAConnection/0.Base.js:99:31)
 at WebSocket.<anonymous> (/WAConnection/3.Connect.js:71:42)
 at WebSocket.emit (events.js:315:20)
 at WebSocket.emitClose (/node_modules/ws/lib/websocket.js:194:10)
 at TLSSocket.socketOnClose (/node_modules/ws/lib/websocket.js:862:15)
 at TLSSocket.emit (events.js:327:22)
 at net.js:674:12
 at TCP.done (_tls_wrap.js:567:7)
```

**Comment by adiwajshing** [comment]
Do you have your own auto-reconnect setup?

**Comment by algoz098** [comment]
Yes I do. Tested the code without it the conn is lost after couple hours. Auto reconnect doesn't work as I expected

**Comment by adiwajshing** [comment]
If you have your own autoReconnect setup, just set `con.autoReconnect = ReconnectMode.off` -- then the inbuilt autoReconnect won't interfere with yours

**Comment by algoz098** [comment]
In the end i opt to remove my autoReconnect. Was just not good enough. I will close this.
