### ISSUE TITLE
[BUG] TypeError: this.isZero is not a function

### ISSUE THREAD

**Issue by bigbangshop** [adiwajshing/Baileys#1520]
I see the error below when replying to a message with media. But response is sending to another user.
when retrieving the message in the event "messages.upsert" the same error occurs, making it impossible to archive the message in the database

Caught exception: TypeError: this.isZero is not a function
    at String.toString (/var/www/bll/node_modules/@adiwajshing/baileys/node_modules/long/src/long.js:474:14)
    at Function.toObject (/var/www/bll/node_modules/@adiwajshing/baileys/WAProto/index.js:17479:98)
    at Function.toObject (/var/www/bll/node_modules/@adiwajshing/baileys/WAProto/index.js:22493:64)
    at Function.toObject (/var/www/bll/node_modules/@adiwajshing/baileys/WAProto/index.js:8449:60)
    at Function.toObject (/var/www/bll/node_modules/@adiwajshing/baileys/WAProto/index.js:10909:62)
    at Function.toObject (/var/www/bll/node_modules/@adiwajshing/baileys/WAProto/index.js:22499:78)
    at Function.toObject (/var/www/bll/node_modules/@adiwajshing/baileys/WAProto/index.js:61887:54)
    at WebMessageInfo.toJSON (/var/www/bll/node_modules/@adiwajshing/baileys/WAProto/index.js:61993:37)
    at hasBinary (/var/www/bll/node_modules/socket.io-parser/dist/is-binary.js:46:30)
    at hasBinary (/var/www/bll/node_modules/socket.io-parser/dist/is-binary.js:34:17) unhandledRejection

**Comment by bigbangshop** [comment]
I solved it by making the change below in node_modules/@adiwajshing/baileys/node_modules/long/src/long.js


![image](https://user-images.githubusercontent.com/71706553/165800837-a03c77d1-236f-4aad-a8f3-ed751d217629.png)

**Comment by rafosolima** [comment]
I updated the version by master and this problem stopped

```bash
rm -rf node_modules/
yarn add https://github.com/adiwajshing/Baileys
yarn install
```
