### ISSUE TITLE
[BUG] QR Code Loop After Scan

### ISSUE THREAD

**Issue by makanSukros** [adiwajshing/Baileys#1535]
After im upgrading to version 4.1.0, then im scan qr code, after scan qr code loop with error message like this: 

lastDisconnect: {
    error: Error: Stream Errored
        at WebSocket.<anonymous> (D:\OLD\Research\baileys-md\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:441:13)
        at WebSocket.emit (node:events:394:28)
        at D:\OLD\Research\baileys-md\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:227:35
        at Object.decodeFrame (D:\OLD\Research\baileys-md\node_modules\@adiwajshing\baileys\lib\Utils\noise-handler.js:142:17)
        at WebSocket.onMessageRecieved (D:\OLD\Research\baileys-md\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:203:15)
        at WebSocket.emit (node:events:394:28)
        at Receiver.receiverOnMessage (D:\OLD\Research\baileys-md\node_modules\ws\lib\websocket.js:1137:20)
        at Receiver.emit (node:events:394:28)
        at Receiver.dataMessage (D:\OLD\Research\baileys-md\node_modules\ws\lib\receiver.js:513:14)
        at Receiver.getData (D:\OLD\Research\baileys-md\node_modules\ws\lib\receiver.js:446:17) {
      data: [Object],
      isBoom: true,
      isServer: true,
      output: [Object]
    },
    date: 2022-04-25T02:01:37.974Z
  }

**To Reproduce**
1. Upgrade to version 4.1.0
2. Create new connection until qr showing
3. Scan Qr Code
4. Qr Code always change loop after scan

But if im continue session from previous version still working perfectly, I have also tried changing various internet provider connections, the results are the same

**Comment by makanSukros** [comment]
after I replaced this library with the previous version that I had backed up, the problem was resolved and I was able to scan qr normally,

here is my package.json:

{
   "name": "baileys-md",
   "version": "1.0.0",
   "description": "",
   "main": "index.js",
   "scripts": {
     "test": "echo \"Error: no test specified\" && exit 1"
   },
   "author": "",
   "license": "ISC",
   "dependencies": {
     "@adiwajshing/baileys": "github:adiwajshing/baileys",
     "@adiwajshing/keyed-db": "^0.2.4",
     "axios": "^0.25.0",
     "cors": "^2.8.5",
     "express": "^4.17.2",
     "pino": "^7.6.5",
   }
}

**Comment by HanzCEO** [comment]
Stream error is happening to me too, i will try find a solution. This might be caused by recent push of patches for invalid QR issue

**Comment by rajuaryan21** [comment]
Yeah, it's happening to me too.

**Comment by HanzCEO** [comment]
Check if statusCode === 515 and reconnect, this works

**Comment by makanSukros** [comment]
> 515

still not working

**Comment by HanzCEO** [comment]
> > 515
> 
> still not working

Can you provide your code here?

**Comment by makanSukros** [comment]
> > > 515
> > 
> > 
> > still not working
> 
> Can you provide your code here?

Working now with latest version

**Comment by muhamad-fadla** [comment]
> 515

thanks, working perfectly on baileys ```"^4.1.0"```
