### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'decode')

### ISSUE THREAD

**Issue by SL-Alpha-X** [adiwajshing/Baileys#1560]
**This is my error:**

```node
 Error: /root/AlphaXmd/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:100
            const { key: certKey } = WAProto_1.proto.NoiseCertificateDetails.decode(certDetails);
                                                                              ^
 TypeError: Cannot read properties of undefined (reading 'decode')
     at Object.processHandshake (/root/AlphaXmd/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:100:78)
     at WebSocket.validateConnection (/root/AlphaXmd/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:156:30)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

 Node.js v18.0.0
```

**How to solve this** :'(

**Comment by SL-Alpha-X** [comment]
Eny solutions ?

**Comment by akhilnarayanan1** [comment]
Help, same issue here ;_;

**Comment by rafaellojas2** [comment]
Sorry for my english, I'm using Google Translate to answer...

I had the same problem, I was trying to download media but this error always occurred, but I solved it in a very simple way, I just changed from version 4.2.0 of Baileys to version 4.1.0.

And to download media in version 4.1.0 I used the following code:
```
import { writeFile } from 'fs/promises'
import { downloadContentFromMessage } from '@adiwajshing/baileys'

sock.ev.on('messages.upsert', async ({ messages }) => {
    const m = messages[0]

    if (!m.message) return // if there is no text or media message
    const messageType = Object.keys (m.message)[0]// get what type of message it is -- text, image, video
    // if the message is an image
    if (messageType === 'imageMessage') {
        // download stream
        const stream = await downloadContentFromMessage(m.message.imageMessage, 'image')
        let buffer = Buffer.from([])
        for await(const chunk of stream) {
            buffer = Buffer.concat([buffer, chunk])
        }
        // save to file
        await writeFile('./my-download.jpeg', buffer)
    }
}
```

And it's back working normally, but remember to switch back to version 4.2.0 as soon as you can, it's important to keep everything up to date on the latest version. 😄

Link of version 4.1.0 that the error is not happening:
[https://github.com/adiwajshing/Baileys/tree/v4.1.0](url)
