### ISSUE TITLE
[BUG] Unsupported state or unable to authenticate data

### ISSUE THREAD

**Issue by hezqi** [adiwajshing/Baileys#1581]
Error: Unsupported state or unable to authenticate data

Require stack:
```
0|whatsapp-api-md-01  | Error: Unsupported state or unable to authenticate data
0|whatsapp-api-md-01  |     at Object.final (<anonymous>)
0|whatsapp-api-md-01  |     at Decipheriv.final (internal/crypto/cipher.js:174:29)
0|whatsapp-api-md-01  |     at decrypt (/var/www/whatsapp-api-md/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:43:66)
0|whatsapp-api-md-01  |     at Object.decodeFrame (/var/www/whatsapp-api-md/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:139:36)
0|whatsapp-api-md-01  |     at WebSocket.onMessageRecieved (/var/www/whatsapp-api-md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:15)
0|whatsapp-api-md-01  |     at WebSocket.emit (events.js:400:28)
0|whatsapp-api-md-01  |     at Receiver.receiverOnMessage (/var/www/whatsapp-api-md/node_modules/ws/lib/websocket.js:1160:20)
0|whatsapp-api-md-01  |     at Receiver.emit (events.js:400:28)
0|whatsapp-api-md-01  |     at Receiver.dataMessage (/var/www/whatsapp-api-md/node_modules/ws/lib/receiver.js:513:14)
0|whatsapp-api-md-01  |     at Receiver.getData (/var/www/whatsapp-api-md/node_modules/ws/lib/receiver.js:446:17)
0|whatsapp-api-md-01  | {"level":50,"time":1651972173978,"pid":73586,"hostname":"whatsapp-api-md-01","err":{"type":"Error","message":"Unsupported state or unable to authenticate data","stack":"Error: Unsupported state or unable to authenticate data\n    at Object.final (<anonymous>)\n    at Decipheriv.final (internal/crypto/cipher.js:174:29)\n    at decrypt (/var/www/whatsapp-api-md/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:43:66)\n    at Object.decodeFrame (/var/www/whatsapp-api-md/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:139:36)\n    at WebSocket.onMessageRecieved (/var/www/whatsapp-api-md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:15)\n    at WebSocket.emit (events.js:400:28)\n    at Receiver.receiverOnMessage (/var/www/whatsapp-api-md/node_modules/ws/lib/websocket.js:1160:20)\n    at Receiver.emit (events.js:400:28)\n    at Receiver.dataMessage (/var/www/whatsapp-api-md/node_modules/ws/lib/receiver.js:513:14)\n    at Receiver.getData (/var/www/whatsapp-api-md/node_modules/ws/lib/receiver.js:446:17)"},"msg":"Unsupported state or unable to authenticate data"}
```

**To Reproduce**
I don't know exactly, because it happened it self. but when I did send a message.

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - What do your `connectOptions` look like? 
```
defaultQueryTimeoutMs: undefined,
browser: Browsers.ubuntu('Chrome'),
logger: pino({ level: 'silent' }),
printQRInTerminal: false,
auth: state
```
 - Do you have multiple clients on the same IP? Yes
 - Are you using a proxy? No

Please help...

**Comment by sultanlive** [comment]
Please, help

**Comment by chandika7d** [comment]
i have same issue
