### ISSUE TITLE
Error when getting user profile pic item not found

### ISSUE THREAD

**Issue by AxeemHaider** [adiwajshing/Baileys#1622]
**Describe the bug**
I'm using edge version on Baileys, Everything was working and suddenly I'm getting this error this is because when I try to get profile pic of user

```
Error: item-not-found
    at Object.assertNodeErrorFree (/home/haider/codeplace/bitrespond/wa-backend/node_modules/.pnpm/github.com+adiwajshing+baileys@85a58fbc10caa92e726044336a7e6ff3f562fc62/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/home/haider/codeplace/bitrespond/wa-backend/node_modules/.pnpm/github.com+adiwajshing+baileys@85a58fbc10caa92e726044336a7e6ff3f562fc62/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:135:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.profilePictureUrl (/home/haider/codeplace/bitrespond/wa-backend/node_modules/.pnpm/github.com+adiwajshing+baileys@85a58fbc10caa92e726044336a7e6ff3f562fc62/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:310:24)
```

**To Reproduce**
1. Created a new connection

**Environment (please complete the following information):**
 - Is this on a server? YES
 - What do your `connectOptions` look like? 
 ```js
   makeWASocket({
      auth: creds,
    });
```
 - Do you have multiple clients on the same IP? NO
 - Are you using a proxy? NO

**Comment by HUGEIT** [comment]
does the process crash or is it just the error?

**Comment by AxeemHaider** [comment]
process crash.

I want out the way why this is happen if user does not have profile pic then this error come. I think this should be only error not to crash the process but this error crash the process

**Comment by panalgin** [comment]
This also happens for me too, the process is crashed and there is no way to catch it via try/catch operation

`{"level":10,"time":"2022-10-19T15:35:05.418Z","pid":11896,"hostname":"DESKTOP-5GJQITL","msgId":"53049.63166-7","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"***@s.whatsapp.net","type":"error","id":"53049.63166-7"},"content":[{"tag":"error","attrs":{"code":"404","text":"item-not-found"}}]},"msg":"communication"}
project_path\node_modules\@adiwajshing\baileys\lib\WABinary\generic-utils.js:56
        throw new boom_1.Boom(errNode.attrs.text || 'Unknown error', { data: +errNode.attrs.code });
              ^
Error: item-not-found
    at assertNodeErrorFree (project_path\node_modules\@adiwajshing\baileys\lib\WABinary\generic-utils.js:56:15)
    at query (project_path\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:127:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.profilePictureUrl (project_path\node_modules\@adiwajshing\baileys\lib\Socket\chats.js:375:24) {
  data: 404,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}`
