### ISSUE TITLE
[BUG] ERR_INVALID_ARG_TYPE for the multi-file-auth-state

### ISSUE THREAD

**Issue by ravindu01manoj** [adiwajshing/Baileys#1660]
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
at Object.writeFile (node:internal/fs/promises:814:5)
at writeData (/root/node_modules/@adiwajshing/baileys/lib/Utils/use-multi-file-auth-state.js:18:27)
at Object.set (/root/node_modules/@adiwajshing/baileys/lib/Utils/use-multi-file-auth-state.js:58:40)
at Object.set (/root/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:64:30)
at Object.storeSession (/root/node_modules/@adiwajshing/baileys/lib/Utils/signal.js:97:20)
at 994404069683.0 [as awaitable] (/root/node_modules/libsignal/src/session_builder.js:51:32)
at async _asyncQueueExecutor (/root/node_modules/libsignal/src/queue_job.js:20:29) {
code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by BochilGaming** [comment]
Maybe [this commit](https://github.com/adiwajshing/Baileys/commit/ef71b7e09da402084448595f4af49da049f03df4) fix your issue

**Comment by ravindu01manoj** [comment]
yep
