### ISSUE TITLE
[BUG] useMultiFileAuthState

### ISSUE THREAD

**Issue by daniel672-boo** [adiwajshing/Baileys#1661]
TypeError: Cannot destructure property 'creds' of 'authState' as it is undefined.                        at makeSocket (/storage/emulated/0/bots/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:35:13)                                                                                                     at makeGroupsSocket (/storage/emulated/0/bots/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:8:42)                                                                                                at makeMessagesSocket (/storage/emulated/0/bots/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:16:48)                                                                                      at makeChatsSocket (/storage/emulated/0/bots/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:13:57)                                                                                                 at makeMessagesRecvSocket (/storage/emulated/0/bots/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:38:46)                                                                                  at makeBusinessSocket (/storage/emulated/0/bots/node_modules/@adiwajshing/baileys/lib/Socket/business.js:9:61)                                                                                            at makeWASocket (/storage/emulated/0/bots/node_modules/@adiwajshing/baileys/lib/Socket/index.js:6:69)

**Comment by Islam-Mohammed-Younes** [comment]
cant replicate your issue using example.ts
if you are using plain JavaScript make sure you use await before useMultiFileAuthState
`const { state, saveCreds } =  useMultiFileAuthState("baileys_auth_info");`

**Comment by daniel672-boo** [comment]
Ok, amanhã eu vou tentar usar await.

**Comment by kmhari** [comment]
`useMultiFileAuthState` returns a promise. So you'll have to use `await` to collect the data before passing `state` onto `makeWASocket`

**Comment by mirsyad23** [comment]
TypeError: Cannot destructure property 'creds' of 'authState' as it is undefined.
    at makeSocket (/var/wa/mirsyad/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:35:13)
    at makeChatsSocket (/var/wa/mirsyad/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:19:42)
    at makeGroupsSocket (/var/wa/mirsyad/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:10:46)
    at makeMessagesSocket (/var/wa/mirsyad/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:17:48)
    at makeMessagesRecvSocket (/var/wa/mirsyad/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:15:57)
    at makeBusinessSocket (/var/wa/mirsyad/node_modules/@adiwajshing/baileys/lib/Socket/business.js:9:61)
    at makeWASocket (/var/wa/mirsyad/node_modules/@adiwajshing/baileys/lib/Socket/index.js:6:69)
    at Object.<anonymous> (/var/wa/mirsyad/index.js:133:14)
