### ISSUE TITLE
[BUG] Can't create product with images urls

### ISSUE THREAD

**Issue by AtefR** [adiwajshing/Baileys#1675]
can't create product with image urls

code: 

```javascript
const product = await session.productCreate({
  name: 'wTest',
  description: 'testsss',
  price: '500',
  currency: 'EGP',
  isHidden: false,
  images: [
    {
      url: 'https://yatunisia.com/wp-content/uploads/2021/02/f834ffb723ff729f4d0610b176afef10-780x359.png'
    }
  ]
})
```
errors:
```

{"level":40,"time":1653927840990,"pid":10380,"hostname":"Laptop","trace":"Error: Request failed with status code 415\n    at createError (C:\\Users\\Vincent\\Code\\wa-api\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (C:\\Users\\Vincent\\Code\\wa-api\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\Vincent\\Code\\wa-api\\node_modules\\axios\\lib\\adapters\\http.js:293:11)\n    at IncomingMessage.emit (node:events:538:35)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","uploadResult":{"debug_info":{"retriable":false,"type":"INVALID_MEDIA_TYPE","message":"Invalid media type"}},"msg":"Error in uploading to media.fcai11-1.fna.whatsapp.net , retrying..."}
{"level":40,"time":1653927841532,"pid":10380,"hostname":"Laptop","trace":"Error: Request failed with status code 415\n    at createError (C:\\Users\\Vincent\\Code\\wa-api\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (C:\\Users\\Vincent\\Code\\wa-api\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\Vincent\\Code\\wa-api\\node_modules\\axios\\lib\\adapters\\http.js:293:11)\n    at IncomingMessage.emit (node:events:538:35)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","uploadResult":{"debug_info":{"retriable":false,"type":"INVALID_MEDIA_TYPE","message":"Invalid media type"}},"msg":"Error in uploading to media-hbe1-1.cdn.whatsapp.net , retrying..."}
{"level":40,"time":1653927842191,"pid":10380,"hostname":"Laptop","trace":"Error: Request failed with status code 415\n    at createError (C:\\Users\\Vincent\\Code\\wa-api\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (C:\\Users\\Vincent\\Code\\wa-api\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\Vincent\\Code\\wa-api\\node_modules\\axios\\lib\\adapters\\http.js:293:11)\n    at IncomingMessage.emit (node:events:538:35)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","uploadResult":{"debug_info":{"retriable":false,"type":"INVALID_MEDIA_TYPE","message":"Invalid media type"}},"msg":"Error in uploading to mmg.whatsapp.net "}
Error: Media upload failed on all hosts
    at C:\Users\Vincent\Code\wa-api\node_modules\@adiwajshing\baileys\lib\Utils\messages-media.js:467:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\Vincent\Code\wa-api\node_modules\@adiwajshing\baileys\lib\Utils\business.js:205:30
    at async Promise.all (index 0)
    at async Object.uploadingNecessaryImages (C:\Users\Vincent\Code\wa-api\node_modules\@adiwajshing\baileys\lib\Utils\business.js:190:21)
    at async Object.uploadingNecessaryImagesOfProduct (C:\Users\Vincent\Code\wa-api\node_modules\@adiwajshing\baileys\lib\Utils\business.js:181:34)
    at async Object.productCreate (C:\Users\Vincent\Code\wa-api\node_modules\@adiwajshing\baileys\lib\Socket\business.js:161:18)
    at async createProduct (file:///C:/Users/Vincent/Code/wa-api/controllers/instanceController.js:45:25) {
  data: null,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

```

**Comment by azudindaem** [comment]
have you try using .jpeg format? i have no problem retrieving catalog & product but never try create product from bailey

**Comment by azudindaem** [comment]
reproduction issue

```javascript
const product = await sessions.productCreate(
{
  name: 'Product Test',
  description: 'Baileys Product Test',
  price: 1000,
  currency: 'USD',
  isHidden: false,
  images: [
    {
      url: 'https://example.com/test.jpeg'
    }
  ]
}
)
```

Error Log

```
{"level":10,"time":1654568832450,"pid":13536,"hostname":"localhost","msgId":"11683.36775-8","fromMe":true,"frame":{"tag":"iq","attrs":{"type":"set","xmlns":"w:m","to":"@s.whatsapp.net","id":"11683.36775-8"},"content":[{"tag":"media_conn","attrs":{}}]},"msg":"communication"}
{"level":10,"time":1654568832692,"pid":13536,"hostname":"localhost","class":"ns","msg":"recv 1129 bytes, total recv 1129 bytes"}
{"level":10,"time":1654568832693,"pid":13536,"hostname":"localhost","class":"ns","msg":"11683.36775-8","msg":"recv frame"}
{"level":10,"time":1654568832693,"pid":13536,"hostname":"localhost","msgId":"11683.36775-8","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"result","id":"11683.36775-8"},"content":[{"tag":"media_conn","attrs":{"auth":"AWQAUPTG8TJ8uP3iMainNXISIaafFe5YM31XWkQcEV12GevHLxiZugNDPyk","ttl":"300","auth_ttl":"21600","max_buckets":"12"},"content":[{"tag":"host","attrs":{"hostname":"media-sin6-2.cdn.whatsapp.net","type":"primary","class":"pop","fallback_hostname":"media-hkt1-1.cdn.whatsapp.net","fallback_class":"pop","ip4":"157.240.13.54","ip6":"2a03:2880:f20c:2c6:face:b00c:0:167","fallback_ip4":"31.13.77.60","fallback_ip6":"2a03:2880:f25a:c8:face:b00c:0:167"},"content":[{"tag":"upload","attrs":{}},{"tag":"download","attrs":{},"content":[{"tag":"video","attrs":{}},{"tag":"image","attrs":{}},{"tag":"gif","attrs":{}},{"tag":"ptt","attrs":{}},{"tag":"audio","attrs":{}},{"tag":"document","attrs":{}},{"tag":"sticker","attrs":{}},{"tag":"ppic","attrs":{}},{"tag":"md-app-state","attrs":{}},{"tag":"md-msg-hist","attrs":{}},{"tag":"kyc-id","attrs":{}},{"tag":"thumbnail-image","attrs":{}},{"tag":"thumbnail-video","attrs":{}},{"tag":"thumbnail-gif","attrs":{}},{"tag":"thumbnail-document","attrs":{}},{"tag":"thumbnail-link","attrs":{}},{"tag":"biz-cover-photo","attrs":{}}]},{"tag":"download_buckets","attrs":{},"content":[{"tag":"102","attrs":{}},{"tag":"109","attrs":{}}]}]},{"tag":"host","attrs":{"hostname":"media-sin6-1.cdn.whatsapp.net","type":"primary","class":"pop","fallback_hostname":"media-hkt1-1.cdn.whatsapp.net","fallback_class":"pop","ip4":"157.240.7.54","ip6":"2a03:2880:f20c:c6:face:b00c:0:167","fallback_ip4":"31.13.77.60","fallback_ip6":"2a03:2880:f25a:c8:face:b00c:0:167"},"content":[{"tag":"download","attrs":{},"content":[{"tag":"video","attrs":{}},{"tag":"image","attrs":{}},{"tag":"gif","attrs":{}},{"tag":"ptt","attrs":{}},{"tag":"audio","attrs":{}},{"tag":"document","attrs":{}},{"tag":"sticker","attrs":{}},{"tag":"ppic","attrs":{}},{"tag":"md-app-state","attrs":{}},{"tag":"md-msg-hist","attrs":{}},{"tag":"kyc-id","attrs":{}},{"tag":"thumbnail-image","attrs":{}},{"tag":"thumbnail-video","attrs":{}},{"tag":"thumbnail-gif","attrs":{}},{"tag":"thumbnail-document","attrs":{}},{"tag":"thumbnail-link","attrs":{}},{"tag":"biz-cover-photo","attrs":{}}]},{"tag":"download_buckets","attrs":{},"content":[{"tag":"0","attrs":{}},{"tag":"105","attrs":{}},{"tag":"107","attrs":{}},{"tag":"111","attrs":{}}]}]},{"tag":"host","attrs":{"hostname":"media-sin6-4.cdn.whatsapp.net","type":"primary","class":"pop","fallback_hostname":"media-hkt1-1.cdn.whatsapp.net","fallback_class":"pop","ip4":"157.240.235.60","ip6":"2a03:2880:f20c:3c1:face:b00c:0:167","fallback_ip4":"31.13.77.60","fallback_ip6":"2a03:2880:f25a:c8:face:b00c:0:167"},"content":[{"tag":"upload","attrs":{}},{"tag":"download","attrs":{},"content":[{"tag":"video","attrs":{}},{"tag":"image","attrs":{}},{"tag":"gif","attrs":{}},{"tag":"ptt","attrs":{}},{"tag":"audio","attrs":{}},{"tag":"document","attrs":{}},{"tag":"sticker","attrs":{}},{"tag":"ppic","attrs":{}},{"tag":"md-app-state","attrs":{}},{"tag":"md-msg-hist","attrs":{}},{"tag":"kyc-id","attrs":{}},{"tag":"thumbnail-image","attrs":{}},{"tag":"thumbnail-video","attrs":{}},{"tag":"thumbnail-gif","attrs":{}},{"tag":"thumbnail-document","attrs":{}},{"tag":"thumbnail-link","attrs":{}},{"tag":"biz-cover-photo","attrs":{}}]},{"tag":"download_buckets","attrs":{},"content":[{"tag":"100","attrs":{}},{"tag":"101","attrs":{}},{"tag":"103","attrs":{}},{"tag":"108","attrs":{}}]}]},{"tag":"host","attrs":{"hostname":"media-sin6-3.cdn.whatsapp.net","type":"primary","class":"pop","fallback_hostname":"media-hkt1-1.cdn.whatsapp.net","fallback_class":"pop","ip4":"157.240.15.60","ip6":"2a03:2880:f20c:1c2:face:b00c:0:167","fallback_ip4":"31.13.77.60","fallback_ip6":"2a03:2880:f25a:c8:face:b00c:0:167"},"content":[{"tag":"upload","attrs":{}},{"tag":"download","attrs":{},"content":[{"tag":"video","attrs":{}},{"tag":"image","attrs":{}},{"tag":"gif","attrs":{}},{"tag":"ptt","attrs":{}},{"tag":"audio","attrs":{}},{"tag":"document","attrs":{}},{"tag":"sticker","attrs":{}},{"tag":"ppic","attrs":{}},{"tag":"md-app-state","attrs":{}},{"tag":"md-msg-hist","attrs":{}},{"tag":"kyc-id","attrs":{}},{"tag":"thumbnail-image","attrs":{}},{"tag":"thumbnail-video","attrs":{}},{"tag":"thumbnail-gif","attrs":{}},{"tag":"thumbnail-document","attrs":{}},{"tag":"thumbnail-link","attrs":{}},{"tag":"biz-cover-photo","attrs":{}}]},{"tag":"download_buckets","attrs":{},"content":[{"tag":"104","attrs":{}},{"tag":"106","attrs":{}},{"tag":"110","attrs":{}}]}]},{"tag":"host","attrs":{"hostname":"mmg.whatsapp.net","type":"fallback","class":"pop"}}]}]},"msg":"communication"}
{"level":20,"time":1654568832693,"pid":13536,"hostname":"localhost","msg":"fetched media conn"}
{"level":20,"time":1654568832694,"pid":13536,"hostname":"localhost","msg":"uploading to \"media-sin6-2.cdn.whatsapp.net\""}
{"level":10,"time":1654568833645,"pid":13536,"hostname":"localhost","msgId":"11683.36775-9","fromMe":true,"frame":{"tag":"iq","attrs":{"to":"@s.whatsapp.net","type":"set","xmlns":"w:biz:catalog","id":"11683.36775-9"},"content":[{"tag":"product_catalog_add","attrs":{"v":"1"},"content":[{"tag":"product","attrs":{"is_hidden":"false"},"content":[{"tag":"name","attrs":{},"content":{"type":"Buffer","data":[80,114,111,100,117,99,116,32,84,101,115,116]}},{"tag":"description","attrs":{},"content":{"type":"Buffer","data":[66,97,105,108,101,121,32,80,114,111,100,117,99,116,32,84,101,115,116]}},{"tag":"media","attrs":{},"content":[{"tag":"image","attrs":{},"content":[{"tag":"url","attrs":{},"content":{"type":"Buffer","data":[104,116,116,112,115,58,47,47,109,109,103,46,119,104,97,116,115,97,112,112,46,110,101,116,47,100,47,102,47,65,109,108,84,56,116,78,69,73,112,49,56,76,53,57,95,99,48,97,77,110,76,54,56,118,87,105,122,77,82,75,79,116,74,95,54,102,120,56,74,118,111,45,104,46,101,110,99]}}]}]},{"tag":"price","attrs":{},"content":{"type":"Buffer","data":[49,48,48,48]}},{"tag":"currency","attrs":{},"content":{"type":"Buffer","data":[85,83,68]}}]}]}]},"msg":"communication"}

Error: Timed Out
    at /home/webapps/test/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:174:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (/home/webapps/test/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:169:19)\n' +
      '    at waitForMessage (/home/webapps/test/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:99:61)\n' +
      '    at query (/home/webapps/test/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:122:22)\n' +
      '    at Object.productCreate (/home/webapps/test/node_modules/@adiwajshing/baileys/lib/Socket/business.js:163:30)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      '    at async /home/webapps/test/api.js:108:29'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}
```

**Comment by syifarahmat** [comment]
Chnage image: {url: to real server or local file}

**Comment by azudindaem** [comment]
> Chnage image: {url: to real server or local file}

examples are for reference only .. did you successfully use this function?

**Comment by AtefR** [comment]
> have you try using .jpeg format? i have no problem retrieving catalog & product but never try create product from bailey

Yes, sadly I get the same error,

> 

I don't know why you're getting a timeout instead of the error I got, but u might have some other issue.



> Chnage image: {url: to real server or local file}

This is a real URL to an image I found on google, Try to open it. the url works.

**Comment by as-shiddiq** [comment]
I get the same error, is it possible to work without an image?

**Comment by jrCleber** [comment]
+1

**Comment by IgorDePaula** [comment]
+1
