### ISSUE TITLE
[BUG] node:internal/errors:465     ErrorCaptureStackTrace(err);

### ISSUE THREAD

**Issue by jasmanX** [adiwajshing/Baileys#1715]
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at prepareSecretKey (node:internal/crypto/keys:580:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (E:\xampp\htdocs\wainstance\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (E:\xampp\htdocs\wainstance\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (E:\xampp\htdocs\wainstance\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:86:18)
    at WAConnection.emit (node:events:527:28)
    at WAConnection.emit (E:\xampp\htdocs\wainstance\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
}

installed modules @adiwajshing/baileys, express, request

My Code

const {  WAConnection,MessageType,Presence,MessageOptions,Mimetype, WALocationMessage,MessageLogLevel,WA_MESSAGE_STUB_TYPES,ReconnectMode,ProxyAgent,waChatKey,} = require('@adiwajshing/baileys')
var fs = require("fs");
var express = require('express');
const request = require('request')
 

var app = express();
var client = null;

var server = app.listen(3333, function () {
   var port = server.address().port
   console.log("http://localhost:%s", port) 
})
 
async function connectToWhatsApp (instancesid) {  
var SessionLogin = './'+instancesid+'.json';
client = new WAConnection()
    client.autoReconnect = true
	try { 
		client.loadAuthInfo (SessionLogin)
	}catch (error) { 
	}  
	
	await client.connect()  
	const creds = client.base64EncodedAuthInfo ()  
	fs.writeFileSync(SessionLogin, JSON.stringify(creds, null, '\t'))  
	 
    client.on ('message-new', async m => {
		console.log(m)
	})
	
	client.registerCallback(['action', null, 'battery'], json => {
        const batteryLevelStr = json[2][0][1].value
        const batterylevel = parseInt(batteryLevelStr)
        console.log('battery level: ' + batterylevel)
    })
	
    client.on('close', ({reason}) => {
        console.log ('oh no got disconnected: ' + reason + ', reconnecting: ') 
		  if (reason=='unknown') {
              fs.unlinkSync(SessionLogin)
        } 
    })
	
    return instancesid
}

app.get('/instances/:instancesid/connect', async (req, res) => { 
	instancesid = await connectToWhatsApp(req.params.instancesid) 
    res.send(instancesid+' connect'); 
})
 
app.get('/instances/:instancesid/close', async (req, res) => {
	instancesid = req.params.instancesid;  
	client.close()  // HOW TO DEFINE CLOSE SPECIFIC
	res.send(instancesid+' close'); 
})
  
app.get('/instances/:instancesid/state', async (req, res) => {
	instancesid = req.params.instancesid;  // HOW TO DEFINE STATE SPECIFIC
	res.send(instancesid+client.state); 
})

**Comment by AkirahX** [comment]
In the WhatsApp app, are you in the beta version of Whatsapp Web?

**Comment by jasmanX** [comment]
no its not beta, version 2.22.12.77

**Comment by AkirahX** [comment]
> no its not beta, version 2.22.12.77

You are using Baileys version 3.5.3, this version no longer works with the current version of Whatsapp, convert your system to version 4.1.0 or higher.
