### ISSUE TITLE
Memory leak detected

### ISSUE THREAD

**Issue by Zarinia** [adiwajshing/Baileys#1717]
```
WhatsApp-2  | Jun-09-2022 22:27:54 [server] error: Unhandled Rejection at: Promise
WhatsApp-2  | (node:628) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [File]. Use emitter.setMaxListeners() to increase limit
WhatsApp-2  |     at _addListener (node:events:601:17)
WhatsApp-2  |     at File.addListener (node:events:619:10)
WhatsApp-2  |     at File.once (node:events:663:8)
WhatsApp-2  |     at /usr/src/app/node_modules/winston/lib/winston/rejection-handler.js:220:19
WhatsApp-2  |     at /usr/src/app/node_modules/async/internal/withoutIndex.js:8:40
WhatsApp-2  |     at eachOfArrayLike (/usr/src/app/node_modules/async/eachOf.js:61:9)
WhatsApp-2  |     at eachOf (/usr/src/app/node_modules/async/eachOf.js:181:12)
WhatsApp-2  |     at awaitable (/usr/src/app/node_modules/async/internal/awaitify.js:13:28)
WhatsApp-2  |     at eachLimit (/usr/src/app/node_modules/async/forEach.js:125:31)
```

**Comment by HanzCEO** [comment]
From the Node's `events` docs, it is just a warn useful for debugging memory leaks.
You can disable the warn by using `ev.setMaxListener(n)` and n could be Infinity as you wish.

**Comment by Reyuki-san** [comment]
Thanks for the tips @HanzCEO ! but I am curious what causes the event to increase? will events like `on('qr', ...)` increase as the qr code changes?

**Comment by HanzCEO** [comment]
The error says MaxListenersExceededWarning so it can't be because of qr
event. Please refer to NodeJS documentation about this error.
