### ISSUE TITLE
[BUG] -  "msg": "url generation failed"

### ISSUE THREAD

**Issue by ratnokustiawan** [adiwajshing/Baileys#1719]
**Describe the bug**
When sending message with URL error occured
{
  "level": 40,
  "time": 1654825541740,
  "pid": 28,
  "hostname": "notif3-deployment-5b6b556974-sw5x8",
  "trace": "FetchError: uri requested responds with a redirect, redirect mode is set to error: https://google.com/\n    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1523:14)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at ClientRequest.req.emit (/usr/src/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:95:23)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)\n    at TLSSocket.socketOnData (_http_client.js:515:22)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)",
  "msg": "url generation failed"
}

**To Reproduce**
Send message with url on message

**Environment (please complete the following information):**
 - node:14.18-buster
 - docker container

**Comment by Islam-Mohammed-Younes** [comment]
confirmed 
I got the same warning


Environment
- OS: Linux 5.15
- Node: 16.15.1
- npm: 8.12.1

**Comment by azudindaem** [comment]
I believe this update will fixed this issue

https://github.com/adiwajshing/Baileys/commit/79518787b6c33fcf0e878e4acf855d03c8e9dc95

**Comment by Islam-Mohammed-Younes** [comment]
> I believe this update will fixed this issue
> 
> [7951878](https://github.com/adiwajshing/Baileys/commit/79518787b6c33fcf0e878e4acf855d03c8e9dc95)

already updated 
using 
`npm i github:@adiwajshing/baileys`

same issue

**Comment by azudindaem** [comment]
you did install link-preview-js?

**Comment by ratnokustiawan** [comment]
> you did install link-preview-js?

yes

**Comment by Islam-Mohammed-Younes** [comment]
> you did install link-preview-js?

thanks !

once i installed `link-preview-js` the warning does not show up  (but no link preview either i tried a youtube link)

is that mentioned in the documentation ?
or the warning message should be a little bit more clear

**Comment by azudindaem** [comment]
> `npm i github:@adiwajshing/baileys`

you should get a latest version
npm i github:@adiwajshing/baileys

**Comment by ratnokustiawan** [comment]
Still occured this error

{
  "level": 40,
  "time": 1655084085360,
  "pid": 9448,
  "hostname": "abc-deployment-6bd7cd8847-8xg4z",
  "trace": "FetchError: uri requested responds with a redirect, redirect mode is set to error: https://wa.me/62895395008000\n    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1523:14)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at ClientRequest.req.emit (/usr/src/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:95:23)\n    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)\n    at TLSSocket.socketOnData (_http_client.js:515:22)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)",
  "msg": "url generation failed"
}

**Comment by diazzaid** [comment]
> This issue is stale because it has been open 6 days with no activity. Remove the stale label or comment or this will be closed in 2 days

up

**Comment by gadhiamitul41** [comment]
still an issue

**Comment by deriknyvo** [comment]
I'm having the same error. Is there any way to not fetch the preview link when sending a link in a text message?

**Comment by arthur-es** [comment]
Same error showing here...
![image](https://user-images.githubusercontent.com/37699234/201742707-c42b97cb-3289-4f61-9cdf-fff3487edaf9.png)
