### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SamPandey001** [adiwajshing/Baileys#1754]
Getting This issue 

Connection... {
2022-06-17T11:29:25.583513+00:00 app[web.1]: 0|index  |   connection: 'close',
2022-06-17T11:29:25.583534+00:00 app[web.1]: 0|index  |   lastDisconnect: {
2022-06-17T11:29:25.583551+00:00 app[web.1]: 0|index  |     error: Error: Stream Errored (xml-not-well-formed)
2022-06-17T11:29:25.583580+00:00 app[web.1]: 0|index  |         at WebSocket.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:419:13)
2022-06-17T11:29:25.583601+00:00 app[web.1]: 0|index  |         at WebSocket.emit (node:events:527:28)
2022-06-17T11:29:25.583633+00:00 app[web.1]: 0|index  |         at /app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:219:35
2022-06-17T11:29:25.583647+00:00 app[web.1]: 0|index  |         at Object.decodeFrame (/app/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)
2022-06-17T11:29:25.583688+00:00 app[web.1]: 0|index  |         at WebSocket.onMessageRecieved (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:195:15)
2022-06-17T11:29:25.583722+00:00 app[web.1]: 0|index  |         at WebSocket.emit (node:events:527:28)
2022-06-17T11:29:25.583749+00:00 app[web.1]: 0|index  |         at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1169:20)
2022-06-17T11:29:25.583784+00:00 app[web.1]: 0|index  |         at Receiver.emit (node:events:527:28)
2022-06-17T11:29:25.583823+00:00 app[web.1]: 0|index  |         at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:513:14)
2022-06-17T11:29:25.583864+00:00 app[web.1]: 0|index  |         at Receiver.getData (/app/node_modules/ws/lib/receiver.js:446:17)
2022-06-17T11:29:25.583902+00:00 app[web.1]: 0|index  |         at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:148:22)
2022-06-17T11:29:25.583942+00:00 app[web.1]: 0|index  |         at Receiver._write (/app/node_modules/ws/lib/receiver.js:83:10)
2022-06-17T11:29:25.583967+00:00 app[web.1]: 0|index  |         at writeOrBuffer (node:internal/streams/writable:389:12)
2022-06-17T11:29:25.583980+00:00 app[web.1]: 0|index  |         at _write (node:internal/streams/writable:330:10)
2022-06-17T11:29:25.584013+00:00 app[web.1]: 0|index  |         at Receiver.Writable.write (node:internal/streams/writable:334:10)
2022-06-17T11:29:25.584033+00:00 app[web.1]: 0|index  |         at TLSSocket.socketOnData (/app/node_modules/ws/lib/websocket.js:1263:35) {
2022-06-17T11:29:25.584051+00:00 app[web.1]: 0|index  |       data: [Object],
2022-06-17T11:29:25.584079+00:00 app[web.1]: 0|index  |       isBoom: true,
2022-06-17T11:29:25.584101+00:00 app[web.1]: 0|index  |       isServer: true,
2022-06-17T11:29:25.584132+00:00 app[web.1]: 0|index  |       output: [Object]
2022-06-17T11:29:25.584142+00:00 app[web.1]: 0|index  |     },
2022-06-17T11:29:25.584163+00:00 app[web.1]: 0|index  |     date: 2022-06-17T11:29:25.570Z
2022-06-17T11:29:25.584184+00:00 app[web.1]: 0|index  |   }
2022-06-17T11:29:25.584215+00:00 app[web.1]: 0|index  | }
2022-06-17T11:29:25.584558+00:00 app[web.1]: 0|index  | Connection... {
2022-06-17T11:29:25.584580+00:00 app[web.1]: 0|index  |   connection: 'connecting',
2022-06-17T11:29:25.584605+00:00 app[web.1]: 0|index  |   receivedPendingNotifications: false,
2022-06-17T11:29:25.584626+00:00 app[web.1]: 0|index  |   qr: undefined
2022-06-17T11:29:25.584655+00:00 app[web.1]: 0|index  | }
2022-06-17T11:29:25.991707+00:00 app[web.1]: 0|index  | Connection... { isOnline: true }
2022-06-17T11:29:25.992012+00:00 app[web.1]: 0|index  | Connection... { connection: 'open' }

**Comment by AkirahX** [comment]
This occurs in groups with a considerable amount of members, install the version available from NPM to temporarily solve this.

**Comment by SamPandey001** [comment]
> This occurs in groups with a considerable amount of members, install the version available from NPM to temporarily solve this.

how?
I did but not working

**Comment by AkirahX** [comment]
> > This occurs in groups with a considerable amount of members, install the version available from NPM to temporarily solve this.
> 
> how? I did but not working

Verify on your package.json if Baileys version is 4.1.0
