### ISSUE TITLE
Error while adding users to the group

### ISSUE THREAD

**Issue by q-e** [adiwajshing/Baileys#176]
Getting below error while trying to add users using groupAdd method.

BaileysError: Unexpected status in 'action': Bad Request(400)
    at WAConnection.query (/Users/Baileys/src/WAConnection/0.Base.ts:251:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at WAConnection.setQuery (/Users/Baileys/src/WAConnection/0.Base.ts:224:24)
    at WAConnection.groupQuery (/Users/Baileys/src/WAConnection/8.Groups.ts:21:24)

It was working earlier but getting error during the last 24hrs.

**Comment by adiwajshing** [comment]
You may want to check the permissions of the group, if you’re not an admin, this request will fail

**Comment by q-e** [comment]
The user who created the group is trying to add additional users.

**Comment by adiwajshing** [comment]
Sure that the group hasn't reached its limit of 256 users?

**Comment by q-e** [comment]
Looks like due to creating groups right after activating the number, WhatsApp throws an error
