### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Zarinia** [adiwajshing/Baileys#1760]
```
Failed to decrypt message with any known session...
Session error:MessageCounterError: Key used already or never filled MessageCounterError: Key used already or never filled
at SessionCipher.doDecryptWhisperMessage (/usr/src/app/node_modules/libsignal/src/session_cipher.js:236:19)
at SessionCipher.decryptWithSessions (/usr/src/app/node_modules/libsignal/src/session_cipher.js:147:40)
at 989054898540.0 [as awaitable] (/usr/src/app/node_modules/libsignal/src/session_cipher.js:171:39)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async _asyncQueueExecutor (/usr/src/app/node_modules/libsignal/src/queue_job.js:20:29)
```
What is this error meaning?

**Comment by anandsork** [comment]
If I invoke
setTimeout(async() => {
      try {
         await this.instance.sock.resyncMainAppState();
       } catch (e) {
           console.log(e)
       }
}, 2000);

After socket Creation.. it seems to resolve the issue.. 
Now sure this is a right approach.
