### ISSUE TITLE
[BUG] package.json

### ISSUE THREAD

**Issue by FongsiDev** [adiwajshing/Baileys#1766]
log;
```
internal/modules/cjs/loader.js:329
      throw err;
      ^

Error: Cannot find module '/home/runner/games-wabot/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/games-wabot/main.js:4:39)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/runner/games-wabot/node_modules/@adiwajshing/baileys/package.json',
  requestPath: '@adiwajshing/baileys'
}
Exited with code: 1
```

**Comment by SamPandey001** [comment]
please send complete log

**Comment by Iucasmaia** [comment]
this isn't a bug related to baileys...

**Comment by fadiinho** [comment]
This is happening to me when I try to install the github version with `yarn add github:adiwajshing/baileys` (when using npm it works as expected).
It happens with yarn classic and the latest version. It also happens when using zero-install or `nodeLinker: node-modules` in .yarnrc.yml.
When I install the github version it doesn't contains the lib folder for some reason.
![image](https://user-images.githubusercontent.com/94945604/175118867-dfc21d05-835b-4357-9dd0-056e793a3704.png)
