### ISSUE TITLE
[BUG] Session error:MessageCounterError

### ISSUE THREAD

**Issue by ratnokustiawan** [adiwajshing/Baileys#1768]
**Describe the bug**
Sudenly got this error
Session error:MessageCounterError: Key used already or never filled MessageCounterError: Key used already or never filled
    at SessionCipher.doDecryptWhisperMessage (/usr/src/app/node_modules/libsignal/src/session_cipher.js:236:19)
    at SessionCipher.decryptWithSessions (/usr/src/app/node_modules/libsignal/src/session_cipher.js:147:40)
    at Object.6285851303487.0 [as awaitable] (/usr/src/app/node_modules/libsignal/src/session_cipher.js:171:39)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async _asyncQueueExecutor (/usr/src/app/node_modules/libsignal/src/queue_job.js:20:29)

**To Reproduce**
Use send more than 1000 message

**Environment (please complete the following information):**
 - Is this on a server? kubernetes
 - Do you have multiple clients on the same IP? yes
 - Are you using a proxy? no

**Comment by PhillRoyle** [comment]
me too :-(

**Comment by anandsork** [comment]
If I invoke
setTimeout(async() => {
      try {
         await this.instance.sock.resyncMainAppState();
       } catch (e) {
           console.log(e)
       }
}, 2000);

After socket Creation.. it seems to resolve the issue.. 
Now sure this is a right approach.
