### ISSUE TITLE
[BUG] Cannot set properties of undefined (setting 'unarchiveChats')

### ISSUE THREAD

**Issue by Leocardoso94** [adiwajshing/Baileys#1769]
**Describe the bug**

`{"level":30,"time":"2022-06-21T14:17:25.431Z","pid":8864,"hostname":"instance-1","class":"baileys","name":"regular_low","error":"TypeError: Cannot set properties of undefined (setting 'unarchiveChats')\n    at processSyncAction (/home/luna/node_modules/@adiwajshing/baileys/lib/Utils/chat-utils.js:564:40)\n    at onMutation (/home/luna/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:207:47)\n    at decodeSyncdMutations (/home/luna/node_modules/@adiwajshing/baileys/lib/Utils/chat-utils.js:205:9)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async decodeSyncdPatch (/home/luna/node_modules/@adiwajshing/baileys/lib/Utils/chat-utils.js:226:20)\n    at async decodePatches (/home/luna/node_modules/@adiwajshing/baileys/lib/Utils/chat-utils.js:332:30)\n    at async /home/luna/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:278:71\n    at async Object.transaction (/home/luna/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:82:21)\n    at async resyncAppState (/home/luna/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:216:9)","msg":"failed to sync state from version, removing and trying from scratch"}`

**To Reproduce**
When someone archiving a chat on WhatsApp, the baileys session report this error on console  

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - What do your `connectOptions` look like? 
 
 ```
const sock = makeWASocket({
      auth: state,
      printQRInTerminal: true,
      version,
      msgRetryCounterMap,
      getMessage: async (key) => {
        return (
          getMessageFromStore(key.remoteJid, key.id)?.message || {
            conversation: "Please command again",
          }
        );
      },
    });
```

 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Comment by Leocardoso94** [comment]
for some reason accountSettings is undefined here
https://github.com/adiwajshing/Baileys/blob/master/src/Utils/chat-utils.ts#L683
