### ISSUE TITLE
Unexpected server response: 403 [BUG]

### ISSUE THREAD

**Issue by JoseHM8A** [adiwajshing/Baileys#1773]
```
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 403
    at ClientRequest.<anonymous> (C:\Users\Darker\Desktop\MultiBot\node_modules\ws\lib\websocket.js:852:7)
    at ClientRequest.emit (node:events:526:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:618:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:482:22)
    at TLSSocket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on WebSocket instance at:
    at abortHandshake (C:\Users\Darker\Desktop\MultiBot\node_modules\ws\lib\websocket.js:1022:15)
    at ClientRequest.<anonymous> (C:\Users\Darker\Desktop\MultiBot\node_modules\ws\lib\websocket.js:852:7)
    [... lines matching original stack trace ...]
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
```
Occurs when i start my bot

```js
 const client = makeWASocket({
            printQRInTerminal: true,
            browser: ['MD Baileys', "Safari", "3.0"],
            logger: pino({ level: "fatal" }),
            auth: state,
            emitOwnEvents: true
        })
        client.ws.setMaxListeners(Infinity)
        client.ev.setMaxListeners(Infinity)
```

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - Do you have multiple clients on the same IP? Yes
 - Are you using a proxy? No

**Comment by SrFortes** [comment]
Eu aconselho fortemente NÃO usar o código:

process.setMaxListeners(0);
O aviso não existe sem razão. Na maioria das vezes, é porque há um erro oculto no seu código. A remoção do limite remove o aviso, mas não sua causa, e evita que você seja avisado sobre uma fonte de vazamento de recursos.

Se você atingir o limite por um motivo legítimo, coloque um valor razoável na função (o padrão é 10).

Além disso, para alterar o padrão, não é necessário mexer no protótipo EventEmitter. você pode definir o valor do atributo defaultMaxListeners assim:

require('events').EventEmitter.defaultMaxListeners = 15;
