### ISSUE TITLE
connection closed due to  Error: Stream Errored (ack)

### ISSUE THREAD

**Issue by tiagomatrixd** [adiwajshing/Baileys#1782]
connection closed due to  Error: Stream Errored (ack)
     at WebSocket.<anonymous> (/home/masterbotMD/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:420:13)
     at WebSocket.emit (node:events:390:28)
     at /home/masterbotMD/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:220:35
     at Object.decodeFrame (/home/masterbotMD/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)
     at WebSocket.onMessageRecieved (/home/masterbotMD/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:196:15)
     at WebSocket.emit (node:events:390:28)
     at Receiver.receiverOnMessage (/home/masterbotMD/node_modules/@adiwajshing/baileys/node_modules/ws/lib/websocket.js:1169:20)
     at Receiver.emit (node:events:390:28)
     at Receiver.dataMessage (/home/masterbotMD/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:513:14)
     at Receiver.getData (/home/masterbotMD/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:446:17) {
   data: { tag: 'stream:error', attrs: {}, content: [ [Object] ] },
   isBoom: true,
   isServer: true,
   output: {
     statusCode: 500,
     payload: {
       statusCode: 500,
       error: 'Internal Server Error',
       message: 'An internal server error occurred'
     },
     headers: {}
   }
 } , reconnecting  true
 
 after a few time connected happens this error

**Comment by mrhb6006** [comment]
exactly same eissue

**Comment by biguitarman** [comment]
X3, same error!!
