### ISSUE TITLE
After Connected and when call sock.onWhatsApp(number)  throw this error  Error: Connection Closed

### ISSUE THREAD

**Issue by vinayakvasu** [adiwajshing/Baileys#1792]
```
(node:18236) UnhandledPromiseRejectionWarning: Error: Connection Closed
    at sendRawMessage (/root/whatsapp-production/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:48:19)
    at sendNode (/root/whatsapp-production/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:59:16)
    at query (/root/whatsapp-production/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:15)
    at interactiveQuery (/root/whatsapp-production/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:24:30)
    at Object.onWhatsApp (/root/whatsapp-production/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:62:31)
    at /root/whatsapp-production/whatsapp-api-7777.js:510:43
    at Layer.handle [as handle_request] (/root/whatsapp-production/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/whatsapp-production/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/root/whatsapp-production/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/root/whatsapp-production/node_modules/express/lib/router/layer.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by phaticusthiccy** [comment]
Can you post a code sample that referenced `at /root/whatsapp-production/whatsapp-api-7777.js:510:43`

**Comment by riskihajar** [comment]
same here, and often
```
const { phone } = req.body;
const jid = phoneNumberFormatter(phone);
const [result] = await sock.onWhatsApp(jid);
const contact = sock.store?.contacts[jid] || null;
const name = contact?.name || contact?.notify || null;

return res.send({
  phone,
  result,
  name,
  success: result?.exists || false,
});
```

logger
```
{
    "data": null,
    "isBoom": true,
    "isServer": false,
    "output": {
        "statusCode": 428,
        "payload": {
            "statusCode": 428,
            "error": "Precondition Required",
            "message": "Connection Closed"
        },
        "headers": []
    }
}
```
