### ISSUE TITLE
Error: not-authorized[BUG]

### ISSUE THREAD

**Issue by KiZakiXD** [adiwajshing/Baileys#1808]
Error: not-authorized
    at assertNodeErrorFree (/storage/emulated/0/cican2/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56:15)
    at Object.query (/storage/emulated/0/cican2/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:126:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async zaki (/storage/emulated/0/cican2/zaki.js:1408:15) {
  data: 401,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

**Comment by phaticusthiccy** [comment]
Can you share a code from 
`at async zaki (/storage/emulated/0/cican2/zaki.js:1408:15)`
