### ISSUE TITLE
TypeError: text.match is not a function

### ISSUE THREAD

**Issue by officialdittaz** [adiwajshing/Baileys#1809]
/home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:34
    const matchedUrls = text.match(Defaults_1.URL_REGEX);
                             ^

TypeError: text.match is not a function
    at generateLinkPreviewIfRequired (/home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:34:30)
    at generateWAMessageContent (/home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:197:71)
    at generateWAMessage (/home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:394:102)
    at Object.sendMessage (/home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:511:69)
    at setReply (/home/runner/EXTREAM-BOTZ/message/msg.js:308:6)
    at eval (eval at module.exports (/home/runner/EXTREAM-BOTZ/message/msg.js:4634:20), <anonymous>:1:1)
    at module.exports (/home/runner/EXTREAM-BOTZ/message/msg.js:4634:20)
exit status 1

**Comment by shoukosagiri-poi** [comment]
me, too
