### ISSUE TITLE
[BUG] Timed Out Error

### ISSUE THREAD

**Issue by sorkab** [adiwajshing/Baileys#1813]
```
Error: Timed Out
0|index  |     at /root/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:174:32 {
0|index  |   data: {
0|index  |     stack: 'Error\n' +
0|index  |       '    at promiseTimeout (/root/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:169:19)\n' +
0|index  |       '    at waitForMessage (/root/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:99:61)\n' +
0|index  |       '    at query (/root/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:122:22)\n' +
0|index  |       '    at sendPassiveIq (/root/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:304:37)\n' +
0|index  |       '    at WebSocket.<anonymous> (/root/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:405:15)\n' +
0|index  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
0|index  |   },
0|index  |   isBoom: true,
0|index  |   isServer: false,
0|index  |   output: {
0|index  |     statusCode: 408,
0|index  |     payload: {
0|index  |       statusCode: 408,
0|index  |       error: 'Request Time-out',
0|index  |       message: 'Timed Out'
0|index  |     },
0|index  |     headers: {}
0|index  |   }
0|index  | }
```

Have Any Solution ?

**Comment by jeffersonveloso** [comment]
Same problem here.

**Comment by SrFortes** [comment]
same problem here too

**Comment by pe77** [comment]
Same here...
