### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by pumpa0** [adiwajshing/Baileys#1814]
TypeError: Cannot read properties of undefined (reading '0')
    at sendReceipt (/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:76:31)
    at Object.sendReadReceipt (/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:116:16)

**Comment by morganzysman** [comment]
Same Issue here
