### ISSUE TITLE
[BUG] Error: Server responded with 503

### ISSUE THREAD

**Issue by officialdittaz** [adiwajshing/Baileys#1839]
Error: Server responded with 503
    at /home/runner/EXTREAM-BOTZ/node_modules/canvas/lib/image.js:56:28
    at /home/runner/EXTREAM-BOTZ/node_modules/simple-get/index.js:97:7
    at IncomingMessage.<anonymous> (/home/runner/EXTREAM-BOTZ/node_modules/simple-concat/index.js:8:13)
    at Object.onceWrapper (node:events:513:28)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1348:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by FatihArridho** [comment]
Ngakak

**Comment by BochilGaming** [comment]
the error you are getting has nothing to do with this library, the error is an error in the code/api you are using. so please close this issue

**Comment by officialdittaz** [comment]
🗿

**Comment by radhin123** [comment]
lah Awok2
