### ISSUE TITLE
[BUG] Error: Connection Closed

### ISSUE THREAD

**Issue by officialdittaz** [adiwajshing/Baileys#1856]
Error: Connection Closed
    at sendRawMessage (/home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:48:19)
    at sendNode (/home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:59:16)
    at query (/home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:15)
    at getUSyncDevices (/home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:178:30)
    at /home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:344:53
    at Object.transaction (/home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:86:27)
    at relayMessage (/home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:274:30)
    at Object.sendMessage (/home/runner/EXTREAM-BOTZ/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:525:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}
1006

**Comment by officialdittaz** [comment]
how to fix it

**Comment by Guilherme-j10** [comment]
the same with me

**Comment by russocorp** [comment]
connection closing and dont trigger "connection.update" event :/

**Comment by Guilherme-j10** [comment]
The event name change ?

**Comment by Jorsis** [comment]
none?

**Comment by luispimenta** [comment]
I'm having the same problem

**Comment by Jorsis** [comment]
same

**Comment by officialdittaz** [comment]
Im

**Comment by muzafferkadir** [comment]
@officialdittaz did you find any solution?

**Comment by marlonlimaserra** [comment]
same

**Comment by truemoroz** [comment]
+1

**Comment by SarkarJobs** [comment]
+1
