### ISSUE TITLE
Trying to forward messages from telegram

### ISSUE THREAD

**Issue by LZNOXP** [adiwajshing/Baileys#1887]
I'm trying to forward messages from telegram to whatsapp, i've setup telegram client (GramJS) and use EventEmitter to pass data around, the problem is sendMessage mostly/always crash (log below) if it's called from EventEmitter object.
i've faced similiar issue while trying to implement some kind of message alert at random time, now it's working fine (or is it?) i don't know why
is there something i need to prepare before sending a message?

makeWaSocket options:
```
const sock = makeWASocket({
		version,
		printQRInTerminal: true,
		auth: state,
		msgRetryCounterMap,
                //please tell me if this is not the right way to use it
		keepAliveIntervalMs: 1000 * 60 * 10 * 3,
		// implement to handle retries
		getMessage: async () => {
			return {
				conversation: "hello",
			};
		},
	});
```
code in telegram client:
```
const handleMessage = async (evt: NewMessageEvent) => {
	try {
		const msg = evt.message;
		tgEvent.emit("msgFromTg", "***@g.us", msg.text);
	} catch (error) {
		console.log("error in handleMessage", error);
	}
};

```
code inside startSock function:
```
tgEvent.on("msgFromTg", async (jid, msg) => {
		console.log("msgFromTg", msg);

		await sock.sendMessage(jid, { text: msg });
	});
```

log
```
 | /home/*****/project/waapi/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:48
0|mywaapi  |             throw new boom_1.Boom('Connection Closed', { statusCode: Types_1.DisconnectReason.connectionClosed });
0|mywaapi  |                   ^
0|mywaapi  | Error: Connection Closed
0|mywaapi  |     at sendRawMessage (/home/*****/project/waapi/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:48:19)
0|mywaapi  |     at sendNode (/home/*****/project/waapi/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:59:16)
0|mywaapi  |     at query (/home/*****/project/waapi/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:15)
0|mywaapi  |     at groupQuery (/home/*****/project/waapi/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:12:55)
0|mywaapi  |     at groupMetadata (/home/*****/project/waapi/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:22:30)
0|mywaapi  |     at /home/*****/project/waapi/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:284:47
0|mywaapi  |     at /home/*****/project/waapi/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:287:23
0|mywaapi  |     at async Object.transaction (/home/*****/project/waapi/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:86:21)
0|mywaapi  |     at async relayMessage (/home/*****/project/waapi/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:274:9)
0|mywaapi  |     at async Object.sendMessage (/home/*****/project/waapi/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:525:17) {
0|mywaapi  |   data: null,
0|mywaapi  |   isBoom: true,
0|mywaapi  |   isServer: false,
0|mywaapi  |   output: {
0|mywaapi  |     statusCode: 428,
0|mywaapi  |     payload: {
0|mywaapi  |       statusCode: 428,
0|mywaapi  |       error: 'Precondition Required',
0|mywaapi  |       message: 'Connection Closed'
0|mywaapi  |     },
0|mywaapi  |     headers: {}
0|mywaapi  |   }
0|mywaapi  | }
```

**Comment by LZNOXP** [comment]
> keepAliveIntervalMs: 1000 * 60 * 10 * 3

okay, turns out my keepAliveIntervalMs is to long, i turn it down by 1 minute & now it's working fine. i hope that's the case
