### ISSUE TITLE
getting issue while trying to save auth in postgres.

### ISSUE THREAD

**Issue by akm-akm** [adiwajshing/Baileys#1925]
error: invalid byte sequence for encoding "UTF8": 0xf9
    at Parser.parseErrorMessage (/home/akm/code/akm-whatsapp-bot/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/akm/code/akm-whatsapp-bot/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/akm/code/akm-whatsapp-bot/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/akm/code/akm-whatsapp-bot/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 147,
  severity: 'ERROR',
  code: '22021',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'unnamed portal parameter $14',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'mbutils.c',
  line: '1665',
  routine: 'report_invalid_encoding'
}

**Comment by akm-akm** [comment]
![image](https://user-images.githubusercontent.com/67242659/179736687-83899b0c-6dc9-4720-b216-ca829f545961.png)
