### ISSUE TITLE
restarts every time i try to send message to one specific groups with old id.

### ISSUE THREAD

**Issue by akm-akm** [adiwajshing/Baileys#1932]
![image](https://user-images.githubusercontent.com/67242659/179975478-3255907d-355a-4e9f-a063-94be31a98e21.png)

**Comment by akm-akm** [comment]
file:///home/akm/Pictures/Screenshots/Screenshot%20from%202022-07-20%2017-23-08.png

**Comment by akm-akm** [comment]
![Screenshot from 2022-07-20 17-23-08](https://user-images.githubusercontent.com/67242659/180019551-11f7c21d-2aef-4946-bcec-bbae452a98e7.png)

**Comment by akm-akm** [comment]
Error: Stream Errored (xml-not-well-formed)
    at WebSocket.<anonymous> (/home/akm/code/akm-whatsapp-bot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:419:13)
    at WebSocket.emit (node:events:527:28)
    at /home/akm/code/akm-whatsapp-bot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:219:35
    at Object.decodeFrame (/home/akm/code/akm-whatsapp-bot/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)
    at WebSocket.onMessageRecieved (/home/akm/code/akm-whatsapp-bot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:195:15)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/home/akm/code/akm-whatsapp-bot/node_modules/@adiwajshing/baileys/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (/home/akm/code/akm-whatsapp-bot/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:513:14)
    at Receiver.getData (/home/akm/code/akm-whatsapp-bot/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:446:17) {
  data: { tag: 'stream:error', attrs: {}, content: [ [Object] ] },
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

**Comment by fadiinho** [comment]
It's fixed in the new version 4.3.0.

**Comment by akm-akm** [comment]
> It's fixed in the new version 4.3.0, try upgrading Baileys.

How can I install new version using npm

**Comment by ztfcode** [comment]
> > Sudah diperbaiki di versi baru 4.3.0, coba tingkatkan Baileys.
> 
> Bagaimana saya bisa menginstal versi baru menggunakan npm

base this dosc we are sugested to using yarn

**Comment by fadiinho** [comment]
If you're using npm: `npm update @adiwajshing/baileys`

**Comment by fadiinho** [comment]
> > It's fixed in the new version 4.3.0, try upgrading Baileys.
> 
> How can I install new version using npm

If you're using npm: `npm update @adiwajshing/baileys`
Or if you're using yarn: `yarn upgrade @adiwajshing/baileys@4.3.0`
