### ISSUE TITLE
Cannot Connected to whatsapp [BUG]

### ISSUE THREAD

**Issue by Xnuvers007** [adiwajshing/Baileys#1939]
INFO [2022-07-21 09:33:23.646 +0000] (6044): validated connection successfully
    class: "Baileys"
INFO [2022-07-21 09:33:23.657 +0000] (6044): opened connection to WhatsApp Web
    class: "Baileys"
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:86:18)
    at WAConnection.emit (node:events:526:28)
    at WAConnection.emit (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:87:18)
    at WAConnection.emit (node:events:526:28)
    at WAConnection.emit (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:88:18)
    at WAConnection.emit (node:events:526:28)
    at WAConnection.emit (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:89:18)
    at WAConnection.emit (node:events:526:28)
    at WAConnection.emit (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:90:18)
    at WAConnection.emit (node:events:526:28)
    at WAConnection.emit (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:91:18)
    at WAConnection.emit (node:events:526:28)
    at WAConnection.emit (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
INFO [2022-07-21 09:33:23.679 +0000] (6044): closed connection, reason close, reconnecting in a few seconds...
    class: "Baileys"
INFO [2022-07-21 09:33:28.075 +0000] (6044): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"

**Comment by ztfcode** [comment]
May i see your code?

**Comment by Xnuvers007** [comment]
> May i see your code?

I just want to use it as a bot
And I cloned github on https://github.com/Nurutomo/wabot-aq

**Comment by ztfcode** [comment]
if you still to using this source maybe you can try https://github.com/Aiinne/Aine-MDi it same but have small change
If you have problem again you can reply this 
I suggest you to using yarn not npm
