### ISSUE TITLE
[BUG] Error 500 at updateProfilePicture and other actions

### ISSUE THREAD

**Issue by victorkelvin** [adiwajshing/Baileys#1977]
I'm getting this error when trying to change profile picture, and a similar error in another actions like sendMessage sometimes:

```
Error: not-acceptable
    at assertNodeErrorFree (D:\_projects\launchzapp-js\node_modules\@adiwajshing\baileys\lib\WABinary\generic-utils.js:56:15)
    at query (D:\_projects\launchzapp-js\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:127:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.updateProfilePicture (D:\_projects\launchzapp-js\node_modules\@adiwajshing\baileys\lib\Socket\chats.js:129:9)
    at async changePicture (D:\_projects\launchzapp-js\main.js:390:7) {
  data: 406,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}
```
My socket config is below:

```
  const sock = makeWASocket({
    version,
    logger: P({ level: 'silent', stream: 'store' }),
    auth: state,
    // browser: ['LaunchZAPP', 'Chrome', '4.0.0'],
    browser: ['Windows', 'Chrome', '10.15.7'],
    defaultQueryTimeoutMs: 20000,
    getMessage: async key => {
      return {
        conversation: key
      }
    }
  });
 ```

**Comment by sahiljain379** [comment]
Hi @victorkelvin I am facing same issue, did you find any solution to this? 

If you guys can help, tagging you for assistance on this issue. @BlackAmda
