### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by AzRyCb** [adiwajshing/Baileys#2032]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - cmd
 - What do your `connectOptions` look like? 
 - const connectionOptions = {
  logger: P({ level: 'silent'}),
  printQRInTerminal: true,
  auth: state,
  //version: [2, 2204, 13],
  //browser: ['AzBoTz-MD', 'IOS', '4.1.0'],
  browser: Browsers.macOS('Desktop'),
  syncFullHistory: true
}
 - Do you have multiple clients on the same IP?
 - i dont knw
 - Are you using a proxy?
no

error this for templatemessage
TypeError: Cannot read properties of undefined (reading 'match')
    at extractUrlFromText (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:40:67)
    at generateLinkPreviewIfRequired (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:44:48)
    at generateWAMessageContent (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:209:71)
    at generateWAMessage (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:420:102)
    at Object.sendMessage (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:504:69)
    at conn.sendButton (C:\Bot\azbotzd\lib\simple.js:724:14) unhandledRejection

**Comment by BlackAmda** [comment]
What is this error?

`TypeError: Cannot read properties of undefined (reading 'match')
    at extractUrlFromText (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:40:59)
    at generateLinkPreviewIfRequired (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:44:48)
    at generateWAMessageContent (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:212:71)
    at generateWAMessage (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:433:102)
    at Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:500:69)`
