### ISSUE TITLE
downloadMediaMessage Failed to download media [TypeError]

### ISSUE THREAD

**Issue by AxeemHaider** [adiwajshing/Baileys#2041]
**Describe the bug**
Suddenly `downloadMediaMessage` stop working and I'm getting TypeError
```
TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at new NodeError (node:internal/errors:372:5)
    at Function.from (node:buffer:323:9)
    at hkdf (/home/haider/codeplace/project/was/node_modules/.pnpm/@adiwajshing+baileys@4.3.0_6k2mrzwh25fmbv5ioxilaevhxe/node_modules/@adiwajshing/baileys/lib/Utils/crypto.js:131:73)
    at getMediaKeys (/home/haider/codeplace/project/was/node_modules/.pnpm/@adiwajshing+baileys@4.3.0_6k2mrzwh25fmbv5ioxilaevhxe/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:81:48)
    at downloadContentFromMessage (/home/haider/codeplace/project/was/node_modules/.pnpm/@adiwajshing+baileys@4.3.0_6k2mrzwh25fmbv5ioxilaevhxe/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:324:18)
    at downloadMsg (/home/haider/codeplace/project/was/node_modules/.pnpm/@adiwajshing+baileys@4.3.0_6k2mrzwh25fmbv5ioxilaevhxe/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:553:78)
    at downloadMediaMessage (/home/haider/codeplace/project/was/node_modules/.pnpm/@adiwajshing+baileys@4.3.0_6k2mrzwh25fmbv5ioxilaevhxe/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:524:30)
    at ClientEvents.<anonymous> (/home/haider/codeplace/project/was/src/websocket/ClientEvents.socket.ts:210:75)
    at Generator.next (<anonymous>)
    at /home/haider/codeplace/project/was/src/websocket/ClientEvents.socket.ts:8:71
[ERROR] 06:45:28 TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
```

**To Reproduce**
1. Try to download any media using code that provided in [Example - Download message media](https://github.com/adiwajshing/Baileys#downloading-media-messages)

**Expected behavior**
It should download the media as it was working before

**Environment (please complete the following information):**
 - Is this on a server? YES
 - What do your `connectOptions` look like? DEFAULT
 - Do you have multiple clients on the same IP? NO
 - Are you using a proxy? NO

**Comment by makanSukros** [comment]
+1 for me
