### ISSUE TITLE
[BUG] Manipulate profile photo when unauthorized

### ISSUE THREAD

**Issue by barkerpedro** [adiwajshing/Baileys#210]
**Describe the bug**
Hello, in my project I create an object and in it I get the 'Profile Picture' of the contact when I receive a message, however when the contact does not authorize showing the photo, Baileys informs me of an error. How can I handle this error?

**To Reproduce**
```node
const { WAConnection, ReconnectMode } = require("@adiwajshing/baileys");
const request = require('request');
const conn = new WAConnection();
const session = 'session.json';

async function connectToWhatsApp() {
  conn.connectOptions = {
    waitOnlyForLastMessage: false,
    waitForChats: true,
    maxRetries: Infinity,
    phoneResponseTime: 10_000,
    alwaysUseTakeover: true,
  }

  conn.autoReconnect = ReconnectMode.onConnectionLost;
  conn.logger.level = 'debug';

  conn.on('credentials-updated', () => {
    const authInfo = conn.base64EncodedAuthInfo();
    fs.writeFileSync(session, JSON.stringify(authInfo, null, '\t'));
  });

  (await fs.existsSync(session)) && (await conn.loadAuthInfo(session));
  await conn.connect({ timeoutMs: 30_000 }, false);
}
connectToWhatsApp().catch((err) => console.log("Error: " + err));

conn.on("message-new", async mNew => {

  var objReceived = { messages: [] };

  objReceived.messages.push({
    id: undefined,
    fromMe: undefined,
    senderName: undefined,
    profilePicThumbObj: undefined,
    status: undefined
  });

  // MESSAGE RECEIVED
  if (mNew.key.fromMe == false) {
    objReceived.messages[0].id = mNew.key.fromMe + '_' + mNew.key.remoteJid + '_' + mNew.key.id;
    objReceived.messages[0].fromMe = mNew.key.fromMe;
    objReceived.messages[0].senderName = await conn.chats.get(mNew.key.remoteJid).name;
    objReceived.messages[0].profilePicThumbObj = await conn.getProfilePicture(mNew.key.remoteJid);
    objReceived.messages[0].status = 'received';
  // MESSAGES SENT
  } else if (mNew.key.fromMe == true) {
    objReceived.messages[0].id = mNew.key.fromMe + '_' + conn.user.jid + '_' + mNew.key.id
    objReceived.messages[0].fromMe = mNew.key.fromMe;
    objReceived.messages[0].status = 'sent';
  }
  await request({ url: 'http//mysite.com/webhook', method: "POST", json: objReceived });
  await conn.chatRead(mNew.key.remoteJid);
});
```

**Expected behavior**
I want to take the error `Unauthorized` and set the `profilePicThumbObj = undefined` on the object.

**Error context**
```node
BaileysError: Unexpected status in 'query': Unauthorized(401)
    at WAConnection.query (/baileys/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WAConnection.getProfilePicture (/baileys/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:210:26)
    at async /baileys/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:32
    at async WAConnection.<anonymous> (/baileys/src/app.js:131:50) {
  status: 401,
  context: {
    query: [ 'query', 'ProfilePicThumb', '5511987654321@s.whatsapp.net' ],
    message: 'Unauthorized',
    status: 401
  }
}
```

**Comment by barkerpedro** [comment]
Hello, I don't know if it's right, but I managed to get around the error as follows:

`Add in line 228 of src/WAConnection/0.Base.ts: `

```node
if (response.status !== 401) {
    const message = STATUS_CODES[response.status] || 'unknown'
    throw new BaileysError (`Unexpected status in '${json[0] || 'generic query'}': ${STATUS_CODES[response.status]}${response.status})`, {query: json, message, status: response.status})
}
```

In my project use:
```node
const getProfilePic = await conn.getProfilePicture(mNew.key.remoteJid);
if (getProfilePic) {
    objReceived.messages[0].profilePicThumbObj = getProfilePic;
} else {
    objReceived.messages[0].profilePicThumbObj = 'unauthorized';
}
```

**Comment by adiwajshing** [comment]
You could also just `objReceived.messages[0].profilePicThumbObj = await conn.getProfilePicture(mNew.key.remoteJid).catch(() => '')`
