### ISSUE TITLE
[BUG] BaileysError: Decryption failed, HMAC sign does not match

### ISSUE THREAD

**Issue by ilyaborodin** [adiwajshing/Baileys#212]
Description:

I am trying to save media when i get new message from me but i always catch errors. I try different methods but result is the same.

1) scan qr using phone
2) from this phone send media to somebody

>let buffer
    try {
        console.log('url ', message.message.imageMessage.url)
        buffer = await conn.downloadMediaMessage(message)
    }catch (e) {
        console.log('url ', message.message.imageMessage.url)
        await conn.updateMediaMessage(message)
        buffer = await conn.downloadMediaMessage(message)
    }
    console.log(message.key.remoteJid + " sent media, buffer: " + buffer)

>url  
url  
decryption of imageMessage media with original HKDF key failed
(node:19708) UnhandledPromiseRejectionWarning: BaileysError: Decryption failed, HMAC sign does not match
    at Object.decodeMediaMessageBuffer (/home/ilya/Brazil/whatsapp_server/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:361:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WAConnection.downloadMediaMessage (/home/ilya/Brazil/whatsapp_server/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:223:26)
    at async /home/ilya/Brazil/whatsapp_server/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:32
    at async decode_and_save_message (/home/ilya/Brazil/whatsapp_server/app/files.js:60:18)
    at async get_message_info (/home/ilya/Brazil/whatsapp_server/app/operations.js:70:9)
    at async WAConnection.<anonymous> (/home/ilya/Brazil/whatsapp_server/app/events.js:75:28)

**Comment by adiwajshing** [comment]
That's because WA takes a while to update the media url when you immediately send it from the phone. When you send the media, wait for the `message-update` event -- where WA will update the image's url & then you can download the media

**Comment by ilyaborodin** [comment]
> That's because WA takes a while to update the media url when you immediately send it from the phone. When you send the media, wait for the `message-update` event -- where WA will update the image's url & then you can download the media

Thx, i will check later it.
