### ISSUE TITLE
[BUG] rate-overlimit

### ISSUE THREAD

**Issue by SetyaStore** [adiwajshing/Baileys#2148]
node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56
        throw new boom_1.Boom(errNode.attrs.text || 'Unknown error', { data: +errNode.attrs.code });
              ^
Error: rate-overlimit
    at assertNodeErrorFree (/root/RPLBOTB/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/root/RPLBOTB/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:127:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at groupMetadata (/root/RPLBOTB/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:22:24)
    at /root/RPLBOTB/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:272:41
    at async Promise.all (index 0)
    at /root/RPLBOTB/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:265:51
    at Object.transaction (/root/RPLBOTB/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:85:21)
    at relayMessage (/root/RPLBOTB/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:262:9)
    at Object.sendMessage (/root/RPLBOTB/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:521:17)

**Comment by jurajmatus** [comment]
This is coming from WhatsApp. You need to throttle the calls to groupMetadata
