### ISSUE TITLE
[BUG] Connection abruptly terminating in larger groups.

### ISSUE THREAD

**Issue by sudomaaz** [adiwajshing/Baileys#2193]
**I observed a scenario in which if there are lots of users in a group my current 338 users then bot is unable to send messages and keeps closing the connection., while same bot is working in other groups successfully where number of users are less or equivalent to earlier group limit <=257 . Currently on MD and using edge version and using multistate-file-auth** 

 am pasting error logs.
     

```
trace: "Error: Connection was lost\n    at Timeout._onTimeout (/workspace/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:289:17)\n    at listOnTimeout (node:internal/timers:559:17)\n    at processTimers (node:internal/timers:502:7)"
[chotubotv3-0] [2022-09-24 22:16:21] [22:16:20.901] ERROR (28): ::: ERROR OCCURED HANDLE MESSAGE :::
[chotubotv3-0] [2022-09-24 22:16:21] [22:16:20.901] ERROR (28): Connection Closed
[chotubotv3-0] [2022-09-24 22:16:21]     err: {
[chotubotv3-0] [2022-09-24 22:16:21]       "type": "Error",
[chotubotv3-0] [2022-09-24 22:16:21]       "message": "Connection Closed",
[chotubotv3-0] [2022-09-24 22:16:21]       "stack":
[chotubotv3-0] [2022-09-24 22:16:21]           Error: Connection Closed
[chotubotv3-0] [2022-09-24 22:16:21]               at sendRawMessage (/workspace/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:50:19)
[chotubotv3-0] [2022-09-24 22:16:21]               at sendNode (/workspace/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:61:16)
[chotubotv3-0] [2022-09-24 22:16:21]               at /workspace/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:402:19
[chotubotv3-0] [2022-09-24 22:16:21]               at async Object.transaction (/workspace/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:148:21)
[chotubotv3-0] [2022-09-24 22:16:21]               at async relayMessage (/workspace/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:262:9)
[chotubotv3-0] [2022-09-24 22:16:21]               at async Object.sendMessage (/workspace/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:527:17)
[chotubotv3-0] [2022-09-24 22:16:21]       "data": null,
[chotubotv3-0] [2022-09-24 22:16:21]       "isBoom": true,
[chotubotv3-0] [2022-09-24 22:16:21]       "isServer": false,
[chotubotv3-0] [2022-09-24 22:16:21]       "output": {
[chotubotv3-0] [2022-09-24 22:16:21]         "statusCode": 428,
[chotubotv3-0] [2022-09-24 22:16:21]         "payload": {
[chotubotv3-0] [2022-09-24 22:16:21]           "statusCode": 428,
[chotubotv3-0] [2022-09-24 22:16:21]           "error": "Precondition Required",
[chotubotv3-0] [2022-09-24 22:16:21]           "message": "Connection Closed"
[chotubotv3-0] [2022-09-24 22:16:21]         },
[chotubotv3-0] [2022-09-24 22:16:21]         "headers": {}
[chotubotv3-0] [2022-09-24 22:16:21]       }
[chotubotv3-0] [2022-09-24 22:16:21]     }

[22:16:21.012] INFO (28): logging in...
[chotubotv3-0] [2022-09-24 22:16:21]     node: {
[chotubotv3-0] [2022-09-24 22:16:21]       "username": "12539249233",
[chotubotv3-0] [2022-09-24 22:16:21]       "passive": true,
[chotubotv3-0] [2022-09-24 22:16:21]       "userAgent": {
[chotubotv3-0] [2022-09-24 22:16:21]         "platform": "WEB",
[chotubotv3-0] [2022-09-24 22:16:21]         "appVersion": {
[chotubotv3-0] [2022-09-24 22:16:21]           "primary": 2,
[chotubotv3-0] [2022-09-24 22:16:21]           "secondary": 2230,
[chotubotv3-0] [2022-09-24 22:16:21]           "tertiary": 15
[chotubotv3-0] [2022-09-24 22:16:21]         },
[chotubotv3-0] [2022-09-24 22:16:21]         "mcc": "000",
[chotubotv3-0] [2022-09-24 22:16:21]         "mnc": "000",
[chotubotv3-0] [2022-09-24 22:16:21]         "osVersion": "0.1",
[chotubotv3-0] [2022-09-24 22:16:21]         "manufacturer": "",
[chotubotv3-0] [2022-09-24 22:16:21]         "device": "Desktop",
[chotubotv3-0] [2022-09-24 22:16:21]         "osBuildNumber": "0.1",
[chotubotv3-0] [2022-09-24 22:16:21]         "releaseChannel": "RELEASE",
[chotubotv3-0] [2022-09-24 22:16:21]         "localeLanguageIso6391": "en",
[chotubotv3-0] [2022-09-24 22:16:21]         "localeCountryIso31661Alpha2": "US"
[chotubotv3-0] [2022-09-24 22:16:21]       },
[chotubotv3-0] [2022-09-24 22:16:21]       "webInfo": {
[chotubotv3-0] [2022-09-24 22:16:21]         "webSubPlatform": "DARWIN"
[chotubotv3-0] [2022-09-24 22:16:21]       },
[chotubotv3-0] [2022-09-24 22:16:21]       "connectType": "WIFI_UNKNOWN",
[chotubotv3-0] [2022-09-24 22:16:21]       "connectReason": "USER_ACTIVATED",
[chotubotv3-0] [2022-09-24 22:16:21]       "device": 73
[chotubotv3-0] [2022-09-24 22:16:21]     }
```

This happens when bot is starting up and it always fails with these logs. Sometimes sending repeated messages to bot in group allows bot to update prekeys and then it starts working. Unable to figure exact root cause.

@adiwajshing

**Comment by manojsitapara** [comment]
I am also facing same issue
