### ISSUE TITLE
[BUG] Internal Server Error

### ISSUE THREAD

**Issue by joelvitorniino** [adiwajshing/Baileys#2213]
C:\Users\vitor\Documents\mamakos_bot\node_modules\@adiwajshing\baileys\lib\WABinary\generic-utils.js:56
        throw new boom_1.Boom(errNode.attrs.text || 'Unknown error', { data: +errNode.attrs.code });
              ^
Error: rate-overlimit
    at assertNodeErrorFree (C:\Users\vitor\Documents\mamakos_bot\node_modules\@adiwajshing\baileys\lib\WABinary\generic-utils.js:56:15)
    at query (C:\Users\vitor\Documents\mamakos_bot\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:127:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async groupMetadata (C:\Users\vitor\Documents\mamakos_bot\node_modules\@adiwajshing\baileys\lib\Socket\groups.js:22:24)
    at async C:\Users\vitor\Documents\mamakos_bot\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:272:41
    at async Promise.all (index 0)
    at async C:\Users\vitor\Documents\mamakos_bot\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:265:51
    at async Object.transaction (C:\Users\vitor\Documents\mamakos_bot\node_modules\@adiwajshing\baileys\lib\Utils\auth-utils.js:85:21)
    at async relayMessage (C:\Users\vitor\Documents\mamakos_bot\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:262:9)
    at async Object.sendMessage (C:\Users\vitor\Documents\mamakos_bot\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:521:17) {
  data: 429,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

**Comment by hassanfuad96** [comment]
up

**Comment by makanSukros** [comment]
> 127

for temporary fixed, add catch on this function: const waitForMessage
