### ISSUE TITLE
[BUG]  Error: forbidden

### ISSUE THREAD

**Issue by Cosm1cBug** [adiwajshing/Baileys#2278]
**Describe the bug**
While running the bot am getting this error, the bot won't stop but it keeps showing the error message again and again.

Error: forbidden
    at assertNodeErrorFree (D:\test\node_modules\@adiwajshing\baileys\lib\WABinary\generic-utils.js:56:15)
    at query (D:\test\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:127:48)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.groupMetadata (D:\test\node_modules\@adiwajshing\baileys\lib\Socket\groups.js:22:24)
    at async EventEmitter.updateParticipantsToDb (D:\test\lib\simple.js:71:79) {
  data: 403,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
} unhandledRejection

**Environment (please complete the following information):**
 - Is this on a server? Yes NodeJS 16
 - What do your `connectOptions` look like? 
  
 const connectionOptions = {
  printQRInTerminal: true,
  auth: state,
  logger: P({ level: 'silent' }),
  browser: ['BOT-MD', 'IOS', '4.1.0'],
  version: [2, 2238, 7],
}

 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Comment by shirser121** [comment]
same

**Comment by deriknyvo** [comment]
i have same problem
