### ISSUE TITLE
Error: Incomplete app state key sync

### ISSUE THREAD

**Issue by wesuRage** [adiwajshing/Baileys#2300]
# The error bellow appears after scanning the qr code
```
connection closed due to  Error: Incomplete app state key sync
    at logout (C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:347:13)
    at C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\chats.js:586:17      
    at C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Utils\event-buffer.js:105:36    at C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\messages-recv.js:463:17
    at async Promise.all (index 0)
    at handleMessage (C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\messages-recv.js:418:9) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 401,
    payload: {
      statusCode: 401,
      error: 'Unauthorized',
      message: 'Incomplete app state key sync'
    },
    headers: {}
  }
} , reconnecting  false
```

## My code:

- start.ts:
```

import bot from "./bot"

bot()
```
- bot.ts:
```
import { connect } from "./connection";

export default async () => {
    const socket = await connect();

    socket.ev.on("messages.upsert", async (message) => {
        console.log(JSON.stringify(message, undefined, 2))

        console.log("replying to", message.messages[0].key.remoteJid)
        await socket.sendMessage(message.messages[0].key.remoteJid!, {
            text: "penio alvorecido."
        })
    })
}
```
- connection.ts:
```
import makeWASocket, { DisconnectReason, useMultiFileAuthState } from "@adiwajshing/baileys";
import { Boom } from "@hapi/boom"
import path from "path";

export const connect = async () =>{
    const {state, saveCreds} = await useMultiFileAuthState(
        path.join(
            __dirname,
            "..",
            "cache",
    ))

    const socket = makeWASocket({
        printQRInTerminal: true,
        auth: state,
    })
    socket.ev.on("creds.update", saveCreds)
  
    socket.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = (lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                connect()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    })

    return socket;
}
```

**I couldn't find any solutions for this error, can someone help please?**

**Comment by barkerpedro** [comment]
Try:

```typescript
 socket.ev.on("creds.update", await saveCreds())
```

**Comment by wesuRage** [comment]
> Try:
> 
> ```ts
>  socket.ev.on("creds.update", await saveCreds())
> ```

unfortunately still with error, but before the unauthorized error shows up, this shows up:

````connection closed due to  Error: Stream Errored (restart required)
    at WebSocket.<anonymous> (C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:424:13)
    at WebSocket.emit (node:events:513:28)
    at C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:222:35     
    at Object.decodeFrame (C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Utils\noise-handler.js:131:17)
    at WebSocket.onMessageRecieved (C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:198:15)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (C:\Users\User\Documents\mythings\proj\node_modules\ws\lib\websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (C:\Users\User\Documents\mythings\proj\node_modules\ws\lib\receiver.js:513:14)     
    at Receiver.getData (C:\Users\User\Documents\mythings\proj\node_modules\ws\lib\receiver.js:446:17) {       
  data: { tag: 'stream:error', attrs: { code: '515' }, content: undefined },
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 515,
    payload: {
      statusCode: 515,
      error: 'Unknown',
      message: 'Stream Errored (restart required)'
    },
    headers: {}
  }
} , reconnecting  true```

and then, again the same error:

``
connection closed due to  Error: Incomplete app state key sync
    at logout (C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:347:13)
    at C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\chats.js:586:17      
    at C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Utils\event-buffer.js:105:36    at C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\messages-recv.js:463:17 {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 401,
    payload: {
      statusCode: 401,
      error: 'Unauthorized',
      message: 'Incomplete app state key sync'
    },
    headers: {}
  }
} , reconnecting  false
``

**Comment by wesuRage** [comment]
> Try:
> 
> ```ts
>  socket.ev.on("creds.update", await saveCreds())
> ```

## Unfortunately, still with error, but before the unauthorized error shows up, this shows up:

```
connection closed due to  Error: Stream Errored (restart required)
    at WebSocket.<anonymous> (C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:424:13)
    at WebSocket.emit (node:events:513:28)
    at C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:222:35     
    at Object.decodeFrame (C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Utils\noise-handler.js:131:17)
    at WebSocket.onMessageRecieved (C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:198:15)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (C:\Users\User\Documents\mythings\proj\node_modules\ws\lib\websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (C:\Users\User\Documents\mythings\proj\node_modules\ws\lib\receiver.js:513:14)     
    at Receiver.getData (C:\Users\User\Documents\mythings\proj\node_modules\ws\lib\receiver.js:446:17) {       
  data: { tag: 'stream:error', attrs: { code: '515' }, content: undefined },
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 515,
    payload: {
      statusCode: 515,
      error: 'Unknown',
      message: 'Stream Errored (restart required)'
    },
    headers: {}
  }
} , reconnecting  true
```

## and then, the same error:

```
connection closed due to  Error: Incomplete app state key sync
    at logout (C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:347:13)
    at C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\chats.js:586:17      
    at C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Utils\event-buffer.js:105:36    at C:\Users\User\Documents\mythings\proj\node_modules\@adiwajshing\baileys\lib\Socket\messages-recv.js:463:17 {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 401,
    payload: {
      statusCode: 401,
      error: 'Unauthorized',
      message: 'Incomplete app state key sync'
    },
    headers: {}
  }
} , reconnecting  false
```

**Comment by wesuRage** [comment]
I was using a modded version of whatsapp for tests, i suspect that this version already has in it some api for whatsapp bot. Then i installed another modded whatsapp and it worked. Anyway thanks for the help!!

**Comment by macleysousa** [comment]
I found a branch of Baileys is sending the buttons [https://github.com/Auties00/Baileys](url)

``` js
const buttons = [
  {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
  {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1},
  {buttonId: 'id3', buttonText: {displayText: 'Button 3'}, type: 1}
]

const buttonMessage = {
    text: "Hi it's button message",
    footer: 'Hello World',
    buttons: buttons,
    headerType: 1
}

const sendMsg = await sock.sendMessage(id, buttonMessage)
```

so I believe that it is still possible to send buttons, we just have to describe the correct template.
