### ISSUE TITLE
[BUG] Internal Server error

### ISSUE THREAD

**Issue by RavensVenix** [adiwajshing/Baileys#2301]
2022-10-27T13:33:48.589992+00:00 app[worker.1]: Connected... {
2022-10-27T13:33:48.590020+00:00 app[worker.1]:   connection: 'connecting',
2022-10-27T13:33:48.590021+00:00 app[worker.1]:   receivedPendingNotifications: false,
2022-10-27T13:33:48.590021+00:00 app[worker.1]:   qr: undefined
2022-10-27T13:33:48.590021+00:00 app[worker.1]: }
2022-10-27T13:33:48.851192+00:00 app[worker.1]: Connected... { connection: 'open' }
2022-10-27T13:33:50.058183+00:00 app[worker.1]: Connected... { receivedPendingNotifications: true }
2022-10-27T13:34:06.004167+00:00 app[worker.1]: [ MESSAGE ] Thu Oct 27 2022 13:34:06 GMT+0000 (Coordinated Universal Time) alo cuy
2022-10-27T13:34:06.004210+00:00 app[worker.1]: => From 62xxxxx@s.whatsapp.net
2022-10-27T13:34:06.004211+00:00 app[worker.1]: => In Private Chat 62xxxxx@s.whatsapp.net
2022-10-27T13:34:06.159890+00:00 app[worker.1]: /app/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290
2022-10-27T13:34:06.159891+00:00 app[worker.1]:         throw new boom_1.Boom(errNode.attrs.text || 'Unknown error', { data: +errNode.attrs.code });
2022-10-27T13:34:06.159892+00:00 app[worker.1]:               ^
2022-10-27T13:34:06.159893+00:00 app[worker.1]: 
2022-10-27T13:34:06.159893+00:00 app[worker.1]: Error: service-unavailable
2022-10-27T13:34:06.159895+00:00 app[worker.1]:     at Object.assertNodeErrorFree (/app/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290:15)
2022-10-27T13:34:06.159896+00:00 app[worker.1]:     at Object.query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:141:24)
2022-10-27T13:34:06.159896+00:00 app[worker.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2022-10-27T13:34:06.159896+00:00 app[worker.1]:   data: 503,
2022-10-27T13:34:06.159896+00:00 app[worker.1]:   isBoom: true,
2022-10-27T13:34:06.159897+00:00 app[worker.1]:   isServer: true,
2022-10-27T13:34:06.159897+00:00 app[worker.1]:   output: {
2022-10-27T13:34:06.159898+00:00 app[worker.1]:     statusCode: 500,
2022-10-27T13:34:06.159898+00:00 app[worker.1]:     payload: {
2022-10-27T13:34:06.159898+00:00 app[worker.1]:       statusCode: 500,
2022-10-27T13:34:06.159907+00:00 app[worker.1]:       error: 'Internal Server Error',
2022-10-27T13:34:06.159908+00:00 app[worker.1]:       message: 'An internal server error occurred'
2022-10-27T13:34:06.159908+00:00 app[worker.1]:     },
2022-10-27T13:34:06.159908+00:00 app[worker.1]:     headers: {}
2022-10-27T13:34:06.159909+00:00 app[worker.1]:   }
2022-10-27T13:34:06.159909+00:00 app[worker.1]: }
2022-10-27T13:34:06.159909+00:00 app[worker.1]: 
2022-10-27T13:34:06.159909+00:00 app[worker.1]: Node.js v18.12.0
2022-10-27T13:34:06.290763+00:00 heroku[worker.1]: Process exited with status 1
2022-10-27T13:34:06.353861+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by RavensVenix** [comment]
sometimes it works perfectly, sometimes it crashes at random times. Don't know why

**Comment by SammKun** [comment]
I'm facing this error, it doesn't affect me much but it's very annoying all the time in the terminal
