### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hirohito-xyz** [adiwajshing/Baileys#2310]
/storage/emulated/0/abotwa/.botwa/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56
        throw new boom_1.Boom(errNode.attrs.text || 'Unknown error', { data: +errNode.attrs.code });
              ^
Error: forbidden
    at assertNodeErrorFree (/storage/emulated/0/abotwa/.botwa/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/storage/emulated/0/abotwa/.botwa/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:127:48)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.groupMetadata (/storage/emulated/0/abotwa/.botwa/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:22:24)
    at EventEmitter.<anonymous> (/storage/emulated/0/abotwa/.botwa/main.js:261:22)

**Comment by realmarcos** [comment]
You must be using something that is not allowed in the **groupMetadata** function. Next time specify the BUG better.

**Comment by FERDIZ-afk** [comment]
it's just that the code is not correct in the group participant update section
