### ISSUE TITLE
[BUG] Can't download replied media.

### ISSUE THREAD

**Issue by Quiec** [adiwajshing/Baileys#236]
**Describe the bug**
Replied media cannot download.

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like? Empty 
 - Do you have multiple clients on the same IP? Yes
 - Are you using a proxy? No

**Additional context**
Code:
```js
conn.downloadAndSaveMediaMessage(message.extendedTextMessage.contextInfo.quotedMessage);
```

```
(node:91982) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.decodeMediaMessageBuffer (/Users/yusufusta/Desktop/WhatsAsenaUsta/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:311:25)
    at WAConnection.downloadMediaMessage (/Users/yusufusta/Desktop/WhatsAsenaUsta/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:223:40)
    at /Users/yusufusta/Desktop/WhatsAsenaUsta/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:53
    at WAConnection.descriptor.value (/Users/yusufusta/Desktop/WhatsAsenaUsta/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:22:15)
    at 
```

**Comment by itacirgabral** [comment]
https://adiwajshing.github.io/Baileys/classes/_src_waconnection_8_groups_.waconnection.html#downloadandsavemediamessage

I think It should be:
```javascript
conn.downloadAndSaveMediaMessage(message)
```
(But I not tested it)


This is my tested example of forwardMessage:
```javascript
const message = {
  key: {
    remoteJid: fromChatId,
    id: fromMessageId
  },
  message: {
    conversation: fromMessageText
  }
}

const response = await conn.forwardMessage(to, message)
```
[forwardMessage](https://adiwajshing.github.io/Baileys/classes/_src_waconnection_8_groups_.waconnection.html#forwardmessage) uses `WAMessage` too

**Comment by Quiec** [comment]
@itacirgabral thanks your reply but gives another error:
```
(node:93670) UnhandledPromiseRejectionWarning: BaileysError: cannot decode text message
    at Object.decodeMediaMessageBuffer (/Users/yusufusta/Desktop/WhatsAsenaUsta/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:316:15)
    at WAConnection.downloadMediaMessage (/Users/yusufusta/Desktop/WhatsAsenaUsta/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:227:40)
    at /Users/yusufusta/Desktop/WhatsAsenaUsta/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:53
    at WAConnection.descriptor.value (/Users/yusufusta/Desktop/WhatsAsenaUsta/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:22:15)
    at WAConnection.downloadAndSaveMediaMessage (/Users/yusufusta/Desktop/WhatsAsenaUsta/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:249:35)
    at WAConnection.<anonymous> (/Users/yusufusta/Desktop/WhatsAsenaUsta/bot.js:114:20)
    at WAConnection.emit (events.js:315:20)
    at WAConnection.emit (/Users/yusufusta/Desktop/WhatsAsenaUsta/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:515:41)
    at WAConnection.chatAddMessage (/Users/yusufusta/Desktop/WhatsAsenaUsta/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:446:18)
    at WAConnection.chatAddMessageAppropriate (/Users/yusufusta/Desktop/WhatsAsenaUsta/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:394:14)```

**Comment by Quiec** [comment]
FIXED!
Finally I fixed. Final code:
```js
    var location = await message.client.downloadAndSaveMediaMessage({
        key: {
            remoteJid: message.reply_message.jid,
            id: message.reply_message.id
        },
        message: message.reply_message.data.quotedMessage
    });
```

**Comment by dcdunkan** [comment]
This should work. I just dive into the source code a bit and now I feel like, **more** simpler.
```javascript
const location = await message.client.downloadAndSaveMediaMessage({ message: message.reply_message.data.quotedMessage }, filename)```
