### ISSUE TITLE
[BUG] after update

### ISSUE THREAD

**Issue by alvino-prog** [adiwajshing/Baileys#2405]
node:internal/modules/cjs/loader:408
      throw err;
      ^

Error: Cannot find module 'C:\Users\user\Arisu-MD\node_modules\@adiwajshing\keyed-db\lib\KeyedDB.js'. Please verify that the package.json has a valid "main" entry

  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\user\\Arisu-MD\\node_modules\\@adiwajshing\\keyed-db\\package.json',
  requestPath: '@adiwajshing/keyed-db'

i use Node.js v18.12.1, how to fix

**Comment by AzRyCb** [comment]
Npm install or yarn install

**Comment by alvino-prog** [comment]
its still made same error

**Comment by Fredwuz** [comment]
I am not sure why but it seems that npm is not compiling baileys when installing so the lib folder is empty.
I fixed it by downloading this repo and compiling it myself and just inserting it inside the lib folder.
so just
```
git clone this repo
npm i 
npm run build:tsc
```
and then just copy the lib folder inside the lib folder of the baileys folder inside the node_modules folder
`node_modules/@adiwajshing/baileys/lib`
hope this fixes your issue

**Comment by Fredwuz** [comment]
I edited my comment with "this repo" I ment the Baileys repository

**Comment by alvino-prog** [comment]
it change error to 
C:\Users\user\Arisu-MD\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:36
    const { creds } = authState;
            ^

TypeError: Cannot destructure property 'creds' of 'authState' as it is undefined.
    at makeSocket (C:\Users\user\Arisu-MD\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:36:13)
    at makeChatsSocket (C:\Users\user\Arisu-MD\node_modules\@adiwajshing\baileys\lib\Socket\chats.js:19:42)
    at makeGroupsSocket (C:\Users\user\Arisu-MD\node_modules\@adiwajshing\baileys\lib\Socket\groups.js:10:46)
    at makeMessagesSocket (C:\Users\user\Arisu-MD\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:17:48)
    at makeMessagesRecvSocket (C:\Users\user\Arisu-MD\node_modules\@adiwajshing\baileys\lib\Socket\messages-recv.js:15:57)
    at makeBusinessSocket (C:\Users\user\Arisu-MD\node_modules\@adiwajshing\baileys\lib\Socket\business.js:9:61)
    at makeWASocket (C:\Users\user\Arisu-MD\node_modules\@adiwajshing\baileys\lib\Socket\index.js:6:69)
    at startXeonBotInc (C:\Users\user\Arisu-MD\xeon.js:56:24)
    at Object.<anonymous> (C:\Users\user\Arisu-MD\xeon.js:723:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)

Node.js v18.12.1

**Comment by Fredwuz** [comment]
ok so I found the answer to the first problem and maybe this will also solve your current problem you have to complie the keyed-db repo yourself to
```
git clone https://github.com/adiwajshing/keyed-db
npm i 
npm run build
```
then copy the folder inside the keyed-db folder inside your node_modules folder

`node_modules/@adiwajshing/keyed-db`

maybe this solves your problem

**Comment by alvino-prog** [comment]
its still same probs, TypeError: Cannot destructure property 'creds' of 'authState' as it is undefined.

**Comment by hansputera** [comment]
> its still same probs, TypeError: Cannot destructure property 'creds' of 'authState' as it is undefined.

Could you show your code how the variable `authState` is created?

**Comment by costasamuel16** [comment]
> its still same probs, TypeError: Cannot destructure property 'creds' of 'authState' as it is undefined.

If you created the font code in the old version of baileys try to get the example.ts because in this new version, some things were changed including the way authState works. That could be your problem.

**Comment by zeeone-ofc** [comment]
https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts
