### ISSUE TITLE
[BUG] Error: Value not found

### ISSUE THREAD

**Issue by MaznAbdullah** [adiwajshing/Baileys#2412]
```
Error: Value not found
    at KeyedDB.deleteById (/srv/Baileys/node_modules/@adiwajshing/keyed-db/lib/KeyedDB.js:90:23)
    at EventEmitter.<anonymous> (/srv/Baileys/src/Store/make-in-memory-store.js:254:27)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.<anonymous> (/srv/Baileys/src/Utils/event-buffer.js:123:16)
    at EventEmitter.emit (node:events:525:35)
    at Object.flush (/srv/Baileys/src/Utils/event-buffer.js:168:16)
    at /srv/Baileys/src/Socket/messages-recv.js:836:24
    at step (/srv/Baileys/src/Socket/messages-recv.js:44:23)
    at Object.next (/srv/Baileys/src/Socket/messages-recv.js:25:53)
    at fulfilled (/srv/Baileys/src/Socket/messages-recv.js:16:58)
```

**Comment by LucianoGonzalez** [comment]
i have the same error....

**Comment by satriowicaksn** [comment]
is this issue not resolved yet? @MaznAbdullah  @LucianoGonzalez

**Comment by LucianoGonzalez** [comment]
nothing yet....

**Comment by LucianoGonzalez** [comment]
this issue occurs when trying to delete a chat

**Comment by allegrun** [comment]
how can i solve this problem?

**Comment by jaenudin86** [comment]
i have the same error

**Comment by jaenudin86** [comment]
> how can i solve this problem?

@allegrun  how to solve problem ?

**Comment by tiagomatrixd** [comment]
any solution? i have the same problem

**Comment by maissistem** [comment]
did anyone find the solution? @MaznAbdullah @LucianoGonzalez @efgomes @jeferssonlemes @tiagomatrixd

**Comment by tiagomatrixd** [comment]
> did anyone find the solution? @MaznAbdullah @LucianoGonzalez @efgomes @jeferssonlemes @tiagomatrixd
do you delete the store.json?  or not save?  this error happens because you delete a chat and he tries to delete it in the store
