### ISSUE TITLE
[BUG] Baileys does not installing inside a docker container

### ISSUE THREAD

**Issue by guiireal** [adiwajshing/Baileys#2430]
Test 1: (Installing express, ok)

![image](https://user-images.githubusercontent.com/13739343/209899491-7d4cab84-4c84-4c83-9717-8f22928b9657.png)

Test2: (Installing baileys, error)

![image](https://user-images.githubusercontent.com/13739343/209899518-0b9230a3-d0e7-47b7-8daa-05ecff584156.png)

![image](https://user-images.githubusercontent.com/13739343/209899612-21ca73bb-ecd0-460c-bcc2-1c9ea29ab2e1.png)

Debug log:

`0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.2.0
2 info using node@v18.12.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/root/bot/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/root/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 8ms
17 timing npm:load:configload Completed in 8ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm install github:adiwajshing/baileys
21 verbose argv "install" "github:adiwajshing/baileys"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 3ms
25 verbose logfile logs-max:10 dir:/root/.npm/_logs/2022-12-29T03_25_23_673Z-
26 verbose logfile /root/.npm/_logs/2022-12-29T03_25_23_673Z-debug-0.log
27 timing npm:load:logFile Completed in 4ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 17ms
31 silly logfile done cleaning log files
32 timing config:load:flatten Completed in 0ms
33 timing arborist:ctor Completed in 1ms
34 timing idealTree:init Completed in 48ms
35 timing arborist:ctor Completed in 0ms
36 timing idealTree Completed in 105ms
37 timing command:install Completed in 111ms
38 verbose stack Error: An unknown git error occurred
38 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
38 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
38 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
39 verbose cwd /root/bot
40 verbose Linux 5.10.16.3-microsoft-standard-WSL2
41 verbose node v18.12.1
42 verbose npm  v9.2.0
43 error code ENOENT
44 error syscall spawn git
45 error path git
46 error errno -2
47 error enoent An unknown git error occurred
48 error enoent This is related to npm not being able to find a file.
48 error enoent
49 verbose exit -2
50 timing npm Completed in 149ms
51 verbose unfinished npm timer reify 1672284323709
52 verbose unfinished npm timer reify:loadTrees 1672284323710
53 verbose unfinished npm timer idealTree:userRequests 1672284323760
54 verbose code -2
55 error A complete log of this run can be found in:
55 error     /root/.npm/_logs/2022-12-29T03_25_23_673Z-debug-0.log`

**Comment by guiireal** [comment]
I have solved this error, I forgot to install git, looks like baileys has some dependencies that need git installed.
