### ISSUE TITLE
[BUG] | Error: Value not found

### ISSUE THREAD

**Issue by allegrun** [adiwajshing/Baileys#2497]
1|appapi-port-9001  | Error: Value not found
1|appapi-port-9001  |     at KeyedDB.del| Error: Value not foundeteById (/home/deploy/zulp/backend/node_modules/@adiwajshing/keyed-db/lib/KeyedDB.js:90:23)
1|appapi-port-9001  |     at EventEmitter.<anonymous> (/home/deploy/zulp/backend/node_modules/@adiwajshing/baileys/lib/Store/make-in-memory-store.js:108:23)
1|appapi-port-9001  |     at EventEmitter.emit (node:events:513:28)
1|appapi-port-9001  |     at EventEmitter.emit (node:domain:489:12)
1|appapi-port-9001  |     at EventEmitter.<anonymous> (/home/deploy/zulp/backend/node_modules/@adiwajshing/baileys/lib/Utils/event-buffer.js:40:16)
1|appapi-port-9001  |     at EventEmitter.emit (node:events:513:28)
1|appapi-port-9001  |     at EventEmitter.emit (node:domain:489:12)
1|appapi-port-9001  |     at Object.flush (/home/deploy/zulp/backend/node_modules/@adiwajshing/baileys/lib/Utils/event-buffer.js:73:16)

I have this error for several days, can someone help me to solve it
?

**Comment by allegrun** [comment]
Could someone help me solve this problem, I have this problem and I still don't know how to reproduce it so I can solve it
