### ISSUE TITLE
[BUG] - issue on websocket and etc after scan QR and Logout..

### ISSUE THREAD

**Issue by mzayn** [adiwajshing/Baileys#2546]
hi..

im using the bailey github version only...  when i got 2 issue here... using server ubuntu... 

1. got error when done scan QR
2. when logout connection bailey 

here the log 

hope how to solved this. 

Thanks

    ```
    
    
	//when after done scan QR
	
	trace: "Error: Stream Errored (restart required)\n    at WebSocket.<anonymous> (/mybot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:432:13)\n    at WebSocket.emit (node:events:513:28)\n    at /mybot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:230:35\n    at Object.decodeFrame (/mybot/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/mybot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:206:15)\n    at WebSocket.emit (node:events:513:28)\n    at Receiver.receiverOnMessage (/mybot/node_modules/@adiwajshing/baileys/node_modules/ws/lib/websocket.js:1169:20)\n    at Receiver.emit (node:events:513:28)\n    at Receiver.dataMessage (/mybot/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:513:14)\n    at Receiver.getData (/mybot/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:446:17)"
	
	//
	
	[32mINFO[39m [2023-02-10 23:25:08.592 +0800]: [36mconnection errored[39m
    trace: "Error: Stream Errored (conflict)\n    at WebSocket.<anonymous> (/mybot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:432:13)\n    at WebSocket.emit (node:events:513:28)\n    at /mybot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:230:35\n    at Object.decodeFrame (/mybot/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/mybot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:206:15)\n    at WebSocket.emit (node:events:513:28)\n    at Receiver.receiverOnMessage (/mybot/node_modules/@adiwajshing/baileys/node_modules/ws/lib/websocket.js:1169:20)\n    at Receiver.emit (node:events:513:28)\n    at Receiver.dataMessage (/mybot/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:513:14)\n    at Receiver.getData (/mybot/node_modules/@adiwajshing/baileys/node_modules/ws/lib/receiver.js:446:17)"
	
	//button for logout..
	
	trace: "Error: Intentional Logout\n    at Object.logout (/mybot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:355:13)"
    
    ```

**Comment by hansputera** [comment]
After you scan the QR, you must reconnect to the whatsapp (by reinitialize the socket connection, simply run `makeWASocket` with previous auth state)

**Comment by mzayn** [comment]
this issue don't solved. when i use logout & dis

```
INFO [2023-03-02 09:06:32.085 +0800]: connection errored
    trace: "Error: Intentional Logout\n    at Object.logout (/mybot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:355:13))"
    ```
   
   here my code :
   
![image](https://user-images.githubusercontent.com/15009301/222306759-dba94e75-e453-4ed4-8188-5704996f02de.png)

   
---------

this issue was found on WA Business - when not completely logout at the linked device and appear (Logged Out sign) > here the picture 
![image](https://user-images.githubusercontent.com/15009301/222307194-8495318f-1917-4808-966f-1c74687773e7.png)


and When in try WS Personal > the logout fully logout the device with No Sign (Logged Out) at my phone > Linked Device

hope can fix this.

Thanks
