### ISSUE TITLE
[BUG] Profile Picture URL is not generated

### ISSUE THREAD

**Issue by ar092018** [adiwajshing/Baileys#255]
Profile Picture ImgUrl is not getting generated

**To Reproduce**
1. Created a new connection
2. Used saved credentials to log back in
3. In "chats-received" event, used "conn.chats.all()" to extract all the chats

**Expected behavior**
ImgUrl to be generated and stored in the chats KeyedDb

**Environment:**
 - Is this on a server? no
 - What do your `connectOptions` look like?
    conn.autoReconnect = ReconnectMode.onAllErrors
    conn.connectOptions.maxRetries = 10
 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? yes

The following is the error trace I'm getting while fetching the chats:

```
(node:20228) UnhandledPromiseRejectionWarning: BaileysError: close
    at WAConnection.waitForConnection (/Volumes/jarvis/web/tms/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:309:19)
    at WAConnection.query (/Volumes/jarvis/web/tms/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:209:24)
    at WAConnection.fetchMessagesFromWA (/Volumes/jarvis/web/tms/node_modules/@adiwajshing/baileys/lib/WAConnection/7.MessagesExtra.js:91:37)
    at retreive (/Volumes/jarvis/web/tms/node_modules/@adiwajshing/baileys/lib/WAConnection/7.MessagesExtra.js:103:56)
    at WAConnection.loadMessages (/Volumes/jarvis/web/tms/node_modules/@adiwajshing/baileys/lib/WAConnection/7.MessagesExtra.js:117:37)
    at /Volumes/jarvis/web/tms/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:53
    at WAConnection.descriptor.value (/Volumes/jarvis/web/tms/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:22:15)
    at WAConnection.<anonymous> (/Volumes/jarvis/web/tms/server/api/routes/whatsappChat.js:152:18)
    at WAConnection.emit (events.js:311:20)
    at WAConnection.EventEmitter.emit (domain.js:482:12)
    at WAConnection.emit (/Volumes/jarvis/web/tms/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:518:41)
    at WAConnection.<anonymous> (/Volumes/jarvis/web/tms/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:92:18)
    at WAConnection.emit (events.js:311:20)
    at WAConnection.EventEmitter.emit (domain.js:482:12)
    at WAConnection.emit (/Volumes/jarvis/web/tms/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:518:41)
    at /Volumes/jarvis/web/tms/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:213:53
(node:20228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:20228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Quiec** [comment]
WhatsApp has a problem. Does not create in the web application either

**Comment by zorox-1** [comment]
same here, upon successful connection (after qrcode scanned ). the imgURL propertu in user is null

```
  user: {
    jid: 'XXXXXXXXXXX@s.whatsapp.net',
    name: 'King',
    phone: {
      wa_version: '2.21.6.17',
      mcc: '000',
      mnc: '000',
      os_version: '5.1.1',
      device_manufacturer: 'samsung',
      device_model: 'XXXX',
      os_build_number: 'LMY47V.J320HXXU0ARB1'
    },
    imgUrl: null
  }
```
