### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MiracleKak** [adiwajshing/Baileys#2563]
TypeError: jid.endsWith is not a function
    at isJidGroup (/home/container/node_modules/@adiwajshing/baileys/lib/WABinary/jid-utils.js:43:76)
    at generateWAMessageFromContent (/home/container/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:400:48)
    at generateWAMessage (/home/container/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:410:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.sendMessage (/home/container/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:502:33)
    at async zyren (/home/container/message/zyren.js:13527:5)

Help 
is this really an bug?

**Comment by luix-guxto** [comment]
Could you explain the bug better?

Try showing the snippet of code where it appears.

**Comment by Verzach3** [comment]
The jid is undefined you need to check if the value exists before using any method, maybe yo can do this:

```JS
if (jid !== undefined){
    jid.endsWith("")
}
```
