### ISSUE TITLE
Error: Timed Out to send message in groups

### ISSUE THREAD

**Issue by lanaparadinha** [adiwajshing/Baileys#2634]
**Describe the bug**
Error:
0|teste-backend  | Error: Timed Out
0|teste-backend  |     at /home/deploy/teste/backend/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157:32 {
0|teste-backend  |   data: {
0|teste-backend  |     stack: 'Error\n' +
0|teste-backend  |       '    at promiseTimeout (/home/deploy/teste/backend/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:152:19)\n' +
0|teste-backend  |       '    at waitForMessage (/home/deploy/teste/backend/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:101:61)\n' +
0|teste-backend  |       '    at query (/home/deploy/teste/backend/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:124:22)\n' +
0|teste-backend  |       '    at getUSyncDevices (/home/deploy/teste/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:162:30)\n' +
0|teste-backend  |       '    at /home/deploy/teste/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:335:53\n' +
0|teste-backend  |       '    at Object.transaction (/home/deploy/teste/backend/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:140:27)\n' +
0|teste-backend  |       '    at relayMessage (/home/deploy/teste/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:269:30)\n' +
0|teste-backend  |       '    at Object.sendMessage (/home/deploy/teste/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:533:23)\n' +
0|teste-backend  |       '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
0|teste-backend  |       '    at async SendWhatsAppMessage (/home/deploy/teste/backend/dist/services/WbotServices/SendWhatsAppMessage.js:58:29)'
0|teste-backend  |   },
0|teste-backend  |   isBoom: true,
0|teste-backend  |   isServer: false,
0|teste-backend  |   output: {
0|teste-backend  |     statusCode: 408,
0|teste-backend  |     payload: {
0|teste-backend  |       statusCode: 408,
0|teste-backend  |       error: 'Request Time-out',
0|teste-backend  |       message: 'Timed Out'
0|teste-backend  |     },
0|teste-backend  |     headers: {}
0|teste-backend  |   }
0|teste-backend  | }

**To Reproduce**
Send message in groups

**Expected behavior**

**Environment (please complete the following information):**
Ubuntu server 22.04 bits
deploy@ubuntu:~$ node --version
v16.19.1
deploy@ubuntu:~$ npm --version
9.5.1
deploy@ubuntu:~$

**Comment by lanaparadinha** [comment]
> 

all connections is removed after one hour.

Not is that!
