### ISSUE TITLE
[BUG] ERROR IN LIBSIGNAL - HELP ME PLEASE

### ISSUE THREAD

**Issue by BrunoSobrino** [adiwajshing/Baileys#2686]
I am getting this "No Session" error from libsignal root, apparently it is linked to not finding the session of the user sending the message, does anyone have a possible solution to this problem?

- baileys repository that I use: https://github.com/BrunoSobrino/Baileys
- Repository of the libsignal-node I use: https://github.com/BrunoSobrino/libsignal-node

Error:

SessionError: No sessions
    at 5219996125657.0 [as awaitable] (/home/container/node_modules/libsignal/src/session_cipher.js:74:23)
    at async _asyncQueueExecutor (/home/container/node_modules/libsignal/src/queue_job.js:22:29) unhandledRejection

**Comment by alizin-api** [comment]
JUST USE AN OLD LIBSIGNAL
