### ISSUE TITLE
Connection Closed [BUG]

### ISSUE THREAD

**Issue by SafwanGanz** [adiwajshing/Baileys#2694]
{"level":50,"time":"2023-04-03T20:00:52.316Z","pid":178758,"hostname":"anonymous","class":"baileys","node":{"tag":"stream:error","attrs":{"code":"503"}},"msg":"stream errored out"}                  
{"level":30,"time":"2023-04-03T20:00:52.342Z","pid":178758,"hostname":"anonymous","class":"baileys","trace":"Error: Stream Errored (unknown)\n    at WebSocket.<anonymous> (/root/bot_v2/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:424:13)\n    at WebSocket.emit (node:events:513:28)\n    at /root/bot_v2/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/root/bot_v2/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/root/bot_v2/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)\n    at WebSocket.emit (node:events:513:28)\n    at Receiver.receiverOnMessage (/root/bot_v2/node_modules/ws/lib/websocket.js:1180:20)\n    at Receiver.emit (node:events:513:28)\n    at Receiver.dataMessage (/root/bot_v2/node_modules/ws/lib/receiver.js:526:14)\n    at Receiver.getData (/root/bot_v2/node_modules/ws/lib/receiver.js:459:17)","msg":"connection errored"}                                          Connection: close

Tell me how to fix?

**Comment by bryanjhv** [comment]
I'm having this problem too, even using Yarn like README proposes.
For completeness, here are the logs I'm getting (when I try to log in):

```jsonl
{"level":30,"time":"2023-04-08T23:48:43.350Z","pid":18061,"hostname":"LAPTOP-A8DIKTD9","class":"baileys","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"OS8V2bAyHQQ6BtC8MtMLxSRQ4Ti51ppKUwFkoRXFihM="}},"msg":"connected to WA Web"}
{"level":30,"time":"2023-04-08T23:48:43.516Z","pid":18061,"hostname":"LAPTOP-A8DIKTD9","class":"baileys","node":{"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2243,"tertiary":7},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAALQ==","eKeytype":"BQ==","eIdent":"berkyDTUh2lOKxBp7iA2ONB+hCdru/tU1slUAoc1QwQ=","eSkeyId":"AAAB","eSkeyVal":"lKINcyHaPHH0RTtcZmn1bWwo5w79gMa8aZzrkHQMGTQ=","eSkeySig":"t2lDAZncnF/WR5jKuJR/8s0w7fEXTmotxe2sHz+2HUNhmg5MmNlDAWiR8kh4mbrgk4T+XQ7YpqkH9kI0824hAQ==","buildHash":"JbIlG8aZUo3iKOud0Lr3GA==","deviceProps":"CgdCYWlsZXlzEgYIBBAAGAAYASAA"}},"msg":"not logged in, attempting registration..."}
{"//":"In this line, a QR code shows in Terminal"}
{"level":30,"time":"2023-04-08T23:48:45.180Z","pid":18061,"hostname":"LAPTOP-A8DIKTD9","class":"baileys","me":{"id":"51991737310:22@s.whatsapp.net"},"platform":"android","msg":"pairing configured successfully, expect to restart the connection..."}
{"level":50,"time":"2023-04-08T23:48:45.401Z","pid":18061,"hostname":"LAPTOP-A8DIKTD9","class":"baileys","node":{"tag":"stream:error","attrs":{"code":"515"}},"msg":"stream errored out"}
{"level":30,"time":"2023-04-08T23:48:45.403Z","pid":18061,"hostname":"LAPTOP-A8DIKTD9","class":"baileys","trace":"Error: Stream Errored (restart required)\n    at WebSocket.<anonymous> (/home/bryan/Projects/bryanjhv/bwawebot/.yarn/__virtual__/@adiwajshing-baileys-virtual-d58b79ad17/0/cache/@adiwajshing-baileys-npm-5.0.0-fb04a28d5d-fd90cd993a.zip/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:424:13)\n    at WebSocket.emit (node:events:513:28)\n    at WebSocket.emit (node:domain:489:12)\n    at /home/bryan/Projects/bryanjhv/bwawebot/.yarn/__virtual__/@adiwajshing-baileys-virtual-d58b79ad17/0/cache/@adiwajshing-baileys-npm-5.0.0-fb04a28d5d-fd90cd993a.zip/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/home/bryan/Projects/bryanjhv/bwawebot/.yarn/__virtual__/@adiwajshing-baileys-virtual-d58b79ad17/0/cache/@adiwajshing-baileys-npm-5.0.0-fb04a28d5d-fd90cd993a.zip/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/home/bryan/Projects/bryanjhv/bwawebot/.yarn/__virtual__/@adiwajshing-baileys-virtual-d58b79ad17/0/cache/@adiwajshing-baileys-npm-5.0.0-fb04a28d5d-fd90cd993a.zip/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)\n    at WebSocket.emit (node:events:513:28)\n    at WebSocket.emit (node:domain:489:12)\n    at Receiver.receiverOnMessage (/home/bryan/Projects/bryanjhv/bwawebot/.yarn/__virtual__/ws-virtual-d3b0a5c72f/0/cache/ws-npm-8.13.0-26ffa3016a-53e991bbf9.zip/node_modules/ws/lib/websocket.js:1184:20)\n    at Receiver.emit (node:events:513:28)","msg":"connection errored"}
{"level":30,"time":"2023-04-08T23:48:45.724Z","pid":18061,"hostname":"LAPTOP-A8DIKTD9","class":"baileys","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"0sYbdxl0G/tnb2FJrDszeNk7oq3unwn/sEbmmnpHVCo="}},"msg":"connected to WA Web"}
{"level":30,"time":"2023-04-08T23:48:45.895Z","pid":18061,"hostname":"LAPTOP-A8DIKTD9","class":"baileys","node":{"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2243,"tertiary":7},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAAvg==","eKeytype":"BQ==","eIdent":"OjrlAu+DXYavcz6GcunA/jmgPwIsbtrFzRwsR0upEgc=","eSkeyId":"AAAB","eSkeyVal":"6sv0n2MpCyOm185RAyQx9CkPtbQY/HbOkb3WrrMc+VM=","eSkeySig":"JaTbcM0JYmBgn3DuO5eXZTrkxX4fmakG7Z9aLsMlGcz+kJM7tAPnUnNOO1A3T4ZPpcTT0Orf8A03iZwntKc9Bg==","buildHash":"JbIlG8aZUo3iKOud0Lr3GA==","deviceProps":"CgdCYWlsZXlzEgYIBBAAGAAYASAA"}},"msg":"not logged in, attempting registration..."}
{"//":"In this line, a QR code shows in Terminal"}
```

**Comment by bryanjhv** [comment]
I'm having this problem too, even using Yarn like README proposes.
For completeness, here are the logs I'm getting (when I try to log in):
NOTE: Some info was redacted, specifically phone number and paths.

```jsonl
{
  "level": 30,
  "time": "2023-04-08T23:48:43.350Z",
  "pid": 18061,
  "hostname": "LAPTOP",
  "class": "baileys",
  "browser": ["Baileys", "Chrome", "4.0.0"],
  "helloMsg": {
    "clientHello": {
      "ephemeral": "OS8V2bAyHQQ6BtC8MtMLxSRQ4Ti51ppKUwFkoRXFihM="
    }
  },
  "msg": "connected to WA Web"
}
{
  "level": 30,
  "time": "2023-04-08T23:48:43.516Z",
  "pid": 18061,
  "hostname": "LAPTOP",
  "class": "baileys",
  "node": {
    "passive": false,
    "userAgent": {
      "platform": "WEB",
      "appVersion": { "primary": 2, "secondary": 2243, "tertiary": 7 },
      "mcc": "000",
      "mnc": "000",
      "osVersion": "0.1",
      "manufacturer": "",
      "device": "Desktop",
      "osBuildNumber": "0.1",
      "releaseChannel": "RELEASE",
      "localeLanguageIso6391": "en",
      "localeCountryIso31661Alpha2": "US"
    },
    "webInfo": { "webSubPlatform": "WEB_BROWSER" },
    "connectType": "WIFI_UNKNOWN",
    "connectReason": "USER_ACTIVATED",
    "devicePairingData": {
      "eRegid": "AAAALQ==",
      "eKeytype": "BQ==",
      "eIdent": "berkyDTUh2lOKxBp7iA2ONB+hCdru/tU1slUAoc1QwQ=",
      "eSkeyId": "AAAB",
      "eSkeyVal": "lKINcyHaPHH0RTtcZmn1bWwo5w79gMa8aZzrkHQMGTQ=",
      "eSkeySig": "t2lDAZncnF/WR5jKuJR/8s0w7fEXTmotxe2sHz+2HUNhmg5MmNlDAWiR8kh4mbrgk4T+XQ7YpqkH9kI0824hAQ==",
      "buildHash": "JbIlG8aZUo3iKOud0Lr3GA==",
      "deviceProps": "CgdCYWlsZXlzEgYIBBAAGAAYASAA"
    }
  },
  "msg": "not logged in, attempting registration..."
}
{ "//": "In this line, a QR code shows in Terminal" }
{
  "level": 30,
  "time": "2023-04-08T23:48:45.180Z",
  "pid": 18061,
  "hostname": "LAPTOP",
  "class": "baileys",
  "me": { "id": "51XXXXXXXXX:22@s.whatsapp.net" },
  "platform": "android",
  "msg": "pairing configured successfully, expect to restart the connection..."
}
{
  "level": 50,
  "time": "2023-04-08T23:48:45.401Z",
  "pid": 18061,
  "hostname": "LAPTOP",
  "class": "baileys",
  "node": { "tag": "stream:error", "attrs": { "code": "515" } },
  "msg": "stream errored out"
}
{
  "level": 30,
  "time": "2023-04-08T23:48:45.403Z",
  "pid": 18061,
  "hostname": "LAPTOP",
  "class": "baileys",
  "trace": "Error: Stream Errored (restart required)\n    at WebSocket.<anonymous> (/tmp/baileys/.yarn/__virtual__/@adiwajshing-baileys-virtual-d58b79ad17/0/cache/@adiwajshing-baileys-npm-5.0.0-fb04a28d5d-fd90cd993a.zip/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:424:13)\n    at WebSocket.emit (node:events:513:28)\n    at WebSocket.emit (node:domain:489:12)\n    at /tmp/baileys/.yarn/__virtual__/@adiwajshing-baileys-virtual-d58b79ad17/0/cache/@adiwajshing-baileys-npm-5.0.0-fb04a28d5d-fd90cd993a.zip/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/tmp/baileys/.yarn/__virtual__/@adiwajshing-baileys-virtual-d58b79ad17/0/cache/@adiwajshing-baileys-npm-5.0.0-fb04a28d5d-fd90cd993a.zip/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/tmp/baileys/.yarn/__virtual__/@adiwajshing-baileys-virtual-d58b79ad17/0/cache/@adiwajshing-baileys-npm-5.0.0-fb04a28d5d-fd90cd993a.zip/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)\n    at WebSocket.emit (node:events:513:28)\n    at WebSocket.emit (node:domain:489:12)\n    at Receiver.receiverOnMessage (/tmp/baileys/.yarn/__virtual__/ws-virtual-d3b0a5c72f/0/cache/ws-npm-8.13.0-26ffa3016a-53e991bbf9.zip/node_modules/ws/lib/websocket.js:1184:20)\n    at Receiver.emit (node:events:513:28)",
  "msg": "connection errored"
}
{
  "level": 30,
  "time": "2023-04-08T23:48:45.724Z",
  "pid": 18061,
  "hostname": "LAPTOP",
  "class": "baileys",
  "browser": ["Baileys", "Chrome", "4.0.0"],
  "helloMsg": {
    "clientHello": {
      "ephemeral": "0sYbdxl0G/tnb2FJrDszeNk7oq3unwn/sEbmmnpHVCo="
    }
  },
  "msg": "connected to WA Web"
}
{
  "level": 30,
  "time": "2023-04-08T23:48:45.895Z",
  "pid": 18061,
  "hostname": "LAPTOP",
  "class": "baileys",
  "node": {
    "passive": false,
    "userAgent": {
      "platform": "WEB",
      "appVersion": { "primary": 2, "secondary": 2243, "tertiary": 7 },
      "mcc": "000",
      "mnc": "000",
      "osVersion": "0.1",
      "manufacturer": "",
      "device": "Desktop",
      "osBuildNumber": "0.1",
      "releaseChannel": "RELEASE",
      "localeLanguageIso6391": "en",
      "localeCountryIso31661Alpha2": "US"
    },
    "webInfo": { "webSubPlatform": "WEB_BROWSER" },
    "connectType": "WIFI_UNKNOWN",
    "connectReason": "USER_ACTIVATED",
    "devicePairingData": {
      "eRegid": "AAAAvg==",
      "eKeytype": "BQ==",
      "eIdent": "OjrlAu+DXYavcz6GcunA/jmgPwIsbtrFzRwsR0upEgc=",
      "eSkeyId": "AAAB",
      "eSkeyVal": "6sv0n2MpCyOm185RAyQx9CkPtbQY/HbOkb3WrrMc+VM=",
      "eSkeySig": "JaTbcM0JYmBgn3DuO5eXZTrkxX4fmakG7Z9aLsMlGcz+kJM7tAPnUnNOO1A3T4ZPpcTT0Orf8A03iZwntKc9Bg==",
      "buildHash": "JbIlG8aZUo3iKOud0Lr3GA==",
      "deviceProps": "CgdCYWlsZXlzEgYIBBAAGAAYASAA"
    }
  },
  "msg": "not logged in, attempting registration..."
}
{ "//": "In this line, a QR code shows in Terminal" }
```

Here's the stack trace shown in JSON logs:

```plain
Error: Stream Errored (restart required)
    at WebSocket.<anonymous> (/tmp/baileys/.yarn/__virtual__/@adiwajshing-baileys-virtual-d58b79ad17/0/cache/@adiwajshing-baileys-npm-5.0.0-fb04a28d5d-fd90cd993a.zip/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:424:13)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at /tmp/baileys/.yarn/__virtual__/@adiwajshing-baileys-virtual-d58b79ad17/0/cache/@adiwajshing-baileys-npm-5.0.0-fb04a28d5d-fd90cd993a.zip/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35
    at Object.decodeFrame (/tmp/baileys/.yarn/__virtual__/@adiwajshing-baileys-virtual-d58b79ad17/0/cache/@adiwajshing-baileys-npm-5.0.0-fb04a28d5d-fd90cd993a.zip/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)
    at WebSocket.onMessageRecieved (/tmp/baileys/.yarn/__virtual__/@adiwajshing-baileys-virtual-d58b79ad17/0/cache/@adiwajshing-baileys-npm-5.0.0-fb04a28d5d-fd90cd993a.zip/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/tmp/baileys/.yarn/__virtual__/ws-virtual-d3b0a5c72f/0/cache/ws-npm-8.13.0-26ffa3016a-53e991bbf9.zip/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
```
