### ISSUE TITLE
[BUG] can't mark chat as unread

### ISSUE THREAD

**Issue by lukasportal** [adiwajshing/Baileys#2701]
**Describe the bug**
The lib is throwing an error when trying to mark a chat as unread.
```
Error: myAppStateKey ("AAAAAPuQ") not present
    at encodeSyncdPatch (/Users/lucas/Projects/Voxuy/Voxuy.WhatsApp.Baileys/node_modules/@adiwajshing/baileys/lib/Utils/chat-utils.js:104:15)
    at async /Users/lucas/Projects/Voxuy/Voxuy.WhatsApp.Baileys/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:485:32
    at async Object.transaction (/Users/lucas/Projects/Voxuy/Voxuy.WhatsApp.Baileys/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:145:21)
    at async /Users/lucas/Projects/Voxuy/Voxuy.WhatsApp.Baileys/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:480:13
    at async /Users/lucas/Projects/Voxuy/Voxuy.WhatsApp.Baileys/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:18:36
    at async appPatch (/Users/lucas/Projects/Voxuy/Voxuy.WhatsApp.Baileys/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:479:9)
```

**To Reproduce**
1. open a socket connection with a phone number logged in
2. call the following code: 
```
const chatid = '<full_chatid_here>';
const lastMsg = (await store.loadMessages(chatid, 1 { before: undefined, after: undefined }))[0]; // this msg is indeed the last one, correct
await sock.chatModify(
      { markRead: false, lastMessages: [lastMsg] },
      chatid
);
```

**Expected behavior**
Chat would be marked as unread in whatsapp.

**Environment (please complete the following information):**
 - Is this on a server? no
 - What do your `connectOptions` look like? 
<img width="511" alt="image" src="https://user-images.githubusercontent.com/5941939/230221574-1ebe5f56-2617-4887-ad6f-f934a7580e86.png">

 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? no

**Additional context**
everything else is working fine,  i dont see any other error messages in the log

**Comment by lukasportal** [comment]
Update: after commit 1802da12a4cd929a9f1d23668792011edbcf0a38, no more errors are shown, but the chat isnt marked as unread
