### ISSUE TITLE
[BUG] chat.messages.upsert is not a function

### ISSUE THREAD

**Issue by fdciabdul** [adiwajshing/Baileys#286]
idk why , but now is always showing like this and my app got closed after that

```
class: "Baileys"
/app/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:159
                        if (chat.messages.upsert(message).length > 0) {
                                          ^

TypeError: chat.messages.upsert is not a function
    at /app/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:159:43
    at Array.forEach (<anonymous>)
    at messagesUpdate (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:139:36)
```

**Comment by adiwajshing** [comment]
I think if you delete node_modules and your lock file and run yarn again -- should work
