### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by justinthoms** [adiwajshing/Baileys#299]
message: 'Bad Request

**Comment by justinthoms** [comment]
![image](https://user-images.githubusercontent.com/57831354/103433848-70323300-4c1e-11eb-9586-23fc394cb570.png)
 [33mWARNING:[0m ytdl-core is out of date! Update with "npm install ytdl-core@latest".
2021-01-01T04:58:38.164667+00:00 app[worker.1]: ERROR	 [2021-01-01 04:58:38.156 +0000] (3): Error in uploading to media-lhr8-1.cdn.whatsapp.net, retrying...
2021-01-01T04:58:38.164689+00:00 app[worker.1]:     class: "Baileys"
2021-01-01T04:58:43.173353+00:00 app[worker.1]: ERROR	 [2021-01-01 04:58:43.172 +0000] (3): Error in uploading to mmg.whatsapp.net
2021-01-01T04:58:43.173371+00:00 app[worker.1]:     class: "Baileys"
2021-01-01T04:58:43.187627+00:00 app[worker.1]: /root/whatsapp-userbot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:163
2021-01-01T04:58:43.187629+00:00 app[worker.1]:             throw new Error('Media upload failed on all hosts');
2021-01-01T04:58:43.187630+00:00 app[worker.1]:                   ^
2021-01-01T04:58:43.187630+00:00 app[worker.1]: 
2021-01-01T04:58:43.187631+00:00 app[worker.1]: Error: Media upload failed on all hosts
2021-01-01T04:58:43.187634+00:00 app[worker.1]:     at WAConnection.prepareMessageMedia (/root/whatsapp-userbot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:163:19)
2021-01-01T04:58:43.187634+00:00 app[worker.1]:     at processTicksAndRejections (node:internal/process/task_queues:93:5)
2021-01-01T04:58:43.187636+00:00 app[worker.1]:     at async WAConnection.prepareMessageContent (/root/whatsapp-userbot/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:81:21)

**Comment by adiwajshing** [comment]
Happens when too many uploads happen from the same IP

**Comment by justinthoms** [comment]
![image](https://user-images.githubusercontent.com/57831354/103450702-fe222280-4cdf-11eb-8165-c2cb1977ee21.png)
/root/whatsapp-userbot/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:230
2021-01-02T04:19:18.796756+00:00 app[worker.1]:             throw new Constants_1.BaileysError(`Unexpected status in '${json[0] || 'generic query'}': ${http_1.STATUS_CODES[response.status]}(${response.status})`, { query: json, message, status: response.status });
2021-01-02T04:19:18.796758+00:00 app[worker.1]:                   ^
2021-01-02T04:19:18.796759+00:00 app[worker.1]: 
2021-01-02T04:19:18.796760+00:00 app[worker.1]: BaileysError: Unexpected status in 'action': Bad Request(400)
2021-01-02T04:19:18.796761+00:00 app[worker.1]:     at WAConnection.query (/root/whatsapp-userbot/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:230:19)
2021-01-02T04:19:18.796762+00:00 app[worker.1]:     at processTicksAndRejections (node:internal/process/task_queues:93:5)
2021-01-02T04:19:18.796762+00:00 app[worker.1]:     at async WAConnection.setQuery (/root/whatsapp-userbot/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:196:24)
2021-01-02T04:19:18.796763+00:00 app[worker.1]:     at async WAConnection.chatRead (/root/whatsapp-userbot/node_modules/@adiwajshing/baileys/lib/WAConnection/7.MessagesExtra.js:57:13)
2021-01-02T04:19:18.796764+00:00 app[worker.1]:     at async /root/whatsapp-userbot/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:32
2021-01-02T04:19:18.796765+00:00 app[worker.1]:     at async /root/whatsapp-userbot/bot.js:201:29 {
2021-01-02T04:19:18.796765+00:00 app[worker.1]:   status: 400,
2021-01-02T04:19:18.796765+00:00 app[worker.1]:   context: {
2021-01-02T04:19:18.796765+00:00 app[worker.1]:     query: [
2021-01-02T04:19:18.796766+00:00 app[worker.1]:       'action',
2021-01-02T04:19:18.796767+00:00 app[worker.1]:       { epoch: '273', type: 'set' },
2021-01-02T04:19:18.796767+00:00 app[worker.1]:       [
2021-01-02T04:19:18.796767+00:00 app[worker.1]:         [
2021-01-02T04:19:18.796768+00:00 app[worker.1]:           'read',
2021-01-02T04:19:18.796768+00:00 app[worker.1]:           {
2021-01-02T04:19:18.796768+00:00 app[worker.1]:             jid: '917736849262-1606799723@g.us',
2021-01-02T04:19:18.796769+00:00 app[worker.1]:             count: '1',
2021-01-02T04:19:18.796769+00:00 app[worker.1]:             index: '029390560F646B044DF860AF834E3F73',
2021-01-02T04:19:18.796770+00:00 app[worker.1]:             owner: 'false',
2021-01-02T04:19:18.796770+00:00 app[worker.1]:             participant: undefined
2021-01-02T04:19:18.796770+00:00 app[worker.1]:           },
2021-01-02T04:19:18.796771+00:00 app[worker.1]:           null
2021-01-02T04:19:18.796771+00:00 app[worker.1]:         ]
2021-01-02T04:19:18.796771+00:00 app[worker.1]:       ]
2021-01-02T04:19:18.796772+00:00 app[worker.1]:     ],
2021-01-02T04:19:18.796772+00:00 app[worker.1]:     message: 'Bad Request',
2021-01-02T04:19:18.796773+00:00 app[worker.1]:     status: 400
2021-01-02T04:19:18.796773+00:00 app[worker.1]:   }
2021-01-02T04:19:18.796773+00:00 app[worker.1]: }

**Comment by Dimasbiasalah** [comment]
Error : BaileysError: Unexpected status in 'query': Internal Server Error(500)
