### ISSUE TITLE
How to properly stop qr code gen and close the connection?

### ISSUE THREAD

**Issue by jimmyfaat** [adiwajshing/Baileys#318]
```
const { WAConnection } = require('@adiwajshing/baileys');

let testFn = ()=>{
    let waConn = new WAConnection();

    waConn.on('qr', qr => {
        console.log(waConn.state);
        waConn.close();
    });

    waConn.connect().then(user=>{
        //...
    }).catch(err=>{
        //ignore error
    });
}

testFn();
```
It keep showing below error for every 30 seconds.

node .\test.js
INFO     [2021-01-19 03:09:06.592 +0000] (21268): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
//QR
█▄▄▄▄▄▄▄█▄█▄▄███▄▄▄▄▄██▄▄▄▄███▄▄██▄██▄█▄▄███▄██

connecting
INFO     [2021-01-19 03:09:06.857 +0000] (21268): closed connection, reason intentional
    class: "Baileys"
WARN     [2021-01-19 03:09:06.860 +0000] (21268): connect attempt 1 failed: Error: intentional
    error: {}
    class: "Baileys"
WARN     [2021-01-19 03:09:26.862 +0000] (21268): error in QR gen
    error: {}
    class: "Baileys"
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
//QR
█▄▄▄▄▄▄▄█▄█▄▄███▄▄▄▄▄██▄▄▄▄███▄▄██▄██▄█▄▄███▄██

close
INFO     [2021-01-19 03:09:26.925 +0000] (21268): closed connection, reason intentional
    class: "Baileys"
(node:21268) UnhandledPromiseRejectionWarning: BaileysError: intentional
    at WAConnection.onErr (C:\waTest\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:192:56)
    at WAConnection.emit (events.js:327:22)
    at WAConnection.emit (C:\waTest\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:614:41)
    at WAConnection.endConnection (C:\waTest\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:426:14)    
    at WAConnection.closeInternal (C:\waTest\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:411:14)    
    at WAConnection.close (C:\waTest\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:403:14)
    at WAConnection.<anonymous> (C:\waTest\test.js:8:16)
    at WAConnection.emit (events.js:327:22)
    at WAConnection.emit (C:\waTest\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:614:41)
    at qrLoop (C:\waTest\node_modules\@adiwajshing\baileys\lib\WAConnection\1.Validation.js:221:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate 
the Node.js process with a non-zero exit code.

**Comment by jessekalil** [comment]
Hello did you get a solution? I have the same problem!

```
Error: intentional
    at WAConnection.rejectAllOnWSClose (/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:79:62)
    at WAConnection.emit (events.js:327:22)
    at WAConnection.emit (/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:656:41)
    at WAConnection.endConnection (/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:415:14)
    at WAConnection.closeInternal (/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:398:14)
    at WAConnection.close (/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:390:14)

```

**Comment by thiagomagamoc** [comment]
Any solution for this?
