### ISSUE TITLE
Error on receiving data after await client.connect()

### ISSUE THREAD

**Issue by adyscorpius** [adiwajshing/Baileys#32]
Getting this error on connecting with 

[Baileys] waiting for chats & contacts"

/mnt/c/Users/<username>/projects/whatsapp-bot/node_modules/baileys/WhatsAppWeb.Send.js:327
                this.conn.send( m )
            ^
TypeError: Cannot read property 'send' of null
    at WhatsAppWeb.send (/mnt/c/Users/<username>/projects/whatsapp-bot/node_modules/baileys/WhatsAppWeb.Send.js:327:13)
    at Timeout._onTimeout (/mnt/c/Users/<username>/projects/whatsapp-bot/node_modules/baileys/WhatsAppWeb.Session.js:247:10)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-detox@0.0.1 start: `ts-node src/index.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-detox@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<username>/.npm/_logs/2020-06-09T13_11_24_956Z-debug.log

**Comment by adiwajshing** [comment]
This is odd. Could you show your code?

**Comment by adyscorpius** [comment]
Hi.. I figured out the fix. I was using Typescript and it was causing errors without a module declared. 

I'll close this issue. Do you have plans of implementing typescript to the project?

**Comment by adiwajshing** [comment]
I see, but I don’t have plans to incorporate typescript at this moment.

**Comment by adyscorpius** [comment]
Would it be okay if I shared a pull request with it?

**Comment by adiwajshing** [comment]
What exactly do you have in mind?

**Comment by adiwajshing** [comment]
Closing for inactivity.
