### ISSUE TITLE
Error sending JPEG image

### ISSUE THREAD

**Issue by barkerpedro** [adiwajshing/Baileys#358]
I saw that there are times that JPEG images are not being sent, because there is an error in lib "jpeg-js".
You may need to update to the "jpeg-js@0.4.3" version.

**_The error occurs in version 4.0.0. In version 3.4.1 it works normally;_**

ERROR:
```node
Error: marker was not found
    at decodeScan (/home/node/api/node_modules/@jimp/jpeg/node_modules/jpeg-js/lib/decoder.js:344:15)
    at constructor.parse (/home/node/api/node_modules/@jimp/jpeg/node_modules/jpeg-js/lib/decoder.js:804:29)
    at Object.decode [as image/jpeg] (/home/node/api/node_modules/@jimp/jpeg/node_modules/jpeg-js/lib/decoder.js:1096:11)
    at Jimp.parseBitmap (/home/node/api/node_modules/@jimp/core/dist/utils/image-bitmap.js:196:53)
    at Jimp.parseBitmap (/home/node/api/node_modules/@jimp/core/dist/index.js:431:32)
    at /home/node/api/node_modules/@jimp/core/dist/index.js:373:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  methodName: 'constructor'
}
```

UPDATE TEST:
```yml
"@jimp/jpeg@^0.16.1":
  version "0.16.1"
  resolved "https://registry.yarnpkg.com/@jimp/jpeg/-/jpeg-0.16.1.tgz#3b7bb08a4173f2f6d81f3049b251df3ee2ac8175"
  integrity sha512-8352zrdlCCLFdZ/J+JjBslDvml+fS3Z8gttdml0We759PnnZGqrnPRhkOEOJbNUlE+dD4ckLeIe6NPxlS/7U+w==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.16.1"
    jpeg-js "0.4.3"
```
and

```yml
jpeg-js@0.4.3:
  version "0.4.3"
  resolved "https://registry.yarnpkg.com/jpeg-js/-/jpeg-js-0.4.3.tgz#6158e09f1983ad773813704be80680550eff977b"
  integrity sha512-ru1HWKek8octvUHFHvE5ZzQ1yAsJmIvRdGWvSoKV52XKyuyYA437QWDttXT8eZXDSbuMpHlLzPDZUPd6idIz+Q==
```

**Comment by adiwajshing** [comment]
@barkerpedro are you trying to send via a buffer or stream?

**Comment by barkerpedro** [comment]
Buffer

```node
let fileUrl = await axios.get(url, { responseType: 'arraybuffer' });
let buffer = new Buffer.from(fileUrl.data, 'base64');
let options = { mimetype: 'image/jpeg' , caption: "Test JPEG", filename: "file.jpeg" };
conn.sendMessage("123456@s.whatsapp.net", buffer, MessageType.image, options);
```

**Comment by barkerpedro** [comment]
The error happens with ".jpeg", but with ".jpg" it is not happening.

**Comment by barkerpedro** [comment]
> @barkerpedro are you trying to send via a buffer or stream?

Were you able to perform any tests?

**Comment by ikheetjeff** [comment]
I have the same error: 

` Error: marker was not found
    at decodeScan (/projects/whatsapp/complimaatje/node_modules/jpeg-js/lib/decoder.js:344:15)
    at constructor.parse (/projects/whatsapp/complimaatje/node_modules/jpeg-js/lib/decoder.js:804:29)
    at Object.decode [as image/jpeg] (/projects/whatsapp/complimaatje/node_modules/jpeg-js/lib/decoder.js:1096:11)
    at Jimp.parseBitmap (/projects/whatsapp/complimaatje/node_modules/@jimp/core/dist/utils/image-bitmap.js:196:53)
    at Jimp.parseBitmap (/projects/whatsapp/complimaatje/node_modules/@jimp/core/dist/index.js:431:32)
    at /projects/whatsapp/complimaatje/node_modules/@jimp/core/dist/index.js:373:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3) {
  methodName: 'constructor'
}
`

Code: 
`await client.sendMessage('<number>@s.whatsapp.net', { url: 'https://i.imgur.com/m9VKjJf.jpg' }, MessageType.image,{ mimetype: Mimetype.png, caption: "hello!" });
`

If i add "thumbnail: null" to options, i don't get the error. Is there any fix for this?
