### ISSUE TITLE
[BUG] Error: unexpected end of file on sendMessage with one specific PNG image

### ISSUE THREAD

**Issue by canove** [adiwajshing/Baileys#364]
**Describe the bug**
Sometimes sending a specific PNG image return a error and message is not sent. I tried with Buffer and URL as "uploadType"

```
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
    at Inflate._processChunk (/home/canove/code_learn/whaticket-prod/backend/node_modules/pngjs/lib/sync-inflate.js:110:28)
    at zlibBufferSync (/home/canove/code_learn/whaticket-prod/backend/node_modules/pngjs/lib/sync-inflate.js:151:17)
    at inflateSync (/home/canove/code_learn/whaticket-prod/backend/node_modules/pngjs/lib/sync-inflate.js:155:10)
    at module.exports (/home/canove/code_learn/whaticket-prod/backend/node_modules/pngjs/lib/parser-sync.js:85:20)
    at Object.exports.read [as image/png] (/home/canove/code_learn/whaticket-prod/backend/node_modules/pngjs/lib/png-sync.js:10:10)
    at Jimp.call (/home/canove/code_learn/whaticket-prod/backend/node_modules/@jimp/core/src/utils/image-bitmap.js:165:21)
    at Jimp.parseBitmap (/home/canove/code_learn/whaticket-prod/backend/node_modules/@jimp/core/src/index.js:400:17)
    at /home/canove/code_learn/whaticket-prod/backend/node_modules/@jimp/core/src/index.js:344:14
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  errno: -5,
  code: 'Z_BUF_ERROR',
  methodName: 'constructor'
```

I've added a little "sleep" before `compressImage` function as a workaround, and it works 100% of time on my tests:
```
const compressImage = async (bufferOrFilePath) => {
    await new Promise((r) => setTimeout(r, 100));
    const jimp = await jimp_1.default.read(bufferOrFilePath);
    const result = await jimp.resize(48, 48).getBufferAsync(jimp_1.default.MIME_JPEG);
    return result;
};
```

I hope it can help.

PS.: The error  doesn't occur with every image I've, just got lucky to find one that triggers the bug 90% of times.

**Comment by ilyaborodin** [comment]
I have the same problem
