### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sudomaaz** [adiwajshing/Baileys#411]
While sending image as media message through remote url method it gives below error on certain jpg files

Error: marker was not found
    at decodeScan (F:\WA\node_modules\jpeg-js\lib\decoder.js:344:15)
    at constructor.parse (F:\WA\node_modules\jpeg-js\lib\decoder.js:804:29)
    at Object.decode [as image/jpeg] (F:\WA\node_modules\jpeg-js\lib\decoder.js:1096:11)
    at Jimp.parseBitmap (F:\WA\node_modules\@jimp\core\dist\utils\image-bitmap.js:196:53)
    at Jimp.parseBitmap (F:\WA\node_modules\@jimp\core\dist\index.js:431:32)
    at F:\WA\node_modules\@jimp\core\dist\index.js:373:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  methodName: 'constructor'

**Comment by sudomaaz** [comment]
Its a duplicate got the old thread and resolved issue

**Comment by thaziz** [comment]
how to solve the error methodName: 'constructor' ?
