### ISSUE TITLE
example.js error

### ISSUE THREAD

**Issue by eranetsa** [adiwajshing/Baileys#43]
[Baileys] connected to WhatsApp Web
TypeError: this.callbacks[key].reject is not a function
    at /home/letsw/wa/node_modules/baileys/WhatsAppWeb.Session.js:303:25
    at Array.forEach (<anonymous>)
    at WhatsAppWeb.close (/home/letsw/wa/node_modules/baileys/WhatsAppWeb.Session.js:301:8)
    at /home/letsw/wa/node_modules/baileys/WhatsAppWeb.Session.js:49:38
    at async WhatsAppWeb.connect (/home/letsw/wa/node_modules/baileys/WhatsAppWeb.Session.js:15:20)

**Comment by adiwajshing** [comment]
This is fixed in the latest version. Please install that using: `npm install @adiwajshing/baileys@1.1.1`

**Comment by adiwajshing** [comment]
Closing.
