### ISSUE TITLE
[BUG] duplicate ID being inserted

### ISSUE THREAD

**Issue by tiesco238** [adiwajshing/Baileys#459]
**Describe the bug**
Phone doesn't sync on 'open' event and throws an error from the library. Find stacktrace below:

Error: duplicate ID being inserted: 32325278120-1618284503@g.us
at KeyedDB._insertSingle (/home/user/folder/instance/node_modules/@adiwajshing/keyed-db/lib/KeyedDB.js:194:19)
at /home/user/folder/instance/node_modules/@adiwajshing/keyed-db/lib/KeyedDB.js:36:34
at Array.forEach (<anonymous>)
at KeyedDB.insert (/home/user/folder/instance/node_modules/@adiwajshing/keyed-db/lib/KeyedDB.js:36:16)
at /home/user/folder/instance/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:128:23
at Array.forEach (<anonymous>)
 at WAConnection.<anonymous> (/home/user/folder/instance/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:118:21)
at WAConnection.emit (events.js:315:20)
at WAConnection.EventEmitter.emit (domain.js:467:12)
at WAConnection.emit (/home/user/folder/instance/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:656:41)

Apparently the local Keyed db does not allow a (group) chat to be added twice.

**To Reproduce**
1. Scan QR code and make sure it logs in

**Expected behavior**
Sync chats from chat with the client

**Environment (please complete the following information):**
 - Is this on a server? 
 - YES
 - What do your `connectOptions` look like? 
 conn.autoReconnect = ReconnectMode.off
        conn.connectOptions.maxRetries = 10;

 - Do you have multiple clients on the same IP?
 YES
 - Are you using a proxy?
NO
**Additional context**
It can be reproduced everytime, but only for some whatsapp accounts.

**Comment by adiwajshing** [comment]
@tiesco238 should be resolved in latest commit

**Comment by tiesco238** [comment]
thanks a lot @adiwajshing it seems to work!
