### ISSUE TITLE
TypeError: Cannot read property 'send' of null

### ISSUE THREAD

**Issue by nswbmw** [adiwajshing/Baileys#46]
An error is reported after the program has been running for some time.

```js
TypeError: Cannot read property 'send' of null
    at WhatsAppWeb.send (/root/xxx/node_modules/baileys/WhatsAppWeb.Send.js:327:13)
    at WhatsAppWeb.sendJSON (/root/xxx/node_modules/baileys/WhatsAppWeb.Send.js:317:8)
    at WhatsAppWeb.query (/root/xxx/node_modules/baileys/WhatsAppWeb.Send.js:280:15)
    at WhatsAppWeb.isOnWhatsApp (/root/xxx/node_modules/baileys/WhatsAppWeb.Query.js:11:15)
    at validateWhatsappNumber (/root/xxx/app/route/Whatsapp.validateWhatsappNumber.js:38:44)
```

**Comment by adiwajshing** [comment]
That's odd.

1. Did you turn off `autoReconnect`?
2. What's your setup like? Like what triggers the `isOnWhatsappNumber` query?

**Comment by nswbmw** [comment]
1. No. `client.autoReconnect = true`
2. use koa

```js
const body = ctx.request.body
const whats_app = body.whats_app

const [exist] = await whatsappClient.isOnWhatsApp(`${whats_app}@c.us`)
ctx.body = exist
```

**Comment by adiwajshing** [comment]
So there could be a few reasons why this is happening:
1. You're calling the function without waiting for `connect()` to end
2. You've called the function after closing the connection
3. The library is trying to reconnect after an unexpected disconnect and this function was called while reconnecting (unlikely)

If you can rule out 1. and 2, lemme know and I'll provide a solution for 3.

**Comment by nswbmw** [comment]
restart is now work. Only print:

```
 [Baileys] connected to WhatsApp Web
```

I need delete auth.json and scan qrcode again.

**Comment by nswbmw** [comment]
baileys@1.1.1
