### ISSUE TITLE
[BUG] Not Expecting a Response

### ISSUE THREAD

**Issue by Xenon67** [adiwajshing/Baileys#473]
**Describe the bug**
Sometimes bailyes send this error:

```
2021-04-29T20:55:59.013023+00:00 app[worker.1]: /root/WhatsAsenaDuplicated/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:188
2021-04-29T20:55:59.013035+00:00 app[worker.1]:                 onErr = ({ reason, status }) => reject(new Constants_1.BaileysError(reason, { status }));
2021-04-29T20:55:59.013036+00:00 app[worker.1]:                                                        ^
2021-04-29T20:55:59.013038+00:00 app[worker.1]: 
2021-04-29T20:55:59.013039+00:00 app[worker.1]: BaileysError: Not expecting a response
2021-04-29T20:55:59.013039+00:00 app[worker.1]:     at onErr (/root/WhatsAsenaDuplicated/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:188:56)
2021-04-29T20:55:59.013039+00:00 app[worker.1]:     at /root/WhatsAsenaDuplicated/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:183:82
2021-04-29T20:55:59.013040+00:00 app[worker.1]:     at Timeout.<anonymous> (/root/WhatsAsenaDuplicated/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:270:21)
2021-04-29T20:55:59.013041+00:00 app[worker.1]:     at listOnTimeout (node:internal/timers:556:17)
2021-04-29T20:55:59.013041+00:00 app[worker.1]:     at processTimers (node:internal/timers:499:7) {
2021-04-29T20:55:59.013042+00:00 app[worker.1]:   status: 422,
2021-04-29T20:55:59.013043+00:00 app[worker.1]:   context: { status: 422 }
```
It mostly happens in media messages. There was no such error in the previous version (3.4.1), even this error just started to occur.

Can you fix it @adiwajshing, I would be very pleased :)

**Comment by ziadAwfarDev** [comment]
it happens also when blocking contact

**Comment by Nurutomo** [comment]
it also happens when sending reply

**Comment by phaticusthiccy** [comment]
Oh, maybe ur right. I don't test it completely yet. I just wann to open issues for people to see this bug. @Nurutomo does not throw thiss err for every replied message. I just fixed it but ı must check [ai scanner](https://github.com/phaticusthiccy/WhatsAsenaDuplicated/blob/master/plugins/updown.js) program. 
Okey thanks guys, i appreciate it :)
(I am the one who opened this issue)

**Comment by adiwajshing** [comment]
@Xenon67 the issue always existed. The latest version only catches the error -- that the response isn't expected from the phone anymore. You can ignore the error if it suits your work.

**Comment by phaticusthiccy** [comment]
> @Xenon67 the issue always existed. The latest version only catches the error -- that the response isn't expected from the phone anymore. You can ignore the error if it suits your work.

Oh okey, thanks for information! Now ı m closing this issue.
