### ISSUE TITLE
Error when replying message contain media

### ISSUE THREAD

**Issue by azudindaem** [adiwajshing/Baileys#503]
**Describe the bug**
TypeError: this.isZero is not a function
    at String.toString (/home/../node_modules/long/src/long.js:474:14)
    at Function.toObject (/home/../node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:9881:98)
    at Function.toObject (/home/../node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:25789:64)
    at Function.toObject (/home/../node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:8874:60)
    at Function.toObject (/home/../node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:11093:62)
    at Function.toObject (/home/../node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:25795:78)
    at Function.toObject (/home/../node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:4635:54)
    at WebMessageInfo.toJSON (/home/../node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:4709:37)
    at JSON.stringify (<anonymous>)
    at stringify (/home/../node_modules/express/lib/response.js:1123:12)

sample message:
quotedMessage log:
{
  key: {
    remoteJid: 'xx@s.whatsapp.net',
    fromMe: false,
    id: 'xxx'
  },
  message: {
    imageMessage: {
      url: 'https://mmg.whatsapp.net/d/f/... .enc',
      mimetype: 'image/jpeg',
     .
     .
      scanLengths: [Array],
      midQualityFileSha256: 'u...='
    }
  },
  messageTimestamp: '1622268138',
  ephemeralOutOfSync: false
}

**Comment by azudindaem** [comment]
manage to solve the problem from discord channel..

    app.post('/api/replyText', async (req, res) => {
        var id_device = req.body.id_device;
        var jid = req.body.jid
        var messageId = req.body.messageId
        var message = req.body.message;

        const quotedMessage = await myclient[id_device].loadMessage(jid, messageId);

        try {
            const sentMsg  = await myclient[id_device].sendMessage (jid, message, MessageType.extendedText, { 
                quoted: quotedMessage 
            } );

            res.json({
                success: true,
                message: "Sending reply",
                data: sentMsg
            });
        
        } catch (err) {
            console.log(err);
        };

    })
