### ISSUE TITLE
ECONNRESET error

### ISSUE THREAD

**Issue by Pegorino82** [adiwajshing/Baileys#547]
```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
Got this error after example script was running about 3 hours.
https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle here says that node.js problem, but is there any solution to handle it while script is running?

**Comment by PurpShell** [comment]
this is not the full log. 
Please provide the full log

**Comment by Pegorino82** [comment]
unfortunally i lost it(
i cleaned up npm cache and reinstall node_modules and it is ok for now.
if i will catch such error again i will save log)

**Comment by Pegorino82** [comment]
Got it
```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @adiwajshing/baileys@3.5.1 example: `node --inspect -r ts-node/register Example/example.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @adiwajshing/baileys@3.5.1 example script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

and log from file
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'example'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'preexample', 'example', 'postexample' ]
5 info lifecycle @adiwajshing/baileys@3.5.1~preexample: @adiwajshing/baileys@3.5.1
6 info lifecycle @adiwajshing/baileys@3.5.1~example: @adiwajshing/baileys@3.5.1
7 verbose lifecycle @adiwajshing/baileys@3.5.1~example: unsafe-perm in lifecycle true
8 verbose lifecycle @adiwajshing/baileys@3.5.1~example: PATH:  ...
9 verbose lifecycle @adiwajshing/baileys@3.5.1~example: CWD: ...\Baileys
10 silly lifecycle @adiwajshing/baileys@3.5.1~example: Args: [ '/d /s /c', 'node --inspect -r ts-node/register Example/example.ts' ]
11 silly lifecycle @adiwajshing/baileys@3.5.1~example: Returned: code: 1  signal: null
12 info lifecycle @adiwajshing/baileys@3.5.1~example: Failed to exec example script
13 verbose stack Error: @adiwajshing/baileys@3.5.1 example: `node --inspect -r ts-node/register Example/example.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @adiwajshing/baileys@3.5.1
15 verbose cwd ...\Baileys
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "example"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error @adiwajshing/baileys@3.5.1 example: `node --inspect -r ts-node/register Example/example.ts`
22 error Exit status 1
23 error Failed at the @adiwajshing/baileys@3.5.1 example script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by PurpShell** [comment]
weird
