### ISSUE TITLE
Multi-device beta

### ISSUE THREAD

**Issue by thewh1teagle** [adiwajshing/Baileys#605]
Baileys doesn't work with latest whatsapp beta release of multi linked device to whatsapp web
when I scan the qr I get this error
```node
_unhandled_rejections_mode). (rejection id: 1)
(node:6796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6796) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:107:24)
    at WAConnection.sendBinary (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:87:18)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:668:41)
    at WAConnection.connect (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
(node:6796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6796) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:107:24)
    at WAConnection.sendBinary (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:88:18)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:668:41)
    at WAConnection.connect (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
(node:6796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:6796) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:107:24)
    at WAConnection.sendBinary (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:89:18)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:668:41)
    at WAConnection.connect (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
(node:6796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:6796) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:107:24)
    at WAConnection.sendBinary (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:90:18)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:668:41)
    at WAConnection.connect (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
(node:6796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:6796) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:107:24)
    at WAConnection.sendBinary (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:91:18)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:668:41)
    at WAConnection.connect (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
(node:6796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:6796) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:107:24)
    at WAConnection.sendBinary (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.query (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:230:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async WAConnection.relayWAMessage (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:315:13)
    at async WAConnection.sendMessage (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:25:9)
(node:6796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
INFO [2021-07-19 05:40:04.049 +0000] (6796): closed connection, reason close, reconnecting in a few seconds...
    class: "Baileys"
(node:6796) UnhandledPromiseRejectionWarning: BaileysError: close
    at WAConnection.onErr (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:190:56)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:668:41)
    at WAConnection.endConnection (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:417:14)
    at WAConnection.closeInternal (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:400:14)
    at WAConnection.unexpectedDisconnect (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:107:18)
    at WebSocket.<anonymous> (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:72:42)
    at WebSocket.emit (events.js:375:28)
    at WebSocket.emitClose (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\ws\lib\websocket.js:243:10)
    at TLSSocket.socketOnClose (C:\Users\User\Desktop\Files\code\my\whatsapp_bot\node_modules\ws\lib\websocket.js:1031:15)    
(node:6796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
INFO [2021-07-19 05:40:08.391 +0000] (6796): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
```

**Comment by PurpShell** [comment]
Please talk in the discord, so far no one has been able to use multi-device with baileys, and for a long time, we won't have a lot of progress, if you have been caught up on the discord, you would know we are so fucked to the level of having to rewrite: 

- Encryption and Decryption of media
- binary values and decoding incoming and outgoing messages
- having no fetch-from-websocket so far, meaning no persistence for storing messages, and you are essentially the cache itself :D
- libsignal-protocol and indexedDB taking over the world
- whole new `challenge`, that's the thing that proves that proves to the other end you are really whatsapp web connecting to their WS's.
At the end of the day, with only a few people and without @sigalor 's help because he understands the whatsapp and whatsapp web protocol properly, we are so fucked :cowboy_hat_face:

**Comment by PurpShell** [comment]
update we now hvae sigalor's hand on this, and a new repo sigalor/whatsapp-web-multi-device-reveng

**Comment by cryptoAlgorithm** [comment]
Wow that was really fast. Sigalor's really a genius lol 😄

**Comment by itacirgabral** [comment]
bump

POCs
https://github.com/pokearaujo/multidevice

**Comment by DerDjava** [comment]
> bump
> 
> POCs
> https://github.com/pokearaujo/multidevice

How to use this? Is there any documentations? Please

**Comment by PurpShell** [comment]
> > bump
> > POCs
> > https://github.com/pokearaujo/multidevice
> 
> How to use this? Is there any documentations? Please

It's called a research repo. Look at it well and it will tell you how to run it. it doesn't have an api etc. 
Instead, it does a bunch of tests and things automatically. 
It's not a package.
