### ISSUE TITLE
npm ERR! prepareGitDep npm ERR! Failed at the @adiwajshing/baileys@3.5.1 prepare script.

### ISSUE THREAD

**Issue by Ftwrr** [adiwajshing/Baileys#621]
npm ERR! prepareGitDep npm ERR! Failed at the @adiwajshing/baileys@3.5.1 prepare script.

**Comment by Ftwrr** [comment]
-----> Installing dependencies
       Installing node modules (package.json)
       npm ERR! prepareGitDep 1> 
       npm ERR! prepareGitDep > protobufjs@6.11.2 postinstall /tmp/npmcache.2G6AF/_cacache/tmp/git-clone-b987dd86/node_modules/protobufjs
       npm ERR! prepareGitDep > node scripts/postinstall
       npm ERR! prepareGitDep 
       npm ERR! prepareGitDep 
       npm ERR! prepareGitDep > @adiwajshing/baileys@3.5.1 prepare /tmp/npmcache.2G6AF/_cacache/tmp/git-clone-b987dd86
       npm ERR! prepareGitDep > tsc
       npm ERR! prepareGitDep 
       npm ERR! prepareGitDep node_modules/token-types/lib/index.d.ts(123,44): error TS2314: Generic type 'IGetToken<T>' requires 1 type argument(s).
       npm ERR! prepareGitDep node_modules/token-types/lib/index.d.ts(131,44): error TS2314: Generic type 'IGetToken<T>' requires 1 type argument(s).
       npm ERR! prepareGitDep 
       npm ERR! prepareGitDep 2> npm ERR! code ELIFECYCLE
       npm ERR! prepareGitDep npm ERR! errno 2
       npm ERR! prepareGitDep npm ERR! @adiwajshing/baileys@3.5.1 prepare: `tsc`
       npm ERR! prepareGitDep npm ERR! Exit status 2
       npm ERR! prepareGitDep npm ERR! 
       npm ERR! prepareGitDep npm ERR! Failed at the @adiwajshing/baileys@3.5.1 prepare script.
       npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       npm ERR! prepareGitDep 
       npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
       npm ERR! prepareGitDep npm ERR!     /tmp/npmcache.2G6AF/_logs/2021-07-30T02_31_28_814Z-debug.log
       npm ERR! prepareGitDep 
       npm ERR! premature close
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.2G6AF/_logs/2021-07-30T02_31_28_928Z-debug.log
-----> Build failed

**Comment by FaizBastomi** [comment]
use yarn

yarn add git+https://github.com/adiwajshing/Baileys.git

**Comment by Adiixyz** [comment]
> use yarn
> 
> yarn add git+https://github.com/adiwajshing/Baileys.git

i tried but error

internal/modules/cjs/loader.js:311
      throw err;
      ^

Error: Cannot find module '/data/data/com.termux/files/home/games-wabot/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/games-wabot/main.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/data/data/com.termux/files/home/games-wabot/node_modules/@adiwajshing/baileys/package.json',
  requestPath: '@adiwajshing/baileys'
}
Exited with code: 1

**Comment by Adiixyz** [comment]
> This issue is stale because it has been open 6 days with no activity. Remove the stale label or comment or this will be closed in 2 days

github bot gabut
