### ISSUE TITLE
[BUG]  Baileys error with whatsApp beata

### ISSUE THREAD

**Issue by SLdevilX** [adiwajshing/Baileys#631]
Baileys not response with whatsapp beata version please cheeck it & could you please fix it

**Comment by SLdevilX** [comment]
can use button messeges on normel whatsapp

**Comment by Sambosa711** [comment]
I can't send buttons on WhatsApp  or WhatsApp  whatsapp business 




========================


BaileysError: Unexpected status in 'action': Bad Request(400)
    at WAConnection.query (C:\Users\r2\Desktop\termuxBot\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:236:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async WAConnection.relayWAMessage (C:\Users\r2\Desktop\termuxBot\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:279:13)
    at async WAConnection.sendMessage (C:\Users\r2\Desktop\termuxBot\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:25:9)
    at async WAConnection.<anonymous> (C:\Users\r2\Desktop\termuxBot\min.js:70:15) {
  status: 400,
  context: {
    query: [ 'action', [Object], [Array] ],
    message: 'Bad Request',
    status: 400
  }
}
