### ISSUE TITLE
Multidevice beta version not working

### ISSUE THREAD

**Issue by Akash-Rathore** [adiwajshing/Baileys#697]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**
 
if joined multidevice in whatsapp not working

**Comment by tiesco238** [comment]
When trying the multidevice branch I am getting the following error on yarning the example, after scanning the qr code successfully:

```{"level":10,"time":1632398031282,"pid":24081,"hostname":"my.local","fromMe":false,"frame":{"tag":"stream:error","attrs":{"code":"401"},"content":[{"tag":"conflict","attrs":{"type":"device_removed"},"content":null}]},"msg":"communication"}
{"level":10,"time":1632398031282,"pid":24081,"hostname":"my.local","fromMe":false,"frame":{"tag":"xmlstreamend","attrs":{},"content":null},"msg":"communication"}
{"level":30,"time":1632398031282,"pid":24081,"hostname":"my.local","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"msg":"connection closed"}
```

Is there something wrong with my setup or how can I overcome this issue?
Thanks and kudos for the multidevice support!

**Comment by adiwajshing** [comment]
Need the entire log @tiesco238 , also the connection is supposed to restart after QR scan

**Comment by tiesco238** [comment]
This is the full log:

```$ node --inspect -r ts-node/register Example/example.ts
Debugger listening on ws://127.0.0.1:9229/aeec2d09-725e-4bcb-99b8-b97abb6b72a2
For help, see: https://nodejs.org/en/docs/inspector
connection update { connection: 'connecting', receivedPendingNotifications: false }
{"level":30,"time":1632402224646,"pid":84822,"hostname":"my.local","msg":"connected to WA Web"}
{"level":20,"time":1632402224800,"pid":84822,"hostname":"my.local","msg":"handshake recv from WA Web"}
{"level":30,"time":1632402224825,"pid":84822,"hostname":"my.local","msg":"handshake complete"}
{"level":30,"time":1632402224825,"pid":84822,"hostname":"my.local","msg":"not logged in, attempting registration..."}
{"level":10,"time":1632402225096,"pid":84822,"hostname":"my.local","msgId":"50997675","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"set","id":"50997675","xmlns":"md"},"content":[{"tag":"pair-device","attrs":{},"content":[{"tag":"ref","attrs":{},"content":{"type":"Buffer","data":[50,64,51,79,50,97,71,109,105,106,57,86,105,105,68,108,113,119,117,90,80,55,77,88,107,97,75,48,101,54,102,112,77,105,50,50,112,49,85,89,68,53,116,112,110,88,78,56,105,53,79,112,110,88,104,79,110,106,51,74,43,65,90,67,51,78,85,98,88,48,114,114,71,69,109,57,88,89,112,65,61,61]}},{"tag":"ref","attrs":{},"content":{"type":"Buffer","data":[50,64,65,102,119,68,77,90,86,107,76,55,116,82,54,86,103,54,103,100,83,65,50,111,75,122,112,115,50,71,110,47,113,57,107,89,54,89,119,101,83,49,55,115,110,75,51,53,65,69,49,67,85,103,49,80,53,81,88,55,121,73,66,119,73,81,90,103,76,88,98,111,112,77,54,118,106,79,69,119,61,61]}},{"tag":"ref","attrs":{},"content":{"type":"Buffer","data":[50,64,47,83,110,99,113,76,103,103,86,70,106,55,65,88,102,119,51,109,102,76,103,118,80,122,119,52,43,110,85,109,84,112,79,51,66,90,72,79,51,113,110,104,102,106,69,99,88,67,53,109,119,78,120,110,50,102,56,77,107,67,81,86,102,102,74,54,65,98,104,116,79,112,119,50,83,106,85,119,61,61]}},{"tag":"ref","attrs":{},"content":{"type":"Buffer","data":[50,64,74,115,116,110,66,97,120,50,111,80,99,109,79,87,75,110,89,90,120,65,103,111,51,83,65,55,112,108,88,54,57,105,103,66,54,103,111,67,70,68,112,109,76,51,105,52,67,111,118,85,82,117,70,97,84,56,121,88,43,81,89,47,122,104,72,79,52,104,82,116,112,122,71,54,57,103,54,81,61,61]}},{"tag":"ref","attrs":{},"content":{"type":"Buffer","data":[50,64,78,57,66,74,65,115,54,53,77,84,56,101,90,112,49,76,66,107,73,118,48,98,97,89,88,99,102,106,69,66,104,54,51,104,100,105,98,115,120,119,85,111,77,79,78,52,98,103,78,103,102,99,48,98,75,55,119,121,84,57,110,52,116,73,115,49,83,121,57,73,121,82,71,105,115,88,102,103,61,61]}},{"tag":"ref","attrs":{},"content":{"type":"Buffer","data":[50,64,116,80,54,65,106,74,115,119,50,117,73,121,76,121,107,71,122,71,48,54,70,108,99,74,108,78,70,83,76,74,120,100,81,80,88,109,86,112,118,88,106,71,83,70,87,77,76,104,112,57,70,57,104,66,84,74,79,109,90,120,72,103,117,53,47,103,112,82,75,109,98,55,47,47,69,75,104,81,61,61]}}]}]},"msg":"communication"}
connection update {
  qr: '2@3O2aGmij9ViiDlqwuZP7MXkaK0e6fpMi22p1UYD5tpnXN8i5OpnXhOnj3J+AZC3NUbX0rrGEm9XYpA==,HSXnd7O90BjfAUS9q1bWGXFMp66KK7UEyF0ig+P0F2I=,diSwO5VLnqpd+b0dXN66IxO7oN5snxTvCYfumNkueXg=,hitf4VFkR/6mi17oo3amqZHIQschHnP6SXV7PCfc7PM='
}
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ ██▀▀█▀▀▄ ▄ ▀█ ▄▀▀▄▀▀ ▄▀ █▄  █▄▀ ▄█▄ ▀██ ▄▄▄▄▄ █
█ █   █ █▀ ▄▄▀▀  █   ▀ ▀█ ▄█▀ ▄ ▄ ▀ ▀▀ ██ ▀▀▄▀█ █   █ █
█ █▄▄▄█ █▄▄█ █▀▀▄▀▄  ███▄ ▄▄▄   ▀▄██  ▄▀▀ ▄ ███ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█ ▀▄█ ▀▄▀▄█▄▀ █ █▄█ █▄█▄▀▄█▄█▄▀ █▄█▄█▄▄▄▄▄▄▄█
█▄ ███▄▄▄▀ ▀██▄  █▀▄▀ ██▀▄  ▄▄▀▀ █▀▀▄ █▀▄█▀  ▀▀▀▀  ▀▀██
█▄█ ▀▄█▄ ▀▄▄▄█▀   ▀▄▄▄ ▀ ▀ █▀▀▀ █  ▀▀█  ▄█▀▀ ▀▄▀██▄▄ ▀█
█ ▀█ ▀█▄ ▄ ▀ ▄█▄██ ▄ ▄▀▄█  ▀█▄ ▀█▄ ██▄▀██▄▄ ▀█▀▄█ ▄██▀█
█▄▄▄ ▀█▄▄▀ ▀▀▄▀▀▄▀ ▄▀ ▄ █▀▄ ███ ▄█ ▄ ▄█▀ ▄██▄▀▀▀▄▄▀ ▀▀█
███▄ ▀▄▄▄█ ▄ ▀▀███  ▀███ ▄   ▀▄▀█▀▀▄█▄ █ █ ▀▀█ █  █ ▄▄█
█▄ ▀█▄█▄▀▀  █▀ ▀█▄ ▀▄▄▄█▀ █▄ ▄▀▀ ▀█▀██▀  ▀▄█▀█▄█▄█▀█▀ █
█▀ ▀█ ▄▄▄▀▄ ▄▄▀█▀  ▄▀ ██▄▄▄  █▀▀ ▀▀   █ ▀▀ ▀  ▀ ▄ ▄▀▄██
█▀▄  ▄█▄▄▄ ██▄▄ ▀▀█ █ ▄▄▄▀ ▄█▀█▀█▄█▄█▀ ▄▄ █▀▀ ▀ ▄█ ████
█▀▀▄▄ ▄▄▄ ▀▄  ██  █ ▀▄█ █ ▄▄▄ ▀▀▀  ▄█ ▀▄▀▄▀ ▀ ▄▄▄ ▄▄  █
█▀█▄▄ █▄█ ▄ ▀█ █ ▄▀   █▄  █▄█ █▄██  ▀▀ ▀█ █ █ █▄█ █▀▄▀█
█▄▄▄▄▄▄▄▄▄▀▀▀▄ █ █▀▄▀▄█▀█▄▄ ▄▄ ▀▄█▀█ ▄ ██▀█▀█▄▄▄   ▄ ▀█
█ ▄  ██▄█  █▀▄ ▄ █▀▀▄██▀▄  ███▀▄ ▀ ▀  █▀█▄██  ▀  ▀▀█▄ █
█▀█▀▀██▄▀▄▀ ▀▀▀▀█▀▀▄▄ ▀▀ ▀ ▀██▀▀██  ▄▄ ▀█▀▄▀██▀██▀█ █▀█
██▀▄▀██▄ ▀▀ ▀  ███▀ ▀▄███▀▀█▀▄▄ █ ▀█▄▀██ ▀▄▀▄ ██ ▄▀██▀█
█▀█▄   ▄▀ ▄ ▄ █▄ ▄█▄ ▄  ▄▄█ ▄▄▄▀█▄▀▄█▄▀█▄    ▄ ▄▀   ▄▄█
█▀█▄ ▀█▄▀▀ ▄▄▄▄▄▄█ ▀█▀▄▀▀ █   ▀▀▄▄██▄▄▀ ▀██▀▄█▀█▄▄ ▀▀▀█
█▄█▀▀ ▀▄█▀▄ ▀▀▄▄ ▀█  █ ▀▄▄ █▀▀  ▄▀ █▄ ███▀▀ ▀▀▀ ▄▀▀▄  █
█▄ ▀▄▄▄▄▄ █▀ █▄▄ ▀▄▄▄ ▀ ▄ ▀███ ██▀▄▀ ▄▀▀▀  ▀▄▀  █▄▄█ ▄█
████▄██▄▄ ▄▄ █ ▄▀▀  ▄ █▀▀ ▄▄▄ ▄▀▀▀ ▀▄ ▀ ▄█▀ ▀ ▄▄▄ ▄▄ ▄█
█ ▄▄▄▄▄ █   ▀ █ ▀▄▄█▄▀█▀▀ █▄█ ▄▀▄ ▄  ▄ ▄█   ▀ █▄█  █▀██
█ █   █ ██▀▀██  █▄█▀▀▄▀▄   ▄▄▄ ▀▀  ▄█ ▀▄█ █  ▄ ▄ ▄▄█▀▄█
█ █▄▄▄█ █▀▀█ █▄██▀ ▄▄ ▀▄▀▄▄▄▄▄   ▄ ▀  ▄▄█▀▄█ ▀▀ █▄▀ █ █
█▄▄▄▄▄▄▄█▄▄██▄▄▄▄█▄▄▄▄▄█▄▄▄████████▄▄▄█████▄▄██▄███████

{"level":10,"time":1632402240695,"pid":84822,"hostname":"my.local","msgId":"1771837674","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"set","id":"1771837674","xmlns":"md"},"content":[{"tag":"pair-success","attrs":{},"content":[{"tag":"platform","attrs":{"name":"android"},"content":null},{"tag":"device-identity","attrs":{},"content":{"type":"Buffer","data":[10,116,10,14,8,254,245,162,183,5,16,190,246,177,138,6,24,1,18,32,40,200,92,237,89,252,205,128,228,253,237,240,183,146,18,117,220,193,241,42,87,219,29,233,195,21,141,89,144,31,5,15,26,64,230,106,36,169,196,181,37,234,74,22,249,85,42,174,171,6,73,98,132,209,96,207,155,78,42,143,239,236,221,20,135,77,14,10,231,179,12,89,253,126,164,106,223,55,20,226,216,161,89,220,206,142,222,126,71,144,253,182,224,246,148,199,250,11,18,32,230,122,230,68,60,183,13,6,144,146,135,225,23,190,4,165,221,85,95,63,72,227,223,65,137,89,97,5,184,93,138,206]}},{"tag":"device","attrs":{"jid":"31627037526:5@s.whatsapp.net"},"content":null}]}]},"msg":"communication"}
{"level":20,"time":1632402240697,"pid":84822,"hostname":"my.local","msg":"pair success recv"}
{"level":20,"time":1632402240708,"pid":84822,"hostname":"my.local","msg":"pairing configured successfully"}
{"level":30,"time":1632402240709,"pid":84822,"hostname":"my.local","jid":"31627037526:5@s.whatsapp.net","msg":"registered connection, restart server"}
saving pre-keys
connection update { isNewLogin: true, qr: undefined }
{"level":30,"time":1632402240710,"pid":84822,"hostname":"my.local","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"},"headers":{}}},"msg":"connection closed"}
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Restart Required
        at WebSocket.<anonymous> (/Users/mylocal/laravelapps/mdwactest/node_modules/@adiwajshing/baileys/src/Socket/socket.ts:429:17) {
      data: null,
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2021-09-23T13:04:00.711Z
  }
}
{"level":30,"time":1632402240858,"pid":84822,"hostname":"my.local","msg":"connected to WA Web"}
{"level":20,"time":1632402240896,"pid":84822,"hostname":"my.local","msg":"handshake recv from WA Web"}
{"level":30,"time":1632402240916,"pid":84822,"hostname":"my.local","msg":"handshake complete"}
{"level":30,"time":1632402240916,"pid":84822,"hostname":"my.local","msg":"logging in..."}
{"level":10,"time":1632402241218,"pid":84822,"hostname":"my.local","fromMe":false,"frame":{"tag":"success","attrs":{"t":"1632402241","props":"26","location":"cln","abprops":"0","creation":"1632402239","companion_enc_static":"l7oZs6UQNRAJY5cKHEA/Bz4sLylPGQuODpqCrdAYvi8="},"content":null},"msg":"communication"}
{"level":30,"time":1632402241551,"pid":84822,"hostname":"my.local","msg":"uploaded pre-keys"}
{"level":10,"time":1632402241673,"pid":84822,"hostname":"my.local","fromMe":false,"frame":{"tag":"ib","attrs":{"from":"@s.whatsapp.net"},"content":[{"tag":"edge_routing","attrs":{},"content":[{"tag":"routing_info","attrs":{},"content":{"type":"Buffer","data":[8,9,8,11]}}]}]},"msg":"communication"}
{"level":10,"time":1632402241674,"pid":84822,"hostname":"my.local","fromMe":false,"frame":{"tag":"ib","attrs":{"from":"@s.whatsapp.net"},"content":[{"tag":"dirty","attrs":{"type":"account_sync","timestamp":"1632402241"},"content":null}]},"msg":"communication"}
{"level":10,"time":1632402241675,"pid":84822,"hostname":"my.local","msgId":"4.6-1","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"result","id":"4.6-1"},"content":[{"tag":"active","attrs":{},"content":null}]},"msg":"communication"}
{"level":10,"time":1632402241894,"pid":84822,"hostname":"my.local","fromMe":false,"frame":{"tag":"ib","attrs":{"from":"@s.whatsapp.net"},"content":[{"tag":"offline","attrs":{"count":"0"},"content":null}]},"msg":"communication"}
{"level":10,"time":1632402242014,"pid":84822,"hostname":"my.local","msgId":"608965247","fromMe":false,"frame":{"tag":"notification","attrs":{"from":"31627037526@s.whatsapp.net","type":"account_sync","id":"608965247","t":"1632402241"},"content":[{"tag":"devices","attrs":{"dhash":"2:bTpkKl8W"},"content":[{"tag":"device","attrs":{"jid":"31627037526@s.whatsapp.net"},"content":null},{"tag":"device","attrs":{"jid":"31627037526:5@s.whatsapp.net"},"content":null},{"tag":"key-index-list","attrs":{"ts":"1632402238"},"content":{"type":"Buffer","data":[10,18,8,254,245,162,183,5,16,190,246,177,138,6,24,1,34,2,0,1,18,64,214,27,130,149,68,94,4,38,228,246,139,87,38,88,228,232,36,42,238,216,96,248,96,8,199,199,165,7,58,123,46,93,58,202,129,185,205,235,218,34,114,94,250,122,128,181,57,81,132,205,74,190,168,67,35,31,21,220,66,57,8,32,57,1]}}]}]},"msg":"communication"}
{"level":10,"time":1632402242014,"pid":84822,"hostname":"my.local","msgId":"4.6-2","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"result","id":"4.6-2"},"content":[{"tag":"list","attrs":{},"content":null}]},"msg":"communication"}
blocklist {
  tag: 'iq',
  attrs: { from: '@s.whatsapp.net', type: 'result', id: '4.6-2' },
  content: [ { tag: 'list', attrs: {}, content: null } ]
}
{"level":20,"time":1632402242016,"pid":84822,"hostname":"my.local","msgId":"608965247","msg":"ack notification"}
{"level":10,"time":1632402242023,"pid":84822,"hostname":"my.local","msgId":"4.6-0","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"result","id":"4.6-0"},"content":null},"msg":"communication"}
{"level":10,"time":1632402242615,"pid":84822,"hostname":"my.local","msgId":"1597071102","fromMe":false,"frame":{"tag":"notification","attrs":{"from":"@s.whatsapp.net","type":"encrypt","id":"1597071102","t":"1632402242"},"content":[{"tag":"count","attrs":{"value":"0"},"content":null}]},"msg":"communication"}
{"level":20,"time":1632402242615,"pid":84822,"hostname":"my.local","msgId":"1597071102","msg":"ack notification"}
{"level":30,"time":1632402242615,"pid":84822,"hostname":"my.local","msg":"recv all pending notifications"}
{"level":10,"time":1632402243078,"pid":84822,"hostname":"my.local","fromMe":false,"frame":{"tag":"stream:error","attrs":{"code":"401"},"content":[{"tag":"conflict","attrs":{"type":"device_removed"},"content":null}]},"msg":"communication"}
{"level":10,"time":1632402243078,"pid":84822,"hostname":"my.local","fromMe":false,"frame":{"tag":"xmlstreamend","attrs":{},"content":null},"msg":"communication"}
{"level":30,"time":1632402243078,"pid":84822,"hostname":"my.local","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"msg":"connection closed"}
✨  Done in 28.64s.
```

**Comment by tiesco238** [comment]
By the way, after restarting the example with authentication enabled I get the following logs and will automatically quit the process afterwards:

```
$ node --inspect -r ts-node/register Example/example.ts
Debugger listening on ws://127.0.0.1:9229/9e6a2087-15eb-4b0a-9072-aca2e0e4a8fc
For help, see: https://nodejs.org/en/docs/inspector
connection update { connection: 'connecting', receivedPendingNotifications: false }
{"level":30,"time":1632402975602,"pid":14402,"hostname":"my.local","msg":"connected to WA Web"}
{"level":20,"time":1632402975634,"pid":14402,"hostname":"my.local","msg":"handshake recv from WA Web"}
{"level":30,"time":1632402975657,"pid":14402,"hostname":"my.local","msg":"handshake complete"}
{"level":30,"time":1632402975657,"pid":14402,"hostname":"my.local","msg":"logging in..."}
{"level":10,"time":1632402980272,"pid":14402,"hostname":"my.local","fromMe":false,"frame":{"tag":"failure","attrs":{"reason":"401","location":"odn"},"content":null},"msg":"communication"}
{"level":30,"time":1632402980272,"pid":14402,"hostname":"my.local","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":401,"payload":{"statusCode":401,"error":"Unauthorized","message":"Logged Out"},"headers":{}}},"msg":"connection closed"}
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Logged Out
        at WebSocket.<anonymous> (/Users/mylocal/laravelapps/mdwactest/node_modules/@adiwajshing/baileys/src/Socket/socket.ts:445:13)
        at WebSocket.emit (events.js:223:5)
        at WebSocket.EventEmitter.emit (domain.js:475:20)
        at /Users/mylocal/laravelapps/mdwactest/node_modules/@adiwajshing/baileys/src/Socket/socket.ts:238:39
        at Array.forEach (<anonymous>)
        at /Users/mylocal/laravelapps/mdwactest/node_modules/@adiwajshing/baileys/src/Socket/socket.ts:236:33
        at Object.decodeFrame (/Users/mylocal/laravelapps/mdwactest/node_modules/@adiwajshing/baileys/src/Utils/noise-handler.ts:162:5)
        at WebSocket.onMessageRecieved (/Users/mylocal/laravelapps/mdwactest/node_modules/@adiwajshing/baileys/src/Socket/socket.ts:218:15)
        at WebSocket.emit (events.js:223:5)
        at WebSocket.EventEmitter.emit (domain.js:475:20) {
      data: null,
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2021-09-23T13:16:20.273Z
  }
}
{"level":30,"time":1632402980786,"pid":14402,"hostname":"my.local","msg":"connected to WA Web"}
{"level":20,"time":1632402981269,"pid":14402,"hostname":"my.local","msg":"handshake recv from WA Web"}
{"level":30,"time":1632402981295,"pid":14402,"hostname":"my.local","msg":"handshake complete"}
{"level":30,"time":1632402981295,"pid":14402,"hostname":"my.local","msg":"logging in..."}
{"level":10,"time":1632402985003,"pid":14402,"hostname":"my.local","fromMe":false,"frame":{"tag":"failure","attrs":{"reason":"401","location":"vll"},"content":null},"msg":"communication"}
{"level":30,"time":1632402985003,"pid":14402,"hostname":"my.local","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":401,"payload":{"statusCode":401,"error":"Unauthorized","message":"Logged Out"},"headers":{}}},"msg":"connection closed"}
✨  Done in 19.39s.
```

**Comment by adiwajshing** [comment]
My guess is you logged out or closed WA while it was connecting, might want to try again

**Comment by tiesco238** [comment]
Thanks for the response @adiwajshing but i tried it multiple times, each time with the same results. Does anyone experience the same problem?

**Comment by PurpShell** [comment]
> My guess is you logged out or closed WA while it was connecting, might want to try again

I think I had this problem before, it will scan, then log in for a few seconds, then say there is an authentication error, then log out and restart..

i think there are some things WA will change to make that better I think.. On the WBI server, pretty much 50% of beta users have faced this

**Comment by Manjit2003** [comment]
Any update on this issue?
Now its occuring too much

**Comment by alirezadigi** [comment]
Same here ...
Error both in baileys and phone.

**Comment by alirezadigi** [comment]
dear @adiwajshing 
do you have any ideas for us?

**Comment by Manjit2003** [comment]
No I won't let you die

**Comment by alirezadigi** [comment]
What should we do?

**Comment by Auties00** [comment]
> The non-MD had a connection close if you did not send presence updates. I have not migrated to MD yet but may that be the root of the issue? @Auties00 have you ever finished your logger for MD? So maybe we could log what happens between second 5555 and 6100 in an otherwise-inactive browser window? Of course the keepalive or whatever comes up could also be sent much sooner than than but the server has a timeout for 100 minutes of not receiving that signal.
> 
> In any case, I think if it only happens after 6000 seconds it's not a high-priority issue for now, one can just reconnect I guess.

Yes, it's already completed, Kotlin, IntelliJ or both though have decided to die though. 
Might take me a while to figure out why.

**Comment by alsa-kode** [comment]
In case it helps, 6006 seconds timeout

{"level":10,"time":1633890791594,"pid":29,"hostname":"d160b413fc72","fromMe":false,"frame":{"tag":"xmlstreamend","attrs":{},"content":null},"msg":"communication"}
{"level":30,"time":1633890791594,"pid":29,"hostname":"d160b413fc72","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"msg":"connection closed"}
Done in 6006.23s.

**Comment by Auties00** [comment]
> The non-MD had a connection close if you did not send presence updates. I have not migrated to MD yet but may that be the root of the issue? @Auties00 have you ever finished your logger for MD? So maybe we could log what happens between second 5555 and 6100 in an otherwise-inactive browser window? Of course the keepalive or whatever comes up could also be sent much sooner than than but the server has a timeout for 100 minutes of not receiving that signal.
> 
> In any case, I think if it only happens after 6000 seconds it's not a high-priority issue for now, one can just reconnect I guess.

It's ready. If you need it, tell me

**Comment by alirezadigi** [comment]
> > The non-MD had a connection close if you did not send presence updates. I have not migrated to MD yet but may that be the root of the issue? @Auties00 have you ever finished your logger for MD? So maybe we could log what happens between second 5555 and 6100 in an otherwise-inactive browser window? Of course the keepalive or whatever comes up could also be sent much sooner than than but the server has a timeout for 100 minutes of not receiving that signal.
> > In any case, I think if it only happens after 6000 seconds it's not a high-priority issue for now, one can just reconnect I guess.
> 
> It's ready. If you need it, tell me

@Auties00 could you please put code here?
What should we do exactly?

**Comment by Ergo-proxy9847** [comment]
There are sometimes when some members in a group can see the see the messages sent by the bot and some cant

**Comment by Auties00** [comment]
> @Auties00 thanks but i dont know kotlin Do you have any js code?

I've created a release to make things easier:
https://github.com/Auties00/whatsappweb4j-request-analyzer/releases/tag/2.0

**Comment by alirezadigi** [comment]
Cant login with md yet .

**Comment by dncore40** [comment]
i was trying example.ts and scanned the qr, then it was ok and work fine, until i killed a running example and logout the device from whatsapp and then i try to scan again (after delete auth_info_multi.json) it had same error like @tiesco238 
 had. And now i still cant login even after changing with another phone and another number whatsapp beta. 
 sorry for my bad english

**Comment by Romerio** [comment]
Hi, I had this exact problem.

The reason: In the code snippet I used to start the application I wasn't using functions "saveState" or "loadState"
The solution for me was: Use functions  "saveState" and "loadState" as they are in the sample file "example.ts".

**Comment by muhamad-fadla** [comment]
Hi, I'm having the same problem,

the way I fix it is to first connect whatapp md to web.whatsapp.com first, then try to scan on bailyes md.
it worked for me

sorry for my bad english

**Comment by alirezadigi** [comment]
@muhamad-fadla 
Hi Dear
I think this works now!
