### ISSUE TITLE
404 in getBroadcastListInfo

### ISSUE THREAD

**Issue by alexandrepossebom** [adiwajshing/Baileys#698]
I'm trying to get user information from a list:

```
let x = await client.getBroadcastListInfo('1632400734@broadcast');
console.log(x);

```

But I get this error for all my lists:

```
BaileysError: Unexpected status in 'query': Not Found(404)
    at WAConnection.query (/Users/alexandre/Devel/wpbroadcast/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:237:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async starts (/Users/alexandre/Devel/wpbroadcast/index.js:62:11) {
  status: 404,
  context: {
    query: [ 'query', 'contact', '1632400734@broadcast' ],
    message: 'Not Found',
    status: 404
  }
}
```

**Comment by alexandrepossebom** [comment]
anybody can help with this bug?
