### ISSUE TITLE
Multidevice beta version Example restarts after QR read

### ISSUE THREAD

**Issue by lonelypx** [adiwajshing/Baileys#701]
**Describe the bug**
Multidevice beta version Example restarts after QR read

**To Reproduce**
1. Clone the repo
2. yarn example
3. Scan the QR code

NFO [2021-09-24 17:21:47.891 +0000] (29127): validated connection successfully
    class: "Baileys"
DEBUG [2021-09-24 17:21:47.951 +0000] (29127): sent init queries
    class: "Baileys"
INFO [2021-09-24 17:21:47.951 +0000] (29127): opened connection to WhatsApp Web
    class: "Baileys"
encountered error: TypeError: Cannot read property 'toString' of undefined
(node:29127) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:123:10)
    at Object.aesEncrypt (/opt/Baileys/src/WAConnection/Utils.ts:82:24)
    at WAConnection.sendBinary (/opt/Baileys/src/WAConnection/0.Base.ts:336:26)
    at WAConnection.<anonymous> (/opt/Baileys/src/WAConnection/4.Events.ts:21:18)
    at WAConnection.emit (events.js:314:20)
    at WAConnection.EventEmitter.emit (domain.js:483:12)
    at WAConnection.emit (/opt/Baileys/src/WAConnection/4.Events.ts:716:72)
(node:29127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29127) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:29127) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:123:10)
    at Object.aesEncrypt (/opt/Baileys/src/WAConnection/Utils.ts:82:24)
    at WAConnection.sendBinary (/opt/Baileys/src/WAConnection/0.Base.ts:336:26)
    at WAConnection.<anonymous> (/opt/Baileys/src/WAConnection/4.Events.ts:22:18)
    at WAConnection.emit (events.js:314:20)
    at WAConnection.EventEmitter.emit (domain.js:483:12)
    at WAConnection.emit (/opt/Baileys/src/WAConnection/4.Events.ts:716:72)
(node:29127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:29127) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:123:10)
    at Object.aesEncrypt (/opt/Baileys/src/WAConnection/Utils.ts:82:24)
    at WAConnection.sendBinary (/opt/Baileys/src/WAConnection/0.Base.ts:336:26)
    at WAConnection.<anonymous> (/opt/Baileys/src/WAConnection/4.Events.ts:23:18)
    at WAConnection.emit (events.js:314:20)
    at WAConnection.EventEmitter.emit (domain.js:483:12)
    at WAConnection.emit (/opt/Baileys/src/WAConnection/4.Events.ts:716:72)
(node:29127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:29127) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:123:10)
    at Object.aesEncrypt (/opt/Baileys/src/WAConnection/Utils.ts:82:24)
    at WAConnection.sendBinary (/opt/Baileys/src/WAConnection/0.Base.ts:336:26)
    at WAConnection.<anonymous> (/opt/Baileys/src/WAConnection/4.Events.ts:24:18)
    at WAConnection.emit (events.js:314:20)
    at WAConnection.EventEmitter.emit (domain.js:483:12)
    at WAConnection.emit (/opt/Baileys/src/WAConnection/4.Events.ts:716:72)
(node:29127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:29127) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:123:10)
    at Object.aesEncrypt (/opt/Baileys/src/WAConnection/Utils.ts:82:24)
    at WAConnection.sendBinary (/opt/Baileys/src/WAConnection/0.Base.ts:336:26)
    at WAConnection.<anonymous> (/opt/Baileys/src/WAConnection/4.Events.ts:25:18)
    at WAConnection.emit (events.js:314:20)
    at WAConnection.EventEmitter.emit (domain.js:483:12)
    at WAConnection.emit (/opt/Baileys/src/WAConnection/4.Events.ts:716:72)
(node:29127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:29127) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:123:10)
    at Object.aesEncrypt (/opt/Baileys/src/WAConnection/Utils.ts:82:24)
    at WAConnection.sendBinary (/opt/Baileys/src/WAConnection/0.Base.ts:336:26)
    at WAConnection.<anonymous> (/opt/Baileys/src/WAConnection/4.Events.ts:26:18)
    at WAConnection.emit (events.js:314:20)
    at WAConnection.EventEmitter.emit (domain.js:483:12)
    at WAConnection.emit (/opt/Baileys/src/WAConnection/4.Events.ts:716:72)
(node:29127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

<img width="351" alt="image" src="https://user-images.githubusercontent.com/6532656/134716679-3b4c5c57-4502-4e93-bc87-447b4ca633f5.png">

**Comment by lonelypx** [comment]
sorry worng repo :(
