### ISSUE TITLE
[BUG] Connection Timeout (multi-device) 

### ISSUE THREAD

**Issue by TentacleSama4254** [adiwajshing/Baileys#709]
Hi,
I'm running the code in example.ts to log messages in the ```muti-device``` branch, sending and receiving messages seem to work fine. 

But after a few minutes of being connected the client stops logging and receiving messages. And the logs only show 
![aaecfe1e-d3ed-43ba-a5b6-f2e258d3366a](https://user-images.githubusercontent.com/74726248/135214699-026fab12-f1df-4c39-885d-2d6e2a8ab39d.png)

The only way I can get it back to work is by deleting the credentials and re-scanning the Qr code again, but the same thing seems to keep happening.

>I didn't change the method of saving/loading credentials provided in the example.ts
>tried running the client locally and on a server
>logs on restart
[logs (1).txt](https://github.com/adiwajshing/Baileys/files/7249429/logs.1.txt)
It receives the read/delivery receipts and goes back to being idle

Not sure if this is just for me or if any others seem to face the same bug

**Comment by ramacatur** [comment]
Me too. Maybe any idea how to get new session without rescan?

**Comment by AffanTheBest** [comment]
@TentacleSama4254 I've just started to use baileys and I got my basic code working using `npm i @adiwajshing/baileys`.

But when I checked out multidevice branch and tried that example written over there it failed to work. 
I got error 
```
PS C:\Users\siddi\Downloads\Projects> node whatsapp.js
(node:14064) UnhandledPromiseRejectionWarning: TypeError: makeWASocket is not a function
    at connectToWhatsApp (C:\Users\siddi\Downloads\Projects\whatsapp.js:24:18)
    at Object.<anonymous> (C:\Users\siddi\Downloads\Projects\whatsapp.js:48:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47(Use `node --trace-warnings ...` to show where the warning was created)(node:14064) UnhandledPromiseRejectio
```nWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My Code:
```js
const makeWASocket = require('@adiwajshing/baileys-md');
async function connectToWhatsApp () {
    const conn = makeWASocket({
        // can provide additional config here
        printQRInTerminal: true
    })
    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = (lastDisconnect.error)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                sock = startSock()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    })
    sock.ev.on('messages.upsert', m => {
        console.log(JSON.stringify(m, undefined, 2))
        console.log('replying to', m.messages[0].key.remoteJid)
        sendMessageWTyping({ text: 'Hello there!' })
    })
}
connectToWhatsApp()
```

**### So Can you please share your code with me?**

**Comment by TentacleSama4254** [comment]
@AffanTheBest I'm just running
 https://github.com/adiwajshing/Baileys/blob/multi-device/Example/example.ts

Without editing anything

**Comment by frmdeveloper** [comment]
baileys just updated. Supports multi-device features

**Comment by tarikhagustia** [comment]
same, i received stream:error with 503 code, maybe whatsapp block our connection. or we don't properly sending something like ack status to whatsapp server

**Comment by frmdeveloper** [comment]
How to write code to commonjs ?

**Comment by frmdeveloper** [comment]
> @TentacleSama4254 I've just started to use baileys and I got my basic code working using `npm i @adiwajshing/baileys`.
> 
> But when I checked out multidevice branch and tried that example written over there it failed to work. I got error
> 
> ```
> PS C:\Users\siddi\Downloads\Projects> node whatsapp.js
> (node:14064) UnhandledPromiseRejectionWarning: TypeError: makeWASocket is not a function
>     at connectToWhatsApp (C:\Users\siddi\Downloads\Projects\whatsapp.js:24:18)
>     at Object.<anonymous> (C:\Users\siddi\Downloads\Projects\whatsapp.js:48:1)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>     at internal/main/run_main_module.js:17:47(Use `node --trace-warnings ...` to show where the warning was created)(node:14064) UnhandledPromiseRejectio
> ```nWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:14064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```
> 
> My Code:
> 
> ```js
> const makeWASocket = require('@adiwajshing/baileys-md');
> async function connectToWhatsApp () {
>     const conn = makeWASocket({
>         // can provide additional config here
>         printQRInTerminal: true
>     })
>     sock.ev.on('connection.update', (update) => {
>         const { connection, lastDisconnect } = update
>         if(connection === 'close') {
>             const shouldReconnect = (lastDisconnect.error)?.output?.statusCode !== DisconnectReason.loggedOut
>             console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
>             // reconnect if not logged out
>             if(shouldReconnect) {
>                 sock = startSock()
>             }
>         } else if(connection === 'open') {
>             console.log('opened connection')
>         }
>     })
>     sock.ev.on('messages.upsert', m => {
>         console.log(JSON.stringify(m, undefined, 2))
>         console.log('replying to', m.messages[0].key.remoteJid)
>         sendMessageWTyping({ text: 'Hello there!' })
>     })
> }
> connectToWhatsApp()
> ```
> 
> **### So Can you please share your code with me?**

use es6 only

**Comment by TentacleSama4254** [comment]
![3b023e4e-1c35-4fc5-96bc-8168bfc03356.png](https://user-images.githubusercontent.com/74726248/135486164-bb36ec1f-d737-40be-ae73-bc0fad49a591.png)
