### ISSUE TITLE
[BUG] error yarn example (multi device)

### ISSUE THREAD

**Issue by scoder37** [adiwajshing/Baileys#716]
root@vpn1:/multi# yarn example
yarn run v1.22.15
$ node --inspect -r ts-node/register Example/example.ts
Debugger listening on ws://127.0.0.1:9229/fe1b9742-eb4b-42b3-aced-36c3cfdef9a8
For help, see: https://nodejs.org/en/docs/inspector
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'ts-node/register'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1276:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:484:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:78:3)
    at node:internal/main/run_main_module:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@vpn1:/multi#

**Comment by scoder37** [comment]
eror scan


INFO [2021-10-04 14:36:55.567 +0000] (17911): validated connection successfully
    class: "Baileys"
DEBUG [2021-10-04 14:36:55.571 +0000] (17911): sent init queries
    class: "Baileys"
INFO [2021-10-04 14:36:55.571 +0000] (17911): opened connection to WhatsApp Web
    class: "Baileys"
encountered error: TypeError: Cannot read properties of undefined (reading 'toString')
TypeError: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:576:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/multi/src/WAConnection/Utils.ts:81:24)
    at WAConnection.sendBinary (/multi/src/WAConnection/0.Base.ts:336:26)
    at WAConnection.<anonymous> (/multi/src/WAConnection/4.Events.ts:21:18)
    at WAConnection.emit (node:events:390:28)
    at WAConnection.emit (node:domain:475:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

![Screenshot (5)](https://user-images.githubusercontent.com/90820338/135871263-5992341f-2e8a-4d41-a834-746b3b4fc7cb.png)

**Comment by tiesco238** [comment]
Running the following command fixed the problem for me:

npm install ts-node

**Comment by scoder37** [comment]
help bro error scan qr

**Comment by tiesco238** [comment]
install qrcode terminal package
```npm install qrcode-terminal```

include ```var qrcode = require('qrcode-terminal')``` at the top of example.

End of 'connection.update' add:
```
	if(update.qr !== undefined) {
        qrcode.generate(update.qr, { small: true} );
	}
```

save and compile and run

**Comment by scoder37** [comment]
tq bro work
