### ISSUE TITLE
How use javascript?

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#721]
`Error: Cannot find module '/home/frmdev/frmdev/node_modules/@adiwajshing/baileys-md/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:320:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:533:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at eval (eval at exports.chatupdate (/home/frmdev/frmdev/index.js:2696:21), <anonymous>:2:16)
    at eval (eval at exports.chatupdate (/home/frmdev/frmdev/index.js:2696:21), <anonymous>:2:53)
    at Object.exports.chatupdate (/home/frmdev/frmdev/index.js:2696:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/frmdev/frmdev/node_modules/@adiwajshing/baileys-md/package.json',
  requestPath: '@adiwajshing/baileys-md'
}`

**Comment by vlamizzz02** [comment]
Duh..

**Comment by BochilGaming** [comment]
> `Error: Cannot find module '/home/frmdev/frmdev/node_modules/@adiwajshing/baileys-md/lib/index.js'. Please verify that the package.json has a valid "main" entry at tryPackage (internal/modules/cjs/loader.js:320:19) at Function.Module._findPath (internal/modules/cjs/loader.js:533:18) at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27) at Function.Module._load (internal/modules/cjs/loader.js:745:27) at Module.require (internal/modules/cjs/loader.js:961:19) at require (internal/modules/cjs/helpers.js:92:18) at eval (eval at exports.chatupdate (/home/frmdev/frmdev/index.js:2696:21), <anonymous>:2:16) at eval (eval at exports.chatupdate (/home/frmdev/frmdev/index.js:2696:21), <anonymous>:2:53) at Object.exports.chatupdate (/home/frmdev/frmdev/index.js:2696:21) at processTicksAndRejections (internal/process/task_queues.js:95:5) { code: 'MODULE_NOT_FOUND', path: '/home/frmdev/frmdev/node_modules/@adiwajshing/baileys-md/package.json', requestPath: '@adiwajshing/baileys-md' }`

```bash
yarn add github:adiwajshing/baileys#multi-device
```

**Comment by frmdeveloper** [comment]
`const {default: makeWASocket} = require('@adiwajshing/baileys-md')`

I've found the solution
