### ISSUE TITLE
Sessions Mult-devices

### ISSUE THREAD

**Issue by sudorafa** [adiwajshing/Baileys#732]
when l read:
someone help me 😪

`import makeWASocket, { BufferJSON } from '@adiwajshing/baileys-md'
import * as fs from 'fs'

// will initialize a default in-memory auth session
const conn = makeSocket() 
// this will be called as soon as the credentials are updated
conn.ev.on ('auth-state.update', () => {
    // save credentials whenever updated
    console.log ('credentials updated!')
    const authInfo = conn.authState // get all the auth info we need to restore this session
    // save this info to a file
    fs.writeFileSync(
        './auth_info.json', 
        JSON.stringify(authInfo, BufferJSON.replacer, 2)
    ) 
})
`

Result:

{"level":30,"time":1634008088256,"pid":7831,"hostname":"MacBookl.local","class":"baileys","msg":"connected to WA Web"}
{"level":30,"time":1634008088400,"pid":7831,"hostname":"MacBookl.local","class":"baileys","msg":"handshake complete"}
{"level":30,"time":1634008088400,"pid":7831,"hostname":"MacBookl.local","class":"baileys","msg":"not logged in, attempting registration..."}
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄ ▀   ▀ █▄▀▀█ █ ▄██ ▄▄  ██▀█▀ █▀▄▄ ▀██ ▄▄▄▄▄ █
█ █   █ █  ▀ ▀▀▄█▄ ▀▄█▄▄▀▄█▀▄█▀▀▀█▄█▀▀█ █▄▀▀▄▀█ █   █ █
█ █▄▄▄█ █▄▄▄█▀█▀ █▄ ▄▄█▄█ ▄▄▄ ▀▀ ▄▄██▀▄  ▀█ ███ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█▄█ █▄█ █▄█ █▄▀ █▄█ ▀▄█▄█▄▀▄█ █ ▀▄█ █▄▄▄▄▄▄▄█
█   ▄█▀▄█ ▀▀▄▄█▄█ ▄█ ██ ▀▄▄ ▄▄ ▀█▀██▄▀ █▄ █ █▄▄██▄ ▄▀▄█
█▀▄  ▀ ▄███  █▄█▀▄█ ▀▄▄▀▀███▄▀ ▄▄ █▀ ▀█▄ █▀▄███ ▄▀▄█▄▀█
█▄█ ▀▀▄▄██▀▄█▄ ▀▄▄█ ▀ ▀▀███ ▀▀█▄▄▀█▄█▄▀▀█▀█▄   ▄▄▄ ▀███
█▄▄  █ ▄ ▄ ▀▄▀ █▀ ███████ ▀▄▀ ▀▀▀▀▄█▀█▄  ██▄█▄▄█▀▄ ▄  █
█▄ ▄▀ ▀▄▄█▄█▀██▄▄▀██▄█▄█▀▀█▄ ▀▀▄   ▀▄██▄ █▀██▄▀ ▀▀ ▄ ▀█
█ ▄▀▀▀█▄▀▄ █  ▄███▀▄ ▀▄  ██ ▀█▀ ██▄▄█ ▀▀█▀▀▄▄ ▀▄▄   ███
█▄▀▄▀▄▀▄▄▄▄▄ █▄▀▄▄▀█▀█▄▄▄▀█    ▀▀▀▄▄▀█ ▄ ▄▀ █▄▄▄▄▀█▄ ▀█
██▄ █▄▄▄▄█▀█▀█ ▀▀▀▀▄▄▀▄ █▄▄▄▄█▀█▄ ▀█    ▀▄ ▀▀█ ▀▀ ▄█ ▀█
█▀ ▄▀ ▄▄▄   ▀ ▄  ▀ ▄▀▀▀▀  ▄▄▄ ▄███▄█▄  ▀█▀▀█  ▄▄▄ ▄▀▄▀█
██▄▀▀ █▄█   ▀▄▀ █▀ ██▀▀▀  █▄█   █▀ ▀▄█▄▄ ▄▄▄█ █▄█ ▀▄ ▄█
███ ▀ ▄▄  ▀▀█  ▄▄ ██▀█▄▀▀▄ ▄  ▀▄▄▄▄▀█▀██ ██▄▀▄   ▄▀ ▀▀█
█ ▄ █ ▄▄ ▀▀█▄ ▀▀█▀█▄█▄▀██ ▀▀▀█▀▄▀ █▄ █▀ ▄▀ ▀ ▄█▀█▄▀ ███
█▀▀▀ ▀▀▄█   █▀ █ ▄▀█ █▄   ██ █▀ ▀▀▄█▄█▀█▄▄ ▀ ▄▀▀█ ▀█▀██
█ ▀ ▄▀▄▄▀███▄▀ ▄▄▀▀▀▄▄    ▀    ██▀█▀█▄  ▀▄█ ▄ ▄▀▀▀██▄██
█▄ ▀ ▀ ▄▄ ███  ▀▀█▄▄▀ ▀██ ▄▀ ▄▄▄▄▀ ▄▄▄▄▀▀▀▄▄▀ ▀ █▄█ ▄▀█
█▀  ███▄▄█▄▀▄▄█ ▄   ▄ ▀ ▀ █▄▄█  █ █ ▄█▀▄▀▀█ ▀█ ▄█▄ ▄  █
█ █▀▄▀▀▄▄▀  ▀▄ █▀█▄██▄▄█▀ ▄▄▄▄▄██▄  ▀▀ █ █ ▄▀██▄█▄▀▀▀▄█
█▄ ▀▄▄▄▄▄▄▀█▀ ▀█  ██▀█ ▀▀█▄  ▄██▄▄▄▀█▄▄ ▄█▄█▄█▀▀ █▄  ██
████▄██▄▄ ████ ███▄█ █ ▄▄ ▄▄▄ ▀▀ ██▄ ▀▀▄▄ █ ▄ ▄▄▄ █▄███
█ ▄▄▄▄▄ ████▀██▄▀ █ ██ ▄▀ █▄█ █  ▀▀▄ ▄██▄ █ ▀ █▄█ ██▄▀█
█ █   █ █▀ █▄  ███ █▀ ███   ▄  █▄█ ▄    ▀██▄▄   ▄▄▄▀ ▄█
█ █▄▄▄█ █ ▄▄███▄ ▄█ █▄ ▄██▀█▀ ▄ ▀▀▄▀ █ █▀ █▀▀█▄█ ▀ █ ██
█▄▄▄▄▄▄▄█▄█▄█▄██▄▄████▄█████▄██▄█▄▄▄▄█▄█▄██▄██▄█████▄██

{"level":30,"time":1634008092840,"pid":7831,"hostname":"MacBookl.local","class":"baileys","jid":"5511980140329:24@s.whatsapp.net","msg":"registered connection, restart server"}
credentials updated!
{"level":30,"time":1634008092845,"pid":7831,"hostname":"MacBookl.local","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"},"headers":{}}},"msg":"connection closed"}

**Comment by sudorafa** [comment]
I did this, but downt work to restoring...

import makeWASocket from '@adiwajshing/baileys-md'

async function connectToWhatsApp () {
    const conn = makeWASocket({
        // can provide additional config here
        printQRInTerminal: true
    })
    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = (lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                sock = startSock()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    })
    sock.ev.on('messages.upsert', m => {
        console.log(JSON.stringify(m, undefined, 2))

        console.log('replying to', m.messages[0].key.remoteJid)
        sendMessageWTyping({ text: 'Hello there!' }, m.messages[0].key.remoteJid!)
    })
}
// run in main file
connectToWhatsApp()

**Comment by sudorafa** [comment]
when restore:

`Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (node_modules/ws/lib/websocket.js:334:13)
    at internal/util.js:308:30
    at new Promise (<anonymous>)
    at WebSocket.send (internal/util.js:307:12)`

**Comment by makanSukros** [comment]
startSock is async function?

**Comment by JimmyBastos** [comment]
Did you solve it?
