### ISSUE TITLE
[Multi Device][BUG] [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. 

### ISSUE THREAD

**Issue by talhabalaj** [adiwajshing/Baileys#748]
I saved the creds, this happens when I try to start baileys again. btw, it spits out another error on first login aswell (Restart Required) but I guess that wants me to restart baileys? 
```
{"level":30,"time":1634640712998,"pid":23343,"hostname":"pavilion","class":"baileys","msg":"connected to WA Web"}
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
    at new NodeError (node:internal/errors:371:5)
    at Cipheriv.update (node:internal/crypto/cipher:176:11)
    at encrypt (/home/talha/dev/personal/whatsapp_v3/node_modules/baileys/lib/Utils/noise-handler.js:26:46)
    at Object.processHandshake (/home/talha/dev/personal/whatsapp_v3/node_modules/baileys/lib/Utils/noise-handler.js:102:28)
    at WebSocket.validateConnection (/home/talha/dev/personal/whatsapp_v3/node_modules/baileys/lib/Socket/socket.js:151:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
Code
```javascript
import makeWASocket, {
  AuthenticationState,
  DisconnectReason,
  initInMemoryKeyStore,
} from "baileys";
import { writeFile, readFile } from "fs/promises";

async function createWADefaultAuthenticatedSocket() {
  let auth: AuthenticationState | undefined;

  try {
    const serializedAuth = JSON.parse((await readFile("auth.json")).toString());
    auth = {
      creds: serializedAuth.creds,
      keys: initInMemoryKeyStore(serializedAuth.keys),
    };
  } catch (e) {}

  return makeWASocket({
    printQRInTerminal: true,
    auth,
  });
}

async function main() {
  let sock = await createWADefaultAuthenticatedSocket();

  sock.ev.on("auth-state.update", async (auth) => {
    await writeFile("auth.json", JSON.stringify(auth));
  });

  sock.ev.on("messages.upsert", (msg) => {
    console.log(msg.messages[0].message);
  });
}

main();
```

**Comment by khanifikhsanudin** [comment]
same problem while to try connect()

class: "Baileys"
(node:36661) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:227:22)
    at Object.createCipheriv (crypto.js:124:10)
    at Object.aesEncrypt (/Users/mac/Projects/NodeJs/baileys/src/WAConnection/Utils.ts:84:24)
    at WAConnection.sendBinary (/Users/mac/Projects/NodeJs/baileys/src/WAConnection/0.Base.ts:336:26)
    at WAConnection.<anonymous> (/Users/mac/Projects/NodeJs/baileys/src/WAConnection/4.Events.ts:21:18)
    at WAConnection.emit (events.js:375:28)
    at WAConnection.emit (domain.js:470:12)
    at WAConnection.emit (/Users/mac/Projects/NodeJs/baileys/src/WAConnection/4.Events.ts:716:72)
