### ISSUE TITLE
[ Multi Device ] WebSocket is not open

### ISSUE THREAD

**Issue by frmontini** [adiwajshing/Baileys#749]
**Describe the issue**
A few minutes after read the QR Code, i can't send messages.

**To Reproduce**
1. Create a new connection
2. Wait for a few minutes
3. Try to send a message

**Expected behavior**
I expect to send a message

**Environment (please complete the following information):**
 - Running on localhost
 - Options to start a connection: `{ logger: P({ level: 'silent' }), browser: ['MyAppName', 'Google Chrome', '18.04'] }`
 - Only my WhatsApp number on my localhost
 - I'm not using a proxy

**Additional context**
`Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (C:\projects\whatsapp-websocket\node_modules\ws\lib\websocket.js:334:13)
    at internal/util.js:308:30
    at new Promise (<anonymous>)
    at WebSocket.send (internal/util.js:307:12)
    at sendRawMessage (C:\projects\whatsapp-websocket\node_modules\@adiwajshing\baileys-md\lib\Socket\socket.js:73:28)
    at sendNode (C:\projects\whatsapp-websocket\node_modules\@adiwajshing\baileys-md\lib\Socket\socket.js:78:16)
    at query (C:\projects\whatsapp-websocket\node_modules\@adiwajshing\baileys-md\lib\Socket\socket.js:135:15)
    at assertSession (C:\projects\whatsapp-websocket\node_modules\@adiwajshing\baileys-md\lib\Socket\messages-send.js:126:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)`

**Comment by JimmyBastos** [comment]
Any update on this?
