### ISSUE TITLE
Download Media

### ISSUE THREAD

**Issue by paulocorcino** [adiwajshing/Baileys#771]
Hi!
When I try to download a media file, the method “downloadMediaMessage” returns an error, I tried many alternatives, but now I don't understand which object I need to input.

my code

```
 CLIENT.on ('chat-update', async chat => {
      if (!chat.messages) return     

      queue.add(async (a = chat, o = CLIENT) => { 

        const { messages } = a;
        const m = messages.all()[0];
        console.log(m);
              
        if(m.message.conversation || m.extendedTextMessage || m.contactMessage || m.locationMessage) {
          //text
          that.PROCESS_MESSAGE(m);
        } else {
          //media
          const buffer = o.downloadMediaMessage(m) // to decrypt & use as a buffer        
          console.log(buffer);        
        }
       });     
    });
```

```
======= 2021-10-28 08:12:18: RequestError: Cannot set property ip of #<IncomingMessage> which has only a getter RequestError: Cannot set property ip of #<IncomingMessage> which has only a getter
    at Request._beforeError (C:\what2api\baileys\node_modules\got\dist\source\core\index.js:1200:21)
    at Request._onResponse (C:\what2api\baileys\node_modules\got\dist\source\core\index.js:938:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Request._onResponseBase (C:\what2api\baileys\node_modules\got\dist\source\core\index.js:787:26)
    at Request._onResponse (C:\what2api\baileys\node_modules\got\dist\source\core\index.js:934:24)
    at ClientRequest.<anonymous> (C:\what2api\baileys\node_modules\got\dist\source\core\index.js:948:23)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:406:35)
    at ClientRequest.origin.emit (C:\what2api\baileys\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:621:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:394:28)
```

**Comment by manojsitapara** [comment]
any solution found for this issue? I am also facing same error

**Comment by paulocorcino** [comment]
> any solution found for this issue? I am also facing same error

Unfortunately, still has these problems when API need download or upload file due GOT package.

```RequestError: Cannot set property ip of #<IncomingMessage> which has only a getter RequestError: Cannot set property ip of #<IncomingMessage> which has only a getter```

Until moment has a workaround:
After npm install, open file node_modules/got/dist/source/core/index.js, go to line 793 and comment there.
