### ISSUE TITLE
Decryption of media with original HKDF key failed

### ISSUE THREAD

**Issue by kaykyr** [adiwajshing/Baileys#78]
Hello! I got this error when trying to decode media. It's a bug or I did something wrongly?

```bash
decryption of videoMessage media with original HKDF key failed
Error: HMAC sign does not match for 4
    at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:279:27
    at step (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:52:23)
    at Object.next (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:33:53)
    at fulfilled (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
decryption of imageMessage media with original HKDF key failed
Error: HMAC sign does not match for 4
    at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:279:27
    at step (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:52:23)
    at Object.next (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:33:53)
    at fulfilled (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by adiwajshing** [comment]
So this is the same error as #77. WhatsApp deletes media that hasn't been downloaded in a while & the url needs to be refreshed. Since this will be an issue for a bunch of people, I've written a function to handle this in a simple way. 

This is available in the latest commit, which you can install via `npm i github:adiwajshing/baileys`. For usage, see [here](https://github.com/adiwajshing/Baileys#downloading-media)

**Comment by kaykyr** [comment]
> So this is the same error as #77. WhatsApp deletes media that hasn't been downloaded in a while & the url needs to be refreshed. Since this will be an issue for a bunch of people, I've written a function to handle this in a simple way.
> 
> This is available in the latest commit, which you can install via `npm i github:adiwajshing/baileys`. For usage, see [here](https://github.com/adiwajshing/Baileys#downloading-media)

Thank you! I'll try it!
