### ISSUE TITLE
[Multi-device] Reconnect doesn't work

### ISSUE THREAD

**Issue by Sserpske** [adiwajshing/Baileys#783]
**Describe the bug**

After the qr code has been scanned, the auth state is saved. With this state, I could restore the session if the application was stopped. Since recently the session is not restored, and I see these errors:  
```
{"level":50,"time":1635847063170,"pid":86301,"hostname":"167","msgId":"369FF176EFB0CFADB07AC15E0BB563B8","trace":"MessageCounterError: Key used already or never filled\n    at SessionCipher.doDecryptWhisperMessage (/home/akochura/Projects/Baileys/node_modules/libsignal/src/session_cipher.js:234:19)\n    at Object.18508206634.0 [as awaitable] (/home/akochura/Projects/Baileys/node_modules/libsignal/src/session_cipher.js:205:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async _asyncQueueExecutor (/home/akochura/Projects/Baileys/node_modules/libsignal/src/queue_job.js:20:29)","data":"APgQCwb6/4YYUIIGY08DBCYI+xA2n/F277DPrbB6wV4LtWO4EjUd/wUWNYRocA38D21paGFpbG92IGFtb2NybY38BHBlZXL4AfgGFjYzBGD8kjMSIQV+SLXa7+wfeDc0CCMW5VEo1dc+mnLkR79DyLoaD+PiahohBRfqkabpB/sJubrBP8jSuD30nQS/QeXsj86hymemEhk5IkIzCiEFbQ4s9jf0EkNKIodtCef6dE4YzK+YEglyQDUCdCemtkwQABgAIhDz2H0qaWFxEjnOFZiTlyQG+QXCsxayz8QoqIjXIDAB","msg":"failure in decrypting message"}

{"level":50,"time":1635847063174,"pid":86301,"hostname":"167","msgId":"6F155B7DB3C0C74CAB536771F10E005E","trace":"MessageCounterError: Key used already or never filled\n    at SessionCipher.doDecryptWhisperMessage (/home/akochura/Projects/Baileys/node_modules/libsignal/src/session_cipher.js:234:19)\n    at Object.18508206634.0 [as awaitable] (/home/akochura/Projects/Baileys/node_modules/libsignal/src/session_cipher.js:205:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async _asyncQueueExecutor (/home/akochura/Projects/Baileys/node_modules/libsignal/src/queue_job.js:20:29)","data":"APgQCwb6/4YYUIIGY08DBCYI+xBvFVt9s8DHTKtTZ3HxDgBeEjUd/wUWNYRocA38D21paGFpbG92IGFtb2NybY38BHBlZXL4AfgGFjYzBGD9AAI0MxIhBX5Itdrv7B94NzQIIxblUSjV1z6acuRHv0PIuhoP4+JqGiEFF+qRpukH+wm5usE/yNK4PfSdBL9B5eyPzqHKZ6YSGTki4wMzCiEFbQ4s9jf0EkNKIodtCef6dE4YzK+YEglyQDUCdCemtkwQARgAIrADJA3g0GVdU7ypZrL0ekPYnmeGRFVhiIZbjydNJ/6qD7zmrrmq4XoSJynz1CBFWaZnJAyVudcMkpdrPQivA1z012QuIVJJb+ZRr/3WavP9cQBY++dQa+pgz5R/8pfCH6hUlN9uCq0fEA8RzzV56ob7vxICCNQdOrQjA7MY6lP5gAGKkPJY6MiIAg+3v2XwWyAGIWsZ3IR4pamLPFwhtzF2Y/jKPa47kRf1wh5Mw745hRXO/mRwaslB872cuEAA15BJ/6GF30svDfM6vRWRUg4d3fTFLOeoSnMQqsntqdOpPwR0Eogz39HqWsI7wLM0nf0mN4IWWhU5vvoDZXZ3QJzpUT5fTX80/oOU9nuGk78+668XE4VvVGtYHavVcSg5hD11QJEZfm30cG0yKC9sjexaOJ4eBdQfVTdq5w6Z9Tz7Lps0zP4HSsWXgtT0i5Ti2GpSPohl5Boohjbc3H65S8OEp2pUJW2LR0XoE/92wbG+okQnEHG+j+W2D4rnxVE3V8LenJSH719l4PcxK4GDi5QLjN1pdSwSUWwMq6+MJPDkBs2xX99CbhoixZ96tVfMLhsaA2yW/RWLQiAoqIjXIDAB","msg":"failure in decrypting message"}
```

**To Reproduce**
For clean reproduction, I describe everything for example.ts from the library
1. yarn example
2. Scan the qr
3. Auth state saved to auth_info_multi.json
4. Stop app with ctrl + c
5. And start it again
6. The session should be restored with the data from auth_info_multi.json
7. The session is restored, but it is impossible to receive or send messages due to encryption errors
```
{"level":50,"time":1635856173329,"pid":104818,"hostname":"167","msgId":"3EB0B6F20A059C55E07E","trace":"SessionError: No session record\n    at Object.<phone_number>:47.0 [as awaitable] (/home/akochura/Desktop/Projects/Baileys/node_modules/libsignal/src/session_cipher.js:167:23)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async _asyncQueueExecutor (/home/akochura/Desktop/Projects/Baileys/node_modules/libsignal/src/queue_job.js:20:29)","data":"APgMCwb3AC//hnkWZkWWbwQmCPsKPrC28goFnFXgfh3/BRY1hWFzDfwKa2xhc3NuZW5refgB+AYWNjMEQvySMwohBcEwDRrtPNg1tewgQd+dTvhQKQrwy4/sTUVGlEZQQMJdEAAYACJgXaI8MR58V+AyTy6W667iPJ8LX1vOKczV5TuG3MyBNAJTETL7WYjTokTfnzH/vSJUVx0/5g/HdoTR6gllhzEZHpCCnlspx1b7ahvtjjFzT6yxljzRhqPE/ks1RYRRAujlxBnbij4ZU5E=","msg":"failure in decrypting message"}
```

**Expected behavior**
I expect the session to be restored without problems.

**Environment (please complete the following information):**
Running locally, not on the server.  
I tried different options to connect, for example this  
```
{
    logger: logger({ level: 'trace' }),
    auth: loadState(),
}

```   
or this  

```
{
    logger: P({ level: 'trace' }), 
    auth: authState,
    browser: ['Windows', 'Google Chrome', '90'],
    version: [2, 2142, 12],
}
```

I have one client per IP  
I don't use proxies  

**Additional context**
I have noticed that this problem is sometimes not there. But it is reproduced in 8 cases of 10

**Comment by guilhermegehres** [comment]
Same issue here

**Comment by jaysixnine** [comment]
Same here
