### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by nazaltk** [adiwajshing/Baileys#883]
When I scan the QR Code, it is showing following exception in the console. Please help me to understand this issue.

`
encountered error: TypeError: Cannot read property 'toString' of undefined
(node:12960) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:305:13)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:117:10)
    at Object.aesEncrypt (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\Utils.ts:82:24)
    at WAConnection.sendBinary (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\0.Base.ts:336:26)
    at WAConnection.<anonymous> (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\4.Events.ts:21:18)
    at WAConnection.emit (events.js:310:20)
    at WAConnection.EventEmitter.emit (domain.js:482:12)
    at WAConnection.emit (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\4.Events.ts:712:72)
(node:12960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12960) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12960) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:305:13)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:117:10)
    at Object.aesEncrypt (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\Utils.ts:82:24)
    at WAConnection.sendBinary (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\0.Base.ts:336:26)
    at WAConnection.<anonymous> (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\4.Events.ts:22:18)
    at WAConnection.emit (events.js:310:20)
    at WAConnection.EventEmitter.emit (domain.js:482:12)
    at WAConnection.emit (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\4.Events.ts:712:72)
(node:12960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12960) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:305:13)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:117:10)
    at Object.aesEncrypt (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\Utils.ts:82:24)
    at WAConnection.sendBinary (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\0.Base.ts:336:26)
    at WAConnection.<anonymous> (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\4.Events.ts:23:18)
    at WAConnection.emit (events.js:310:20)
    at WAConnection.EventEmitter.emit (domain.js:482:12)
    at WAConnection.emit (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\4.Events.ts:712:72)
(node:12960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:12960) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:305:13)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:117:10)
    at Object.aesEncrypt (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\Utils.ts:82:24)
    at WAConnection.sendBinary (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\0.Base.ts:336:26)
    at WAConnection.<anonymous> (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\4.Events.ts:24:18)
    at WAConnection.emit (events.js:310:20)
    at WAConnection.EventEmitter.emit (domain.js:482:12)
    at WAConnection.emit (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\4.Events.ts:712:72)
(node:12960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:12960) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:305:13)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:117:10)
    at Object.aesEncrypt (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\Utils.ts:82:24)
    at WAConnection.sendBinary (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\0.Base.ts:336:26)
    at WAConnection.<anonymous> (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\4.Events.ts:25:18)
    at WAConnection.emit (events.js:310:20)
    at WAConnection.EventEmitter.emit (domain.js:482:12)
    at WAConnection.emit (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\4.Events.ts:712:72)
(node:12960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:12960) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:305:13)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:117:10)
    at Object.aesEncrypt (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\Utils.ts:82:24)
    at WAConnection.sendBinary (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\0.Base.ts:336:26)
    at WAConnection.<anonymous> (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\4.Events.ts:26:18)
    at WAConnection.emit (events.js:310:20)
    at WAConnection.EventEmitter.emit (domain.js:482:12)
    at WAConnection.emit (N:\Web Works\WhatsApp Bot\Angular\npm js\Baileys\src\WAConnection\4.Events.ts:712:72)
(node:12960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
`

**Comment by canove** [comment]
You probably  trying to scan a Baileys legacy QR using a multi device Whatsapp

**Comment by nazaltk** [comment]
Hi, @canove  Yes, I am using a multi-device WhatsApp.  How can I fix this?

**Comment by canove** [comment]
You should follow the instructions on this branch: https://github.com/adiwajshing/Baileys/tree/multi-device

**Comment by borjita2019** [comment]
@nazaltk did you fix it?

**Comment by nazaltk** [comment]
Using the Code from the above branch I was able to connect with the WhatsApp having Multi-Device feature.
