### ISSUE TITLE
Error when trying to scan code

### ISSUE THREAD

**Issue by borjita2019** [adiwajshing/Baileys#885]
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (C:\Users\borjoto\Desktop\lol\FX-SELF-BOT-v83.2\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (C:\Users\borjoto\Desktop\lol\FX-SELF-BOT-v83.2\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (C:\Users\borjoto\Desktop\lol\FX-SELF-BOT-v83.2\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:86:18)
    at WAConnection.emit (node:events:402:35)
    at WAConnection.emit (C:\Users\borjoto\Desktop\lol\FX-SELF-BOT-v83.2\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41)
    at WAConnection.connect (C:\Users\borjoto\Desktop\lol\FX-SELF-BOT-v83.2\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:70:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async starts (C:\Users\borjoto\Desktop\lol\FX-SELF-BOT-v83.2\index.js:1:389255) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by canove** [comment]
https://github.com/adiwajshing/Baileys/issues/883
