### ISSUE TITLE
[MD BUG] failed to sync app state

### ISSUE THREAD

**Issue by nazaltk** [adiwajshing/Baileys#903]
I am using the MD version. I already connected using my WhatsApp. After a few hours when I restarted the app it is showing the below error. Please help me to understand this error.

{"level":40,"time":1637467609504,"pid":8448,"hostname":"Nazal","class":"baileys","trace":"Error: tried remove, but no buffer\n    at computeLtHash (N:\\Web Works\\WhatsApp Bot\\w-Bot\\Baileys\\src\\Utils\\chat-utils.ts:62:23)\n    at decodePatches (N:\\Web Works\\WhatsApp Bot\\w-Bot\\Baileys\\src\\Utils\\chat-utils.ts:302:19)\n    at resyncAppState (N:\\Web Works\\WhatsApp Bot\\w-Bot\\Baileys\\src\\Socket\\chats.ts:214:78)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async resyncMainAppState (N:\\Web Works\\WhatsApp Bot\\w-Bot\\Baileys\\src\\Socket\\chats.ts:309:9)","msg":"failed to sync app state"}`

**Comment by jrvidotti** [comment]
Hi! I am also getting this kind of error here:

```
[2021-02-22 12:11:13.348] WARN: (WASocket) failed to sync app state
    trace: "Error: failed to verify LTHash at 5 of critical_unblock_low
    at Object.decodePatches (/Users/junior/dev/wamanager/node_modules/@adiwajshing/baileys-md/lib/Utils/chat-utils.js:280:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resyncAppState (/Users/junior/dev/wamanager/node_modules/@adiwajshing/baileys-md/lib/Socket/chats.js:185:59)
    at async resyncMainAppState (/Users/junior/dev/wamanager/node_modules/@adiwajshing/baileys-md/lib/Socket/chats.js:273:9)"
```

Program continues to run, but why this is happening?

**Comment by adiwajshing** [comment]
Should be fixed in: https://github.com/adiwajshing/Baileys/pull/696/commits/b4332488b833f1a079d89636eb1a09293050dee7
