### ISSUE TITLE
[MD][BUG] [DUPLICATE] Socket get disconnected after a few moments 

### ISSUE THREAD

**Issue by JimmyBastos** [adiwajshing/Baileys#923]
**Describe the bug**
I'm able to restore a session from database and wait for connection to be open before perform any action (such groupMetadata), but when I try to run any other task the get close immediately after get opened.

PS: The WASocket instance get cached between requests.

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials from database to log back in
3. Perform some action, like get group metadata
4. Perform another action 

**Expected behavior**
Log back in and get groupMetadata

**Environment (please complete the following information):**
 - Is this on a server? No. 
 
 - What do your `connectOptions` look like?  
```typescript
const config = {
      printQRInTerminal: process.env.WP_LOG_QRCODE,
      auth: {
        creds: account.session.creds,
        keys: initInMemoryKeyStore(account.session.keys, () => {})
      }
}

// or
const config = {
      printQRInTerminal: process.env.WP_LOG_QRCODE,
      auth:  { creds: initAuthCreds(), keys: initInMemoryKeyStore({}, () => {}) }
}
```

```typescript
// whatsapp-account.entity.ts
@Exclude()
@Column({
  type: 'varchar',
  transformer: {
    from: (databaseValue: string) => {
      return databaseValue
        ? JSON.parse(databaseValue, BufferJSON.reviver)
        : null
    },
    to: (objectValue: any) => {
      return objectValue
        ? JSON.stringify(objectValue, BufferJSON.replacer, 2)
        : null
    }
  }
})
  session: Record<string, unknown>
```
 - Do you have multiple clients on the same IP? Yes
 - Are you using a proxy? No

**Additional context**

 -  Node v16.13.0
 -  Software
Operating System: Fedora 34
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.14.17-201.fc34.x86_64 (64-bit)
Graphics Platform: X11

- Hardware
Processors: 24 × Intel® Xeon® CPU E5-2678 v3 @ 2.50GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Radeon RX 550 Series

**Logs**

```logs
connection.update connecting
connection.update connecting
{"level":30,"time":1637877797806,"pid":56527,"hostname":"fedora","class":"baileys","msg":"connected to WA Web"}
{"level":30,"time":1637877797949,"pid":56527,"hostname":"fedora","class":"baileys","msg":"handshake complete"}
{"level":30,"time":1637877797949,"pid":56527,"hostname":"fedora","class":"baileys","msg":"logging in..."}
{"level":30,"time":1637877798113,"pid":56527,"hostname":"fedora","class":"baileys","msg":"opened connection to WA"}
connection.update open
connection.update open
{"level":30,"time":1637877798303,"pid":56527,"hostname":"fedora","class":"baileys","msg":"got 0 offline messages/notifications"}
connection.update undefined
connection.update undefined
connection.update connecting
connection.update connecting
{"level":30,"time":1637877808628,"pid":56527,"hostname":"fedora","class":"baileys","msg":"connected to WA Web"}
{"level":30,"time":1637877808750,"pid":56527,"hostname":"fedora","class":"baileys","msg":"handshake complete"}
{"level":30,"time":1637877808750,"pid":56527,"hostname":"fedora","class":"baileys","msg":"logging in..."}
{"level":30,"time":1637877808879,"pid":56527,"hostname":"fedora","class":"baileys","msg":"opened connection to WA"}
connection.update open
connection.update open
{"level":50,"time":1637877808992,"pid":56527,"hostname":"fedora","class":"baileys","error":{"tag":"stream:error","attrs":{},"content":[{"tag":"conflict","attrs":{"type":"replaced"},"content":null}]},"msg":"stream errored out"}
{"level":30,"time":1637877808993,"pid":56527,"hostname":"fedora","class":"baileys","error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"conflict","attrs":{"type":"replaced"},"content":null}]},"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Stream Errored"},"headers":{}}},"msg":"connection closed"}
connection.update close
connection.update close
{"level":30,"time":1637877809001,"pid":56527,"hostname":"fedora","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"msg":"connection closed"}
connection.update connecting
Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (/home/jimmy/Projetos/Autozap.io/autozap/node_modules/@adiwajshing/baileys-md/node_modules/ws/lib/websocket.js:391:13)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at WebSocket.send (node:internal/util:346:12)
    at sendRawMessage (/home/jimmy/Projetos/Autozap.io/autozap/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:82:28)
    at sendNode (/home/jimmy/Projetos/Autozap.io/autozap/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:87:16)
    at query (/home/jimmy/Projetos/Autozap.io/autozap/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:144:15)
    at groupQuery (/home/jimmy/Projetos/Autozap.io/autozap/node_modules/@adiwajshing/baileys-md/lib/Socket/groups.js:10:55)
    at Object.groupInviteCode (/home/jimmy/Projetos/Autozap.io/autozap/node_modules/@adiwajshing/baileys-md/lib/Socket/groups.js:89:34)
    at BaileysMultideviceService.getGroupInviteCode (/home/jimmy/Projetos/Autozap.io/autozap/src/modules/whatsapps/api/providers/baileys-multidevice.service.ts:86:30)
{"level":30,"time":1637877809056,"pid":56527,"hostname":"fedora","class":"baileys","msg":"got 0 offline messages/notifications"}
connection.update undefined
connection.update undefined
{"level":30,"time":1637877809334,"pid":56527,"hostname":"fedora","class":"baileys","msg":"connected to WA Web"}
{"level":30,"time":1637877809440,"pid":56527,"hostname":"fedora","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated"},"headers":{}}},"msg":"connection closed"}
connection.update close
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1006".
```

**Comment by JimmyBastos** [comment]
Closed by github bot: #732 #749 #452 #75
