### ISSUE TITLE
Error: Unexpected status code: 400 when presence status is "Typing..."

### ISSUE THREAD

**Issue by kaykyr** [adiwajshing/Baileys#94]
```bash
(node:36325) UnhandledPromiseRejectionWarning: Error: Unexpected status code: 400
    at /Users/kaykyramos/Desktop/WhatsApp-Socket/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:121:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I am facing this issue when I request userPresence and my callback `client.setOnPresenceUpdate` return this error when status is typing.

**Comment by kaykyr** [comment]
My bad
