### ISSUE TITLE
help [md]

### ISSUE THREAD

**Issue by amiruldev20** [adiwajshing/Baileys#951]
send me an example of deleting chat, i tried to make it but error

TypeError: Cannot use 'in' operator to search for 'mute' in 6281312995073@s.whatsapp.net
    at Object.chatModificationToAppPatch (\home\usr\root\mywamd2\node_modules\@adiwajshing\baileys-md\lib\Utils\chat-utils.js:351:16)
    at Object.chatModify (\home\usr\root\mywamd2\node_modules\@adiwajshing\baileys-md\lib\Socket\chats.js:421:31)
    at Object.eval (eval at handler (\home\usr\root\mywamd2\plugins\exec1.js:15:16), <anonymous>:3:13)
    at Object.handler (\home\usr\root\mywamd2\plugins\exec1.js:16:26)
    at Object.handler (\home\usr\root\mywamd2\handler.js:295:14)

**Comment by phaticusthiccy** [comment]
Can you send the exec1.js's code?
