### ISSUE TITLE
How to fix websocket [md]

### ISSUE THREAD

**Issue by scoder37** [adiwajshing/Baileys#952]
(node:14152) UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 2 (CLOSING)
    at sendAfterClose (C:\Users\rdp\Desktop\mywamd2\node_modules\ws\lib\websocket.js:928:17)
    at WebSocket.send (C:\Users\rdp\Desktop\mywamd2\node_modules\ws\lib\websocket.js:405:7)
    at internal/util.js:340:30
    at new Promise (<anonymous>)

**Comment by Ethernit** [comment]
Post script
