### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by kaykyr** [adiwajshing/Baileys#97]
```bash
Error: Cannot find module '/Users/kaykyramos/Desktop/WhatsApp-Socket/node_modules/@adiwajshing/keyed-db/lib/KeyedDB.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:322:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:683:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/kaykyramos/Desktop/WhatsApp-Socket/node_modules/@adiwajshing/baileys/lib/WAConnection/Connect.js:26:36)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.newLoader [as .js] (/Users/kaykyramos/Desktop/WhatsApp-Socket/node_modules/pirates/lib/index.js:104:7) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/kaykyramos/Desktop/WhatsApp-Socket/node_modules/@adiwajshing/keyed-db/package.json',
  requestPath: '@adiwajshing/keyed-db'
}
```

Hello! There a problem with last package release or this is my fault? I just `yarn add @adiwajshing/baileys`

**Comment by kaykyr** [comment]
Fixed when I did `yarn` inside `keyed-db` folder.

**Comment by adiwajshing** [comment]
Yarn has an issue with GitHub packages -- I'll implement a workaround.

**Comment by adiwajshing** [comment]
Should be fixed now.

**Comment by kaykyr** [comment]
> Should be fixed now.

Great! I'll wait until next update! :)

**Comment by code-by** [comment]
catch this with v.4.1.0.
