### ISSUE TITLE
Automated test returning false negative

### ISSUE THREAD

**Issue by AZMCode** [adiwajshing/Baileys#99]
I find myself passing in a message with a quote, and nothing gets quoted.
Note: I am getting these messages from the setOnUnreadMessages event.

**Comment by adiwajshing** [comment]
Can you provide some code?

**Comment by AZMCode** [comment]
I'll try to replicate it in a cleaner environment. Gimme a sec.

**Comment by AZMCode** [comment]
```
const { WAClient, MessageType } = require("@adiwajshing/baileys");
(async()=>{
    const client = new WAClient()
    await client.connect()
    client.setOnUnreadMessage(true,(obj)=>{
        client.sendMessage(obj.key.remoteJid,"MessageBack",MessageType.extendedText,{quote: obj.message})
    })
})()
```

Responds correctly, but without the quote

**Comment by AZMCode** [comment]
Edited the question body to focus on one bug at a time. Also removed the misconception you couldn't fetch a lone message by its ID.

**Comment by AZMCode** [comment]
It is of note I'm running this on Termux in Android

**Comment by adiwajshing** [comment]
So, the problem is twofold:
``` ts
const options = {quote: obj.message} // incorrect
const optionsCorrect = {quoted: obj} // correct, should be `quoted` & quote the entire message object
client.sendMessage(obj.key.remoteJid,"MessageBack",MessageType.extendedText,options)
```

**Comment by AZMCode** [comment]
```
const { WAClient, MessageType } = require("@adiwajshing/baileys");
(async()=>{
    const client = new WAClient()
    await client.connect()
    client.setOnUnreadMessage(true,(obj)=>{
    const quotedMessage = obj.message.extendedTextMessage.contextInfo.quotedMessage;
        client.sendMessage(obj.key.remoteJid,"MessageBack",MessageType.extendedText,{quote: quotedMessage})
    })
})()
```
(This example required the receiving of a message qith a quote)
If you quote the quote of the notification it happens asw.

**Comment by AZMCode** [comment]
So the quote parameter is meant to receive a message context?

**Comment by AZMCode** [comment]
```
const { WAClient, MessageType } = require("@adiwajshing/baileys");
(async()=>{
    const client = new WAClient()
    await client.connect()
    client.setOnUnreadMessage(true,(obj)=>{
        client.sendMessage(obj.key.remoteJid,"MessageBack",MessageType.extendedText,{quoted: obj})
    })
})()
```
I'm running this corrected example and the quote still wont appear.

**Comment by adiwajshing** [comment]
Super weird. Can you run the test for this: `mocha --timeout 60000 -r ts-node/register -g 'quote a message' src/*/Tests.ts`? See if that works? Do make sure you set the `TEST_JID` in a `.env` file before you run the tests

**Comment by AZMCode** [comment]
Sure, gimme a sec

**Comment by AZMCode** [comment]
I think I accidentally sent a message to a stranger XD
anyways, I got this:

```
   1) should quote a message


  0 passing (6s)
  1 failing

  1) Messages
       should quote a message:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ '08674A5EDEBC55A855116083766A2590'
- '8FD0B838D51ADF10291C'
      + expected - actual

      -08674A5EDEBC55A855116083766A2590
      +8FD0B838D51ADF10291C
      
      at sendAndRetreiveMessage (src/WAClient/Tests.ts:17:12)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Context.<anonymous> (src/WAClient/Tests.ts:58:25)


```

**Comment by AZMCode** [comment]
And the message did not have a quote, ofc

**Comment by AZMCode** [comment]
Can you reproduce it on your side?

**Comment by adiwajshing** [comment]
It's working on my end, just ran the test. Are you using the github link or the npm link?

**Comment by AZMCode** [comment]
Npm

**Comment by adiwajshing** [comment]
Can you try with the GitHub link ‘npm i github:adiwajshing/baileys’?

**Comment by AZMCode** [comment]
Gimme a sec

**Comment by AZMCode** [comment]
NVM, the way I did it was cloning the repo, got confused.

**Comment by AZMCode** [comment]
I'll try both in a sec

**Comment by AZMCode** [comment]
So, cloning the repo is what I did above, but now as a package from either npm or github I'm getting Error 400's

**Comment by AZMCode** [comment]
```
  1) Messages
       should quote a message:
     Error: error in query, got status: 400
      at WhatsAppWebMessages.loadConversation (src/WAClient/Base.ts:162:36)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Context.<anonymous> (src/WAClient/Tests.ts:57:26)

```

**Comment by AZMCode** [comment]
> So, cloning the repo is what I did above, but now as a package from either npm or github I'm getting Error 400's

I used the package this very morning so that's weird af

**Comment by AZMCode** [comment]
Yup, now even cloning the repo gets me Error 400'd

**Comment by AZMCode** [comment]
Ill try to access through tor in case it's a network problem

**Comment by AZMCode** [comment]
Nope, even through tor.
WhatsApp broke your code this very day.
I'll get back with more data when you manage to fix that.

**Comment by adiwajshing** [comment]
WhatsApp is working just fine. In your `.env` file, the `TEST_JID` must be in the format: `TEST_JID=123456789012@s.whatsapp.net`. Also, ensure you have a conversation with them.

**Comment by AZMCode** [comment]
Already took care of both of those. I'll try again rn

**Comment by AZMCode** [comment]
Using the following .env in the same folder as package.json (Censored for privacy reasons):
```
TEST_JID=******@s.whatsapp.net
```
npm package yields this:
```
$ ./node_modules/.bin/mocha --timeout 60000 -r ts-node/register -g 'quote a message' src/*/Tests.ts


  Messages
[Baileys][8/9/2020, 8:49:21 AM] loading authentication credentials from ./auth_info.json
[Baileys][8/9/2020, 8:49:22 AM] connected to WhatsApp Web, authenticating...
[Baileys][8/9/2020, 8:49:22 AM] resolving login challenge
[Baileys][8/9/2020, 8:49:23 AM] validated connection successfully
    1) should quote a message


  0 passing (6s)
  1 failing

  1) Messages
       should quote a message:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ '617EF25F0CDD9BC1A0267F4D224D89DB'
- '4884C3AF422C5045F9EF'
      + expected - actual

      -617EF25F0CDD9BC1A0267F4D224D89DB
      +4884C3AF422C5045F9EF
      
      at sendAndRetreiveMessage (src/WAClient/Tests.ts:17:12)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Context.<anonymous> (src/WAClient/Tests.ts:58:25)




```
Although the mesage sends just fine, quote and all...


github clone yields similar results like this:

```
$ ./node_modules/.bin/mocha --timeout 60000 -r ts-node/register -g 'quote a message' src/*/Tests.ts


  Messages
[Baileys][8/9/2020, 8:55:21 AM] loading authentication credentials from ./auth_info.json
[Baileys][8/9/2020, 8:55:22 AM] connected to WhatsApp Web, authenticating...
[Baileys][8/9/2020, 8:55:22 AM] resolving login challenge
[Baileys][8/9/2020, 8:55:23 AM] validated connection successfully
    1) should quote a message


  0 passing (6s)
  1 failing

  1) Messages
       should quote a message:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ '4884C3AF422C5045F9EF'
- 'BB095FBB45B1E5E6100F'
      + expected - actual

      -4884C3AF422C5045F9EF
      +BB095FBB45B1E5E6100F
      
      at sendAndRetreiveMessage (src/WAClient/Tests.ts:17:12)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Context.<anonymous> (src/WAClient/Tests.ts:58:25)




```
Again, sending a quoted message just fine

And the test code that [began everything](https://github.com/adiwajshing/Baileys/issues/99#issuecomment-670956908), using the node module works. Whaaat?

 Guess this is now a bug in testing then.

**Comment by AZMCode** [comment]
So, I've modified my program for a bit in accordance to your advice (Thank you *so* much btw), and I think I've encountered a similar bug to what started all of this. I'll set it up in a separate issue

**Comment by adiwajshing** [comment]
This should be resolved in the latest commit.

**Comment by AZMCode** [comment]
I'll check it on my side in a bit

**Comment by AZMCode** [comment]
On Master:
```
$ ./node_modules/.bin/mocha --timeout 60000 -r ts-node/register -g 'quote a message'
Error: No test files found: "test"
```

**Comment by AZMCode** [comment]
Attempted to run 
```
$ ./node_modules/.bin/mocha --timeout 60000 -r ts-node/register -g 'quote a message' src/*/Tests.ts
```
Got this:
```
Error: No test files found: "src/*/Tests.ts"
```

**Comment by AZMCode** [comment]
Edited the glob given from
`./node_modules/.bin/mocha --timeout 60000 -r ts-node/register -g 'quote a message' src/*/Tests.ts` to `./node_modules/.bin/mocha --timeout 60000 -r ts-node/register -g 'quote a message' src/*/Tests.*.ts` to get the tests to run. Got this on ubuntu:


```
  0 passing (6s)
  2 failing

  1) Groups
       should quote a message on the group:
     BaileysError: Unexpected status code in 'query': 400
      at WAConnection.queryExpecting200 (src/WAConnection/0.Base.ts:271:19)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at WAConnection.loadConversation (src/WAConnection/4.User.ts:120:26)
      at Context.<anonymous> (src/Tests/Tests.Groups.ts:35:26)

  2) Messages
       should quote a message:
     TypeError: Cannot read property 'contextInfo' of null
      at Context.<anonymous> (src/Tests/Tests.Messages.ts:35:64)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

```
