### ISSUE TITLE
[BUG] [MD]  "failed to sync state" after logout

### ISSUE THREAD

**Issue by danielteodorodt** [adiwajshing/Baileys#997]
**Describe the bug**
If you connect the QR Code, then disconnect through the WhatsApp app, a certain time after this error. On average it's minutes after you disconnect.

```
{"level":30,"time":1639067932440,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","collections":["regular_high"],"error":"Error: Timed Out\n    at /home/zerofill/Baileys/src/Utils/generics.ts:164:13","msg":"failed to sync state from version, trying from scratch"}
{"level":30,"time":1639067932440,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","msg":"resyncing regular_high from v0"}
{"level":50,"time":1639067932443,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","trace":"Error: WebSocket is not open: readyState 3 (CLOSED)\n    at sendAfterClose (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:900:17)\n    at WebSocket.send (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:402:7)\n    at node:internal/util:360:7\n    at new Promise (<anonymous>)\n    at WebSocket.send (node:internal/util:346:12)\n    at sendRawMessage (/home/zerofill/Baileys/src/Socket/socket.ts:73:28)\n    at sendNode (/home/zerofill/Baileys/src/Socket/socket.ts:78:16)\n    at query (/home/zerofill/Baileys/src/Socket/socket.ts:144:15)\n    at resyncAppStateInternal (/home/zerofill/Baileys/src/Socket/chats.ts:185:30)\n    at resyncAppState (/home/zerofill/Baileys/src/Socket/chats.ts:247:28)","node":{"tag":"notification","attrs":{"from":"@s.whatsapp.net","type":"server_sync","id":"3059861429","t":"1639067872"},"content":[{"tag":"collection","attrs":{"name":"regular_high","version":"29"},"content":null}]},"msg":"failed to sync state"}
{"level":30,"time":1639067932443,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","msg":"resyncing regular_low from v29"}
{"level":30,"time":1639067932444,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","collections":["regular_low"],"error":"Error: WebSocket is not open: readyState 3 (CLOSED)\n    at sendAfterClose (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:900:17)\n    at WebSocket.send (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:402:7)\n    at node:internal/util:360:7\n    at new Promise (<anonymous>)\n    at WebSocket.send (node:internal/util:346:12)\n    at sendRawMessage (/home/zerofill/Baileys/src/Socket/socket.ts:73:28)\n    at sendNode (/home/zerofill/Baileys/src/Socket/socket.ts:78:16)\n    at query (/home/zerofill/Baileys/src/Socket/socket.ts:144:15)\n    at resyncAppStateInternal (/home/zerofill/Baileys/src/Socket/chats.ts:185:30)\n    at async resyncAppState (/home/zerofill/Baileys/src/Socket/chats.ts:244:22)","msg":"failed to sync state from version, trying from scratch"}
{"level":30,"time":1639067932444,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","msg":"resyncing regular_low from v0"}
{"level":50,"time":1639067932445,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","trace":"Error: WebSocket is not open: readyState 3 (CLOSED)\n    at sendAfterClose (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:900:17)\n    at WebSocket.send (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:402:7)\n    at node:internal/util:360:7\n    at new Promise (<anonymous>)\n    at WebSocket.send (node:internal/util:346:12)\n    at sendRawMessage (/home/zerofill/Baileys/src/Socket/socket.ts:73:28)\n    at sendNode (/home/zerofill/Baileys/src/Socket/socket.ts:78:16)\n    at query (/home/zerofill/Baileys/src/Socket/socket.ts:144:15)\n    at resyncAppStateInternal (/home/zerofill/Baileys/src/Socket/chats.ts:185:30)\n    at resyncAppState (/home/zerofill/Baileys/src/Socket/chats.ts:247:28)","node":{"tag":"notification","attrs":{"from":"@s.whatsapp.net","type":"server_sync","id":"2992272459","t":"1639067872"},"content":[{"tag":"collection","attrs":{"name":"regular_low","version":"30"},"content":null}]},"msg":"failed to sync state"}
{"level":30,"time":1639067932446,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","msg":"resyncing critical_block from v29"}
{"level":30,"time":1639067932448,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","collections":["critical_block"],"error":"Error: WebSocket is not open: readyState 3 (CLOSED)\n    at sendAfterClose (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:900:17)\n    at WebSocket.send (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:402:7)\n    at node:internal/util:360:7\n    at new Promise (<anonymous>)\n    at WebSocket.send (node:internal/util:346:12)\n    at sendRawMessage (/home/zerofill/Baileys/src/Socket/socket.ts:73:28)\n    at sendNode (/home/zerofill/Baileys/src/Socket/socket.ts:78:16)\n    at query (/home/zerofill/Baileys/src/Socket/socket.ts:144:15)\n    at resyncAppStateInternal (/home/zerofill/Baileys/src/Socket/chats.ts:185:30)\n    at async resyncAppState (/home/zerofill/Baileys/src/Socket/chats.ts:244:22)","msg":"failed to sync state from version, trying from scratch"}
{"level":30,"time":1639067932448,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","msg":"resyncing critical_block from v0"}
{"level":50,"time":1639067932449,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","trace":"Error: WebSocket is not open: readyState 3 (CLOSED)\n    at sendAfterClose (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:900:17)\n    at WebSocket.send (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:402:7)\n    at node:internal/util:360:7\n    at new Promise (<anonymous>)\n    at WebSocket.send (node:internal/util:346:12)\n    at sendRawMessage (/home/zerofill/Baileys/src/Socket/socket.ts:73:28)\n    at sendNode (/home/zerofill/Baileys/src/Socket/socket.ts:78:16)\n    at query (/home/zerofill/Baileys/src/Socket/socket.ts:144:15)\n    at resyncAppStateInternal (/home/zerofill/Baileys/src/Socket/chats.ts:185:30)\n    at resyncAppState (/home/zerofill/Baileys/src/Socket/chats.ts:247:28)","node":{"tag":"notification","attrs":{"from":"@s.whatsapp.net","type":"server_sync","id":"2845188928","t":"1639067872"},"content":[{"tag":"collection","attrs":{"name":"critical_block","version":"30"},"content":null}]},"msg":"failed to sync state"}
{"level":30,"time":1639067932450,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","msg":"resyncing critical_unblock_low from v29"}
{"level":30,"time":1639067932452,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","collections":["critical_unblock_low"],"error":"Error: WebSocket is not open: readyState 3 (CLOSED)\n    at sendAfterClose (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:900:17)\n    at WebSocket.send (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:402:7)\n    at node:internal/util:360:7\n    at new Promise (<anonymous>)\n    at WebSocket.send (node:internal/util:346:12)\n    at sendRawMessage (/home/zerofill/Baileys/src/Socket/socket.ts:73:28)\n    at sendNode (/home/zerofill/Baileys/src/Socket/socket.ts:78:16)\n    at query (/home/zerofill/Baileys/src/Socket/socket.ts:144:15)\n    at resyncAppStateInternal (/home/zerofill/Baileys/src/Socket/chats.ts:185:30)\n    at async resyncAppState (/home/zerofill/Baileys/src/Socket/chats.ts:244:22)","msg":"failed to sync state from version, trying from scratch"}
{"level":30,"time":1639067932452,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","msg":"resyncing critical_unblock_low from v0"}
{"level":50,"time":1639067932453,"pid":8862,"hostname":"DESKTOP-NT7VJ4A","trace":"Error: WebSocket is not open: readyState 3 (CLOSED)\n    at sendAfterClose (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:900:17)\n    at WebSocket.send (/home/zerofill/Baileys/node_modules/ws/lib/websocket.js:402:7)\n    at node:internal/util:360:7\n    at new Promise (<anonymous>)\n    at WebSocket.send (node:internal/util:346:12)\n    at sendRawMessage (/home/zerofill/Baileys/src/Socket/socket.ts:73:28)\n    at sendNode (/home/zerofill/Baileys/src/Socket/socket.ts:78:16)\n    at query (/home/zerofill/Baileys/src/Socket/socket.ts:144:15)\n    at resyncAppStateInternal (/home/zerofill/Baileys/src/Socket/chats.ts:185:30)\n    at resyncAppState (/home/zerofill/Baileys/src/Socket/chats.ts:247:28)","node":{"tag":"notification","attrs":{"from":"@s.whatsapp.net","type":"server_sync","id":"2188599390","t":"1639067872"},"content":[{"tag":"collection","attrs":{"name":"critical_unblock_low","version":"30"},"content":null}]},"msg":"failed to sync state"}
```
**To Reproduce**
1. Created a new connection
2. Logout WhatsApp application
3. Wait up to 3 minutes to see the error appear

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - Do you have multiple clients on the same IP? Not
 - Are you using a proxy? Yes

**Comment by danielteodorodt** [comment]
> Daniel, a sua tradução ficou ruim, não consegui entender o que você quis dizer. abri uma issue no seu projeto me chama lá.

Eu quis informar que após alguns minutos, depois de deslogar a conexão do aplicativo do WhatsApp, é emitido um erro de "failed to sync state" e logo após é emitido um erro de Timed Out.

**Comment by mateuscdor** [comment]
Esse deslogar (é desconectar a sessão do aplicativo ? ) 
ou ficar com wi-fi desligado no aparelho?

Se for desconetar da sessão, precisamos ver o código de update que você está utilizando
existe 2 atualmente em funcionamento.

**Comment by danielteodorodt** [comment]
Sim, deslogar a sessão do aplicativo. E não fazer logout pelo código.

**Comment by olezhko9** [comment]
Same problem.

After logout using my phone i get about the same error 7 times:

```
"Error: Connection Closed
at sendRawMessage (/home/olezhko/Документы/backend/WA-service/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:82:19)
at sendNode (/home/olezhko/Документы/backend/WA-service/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:90:16)
at query (/home/olezhko/Документы/backend/WA-service/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:149:15)"
...
"node":{"tag":"notification","attrs": {from":"@s.whatsapp.net","type":"server_sync","id":"1588866104","t":"1639747709"},"content":[{"tag":"collection","attrs":{"name":"regular_high","version":"13"},"content":null}]},"msg":"failed to sync state"
```

Then an error occurs that crashes application:
```
Error: Timed Out
    at /home/olezhko/Документы/backend/WA-service/node_modules/@adiwajshing/baileys-md/lib/Utils/generics.js:151:32
```

**Comment by barkerpedro** [comment]
Same problem.

**Comment by zhengshengjie666** [comment]
at promiseTimeout (d:\\works\\whatsapp-workspace\\Baileys\\src\\Utils\\generics.ts:158:19)\n' +

同样的问题

**Comment by code-by** [comment]
is some one resolve how to do new connection after `logout()` ?
